-- AgentOS baseline schema.
--
-- One migration, one schema: the full database this branch serves. It
-- replaces the fifty-six incremental pairs this project accumulated
-- before any production database existed - including the drops,
-- re-creations, and a dead template table, none of which deserve a
-- place in a fresh database's history.
--
-- Generated by applying the previous chain to a clean PostgreSQL 18
-- database and dumping the result (pg_dump --schema-only --no-owner
-- --no-privileges, excluding golang-migrate's schema_migrations book
-- table and the unreferenced template `history` table). Equivalence
-- was verified before the swap: the two databases were diffed
-- pg_dump-for-pg_dump, and sqlc-check proves the generated bindings
-- did not move. pg_dump's restore-session preamble (SET ... and
-- set_config search_path) is deliberately dropped: it is not schema,
-- and tests exec this file on pooled connections whose session state
-- must stay untouched.

--
-- Name: enforce_delivered_plan_command_audit(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enforce_delivered_plan_command_audit() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF NEW.status = 'delivered' AND NOT EXISTS (
        SELECT 1
        FROM audit_logs audit
        WHERE audit.plan_id = NEW.plan_id
          AND audit.account_id = NEW.account_id
          AND audit.project_id = NEW.project_id
          AND audit.actor_id = NEW.actor_id
          AND audit.action = NEW.action
          AND audit.idempotency_key = NEW.idempotency_key
          AND audit.payload_json = NEW.payload_json
    ) THEN
        RAISE EXCEPTION 'delivered plan command requires matching audit record'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: enforce_plan_command_status_lifecycle(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.enforce_plan_command_status_lifecycle() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'pending' THEN
            RAISE EXCEPTION 'plan command must be inserted as pending, got %', NEW.status
                USING ERRCODE = '23514';
        END IF;

        RETURN NEW;
    END IF;

    IF OLD.status = 'delivered' AND NEW.status <> 'delivered' THEN
        RAISE EXCEPTION 'delivered plan command is terminal'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.status <> 'pending' AND NEW.status = 'pending' THEN
        RAISE EXCEPTION 'plan command status cannot move back to pending'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: protect_agentos_run_events_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_agentos_run_events_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'agentos run events cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    RAISE EXCEPTION 'agentos run events cannot be updated'
        USING ERRCODE = '23514';
END;
$$;


--
-- Name: protect_artifacts_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_artifacts_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'artifacts cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    RAISE EXCEPTION 'artifacts cannot be updated'
        USING ERRCODE = '23514';
END;
$$;


--
-- Name: protect_audit_logs_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_audit_logs_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'audit logs cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    RAISE EXCEPTION 'audit logs cannot be updated'
        USING ERRCODE = '23514';
END;
$$;


--
-- Name: protect_plan_command_identity(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_plan_command_identity() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'plan commands cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.command_id IS DISTINCT FROM NEW.command_id
        OR OLD.plan_id IS DISTINCT FROM NEW.plan_id
        OR OLD.account_id IS DISTINCT FROM NEW.account_id
        OR OLD.project_id IS DISTINCT FROM NEW.project_id
        OR OLD.actor_id IS DISTINCT FROM NEW.actor_id
        OR OLD.action IS DISTINCT FROM NEW.action
        OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
        OR OLD.payload_json IS DISTINCT FROM NEW.payload_json
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'plan command identity cannot be updated'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.status = 'delivered'
        AND OLD.failure_reason IS DISTINCT FROM NEW.failure_reason THEN
        RAISE EXCEPTION 'delivered plan command failure reason is terminal'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.status = NEW.status
        AND NEW.status <> 'failed'
        AND OLD.failure_reason IS DISTINCT FROM NEW.failure_reason THEN
        RAISE EXCEPTION 'plan command failure reason can only change with a failed lifecycle'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: protect_plan_events_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_plan_events_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'plan events cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    RAISE EXCEPTION 'plan events cannot be updated'
        USING ERRCODE = '23514';
END;
$$;


--
-- Name: protect_plan_identity(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_plan_identity() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'plan identity cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.plan_id IS DISTINCT FROM NEW.plan_id
        OR OLD.thread_id IS DISTINCT FROM NEW.thread_id
        OR OLD.account_id IS DISTINCT FROM NEW.account_id
        OR OLD.project_id IS DISTINCT FROM NEW.project_id
        OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
        OR OLD.requested_at IS DISTINCT FROM NEW.requested_at
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'plan identity cannot be updated'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.spec_json->'plan_id' IS DISTINCT FROM NEW.spec_json->'plan_id'
        OR OLD.spec_json->'thread_id' IS DISTINCT FROM NEW.spec_json->'thread_id'
        OR OLD.spec_json->'account_id' IS DISTINCT FROM NEW.spec_json->'account_id'
        OR OLD.spec_json->'project_id' IS DISTINCT FROM NEW.spec_json->'project_id'
        OR OLD.spec_json->'idempotency_key' IS DISTINCT FROM NEW.spec_json->'idempotency_key'
        OR OLD.spec_json->'requested_at' IS DISTINCT FROM NEW.spec_json->'requested_at'
        OR OLD.spec_json->'inputs' IS DISTINCT FROM NEW.spec_json->'inputs'
        OR OLD.spec_json->'metadata' IS DISTINCT FROM NEW.spec_json->'metadata'
        OR OLD.spec_json->'policy' IS DISTINCT FROM NEW.spec_json->'policy' THEN
        RAISE EXCEPTION 'plan spec identity cannot be updated'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: protect_plan_metric_samples_append_only(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_plan_metric_samples_append_only() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'plan metric samples cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    RAISE EXCEPTION 'plan metric samples cannot be updated'
        USING ERRCODE = '23514';
END;
$$;


--
-- Name: protect_plan_node_identity(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_plan_node_identity() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'plan nodes cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.plan_id IS DISTINCT FROM NEW.plan_id
        OR OLD.node_id IS DISTINCT FROM NEW.node_id
        OR OLD.backend_kind IS DISTINCT FROM NEW.backend_kind
        OR OLD.backend_name IS DISTINCT FROM NEW.backend_name
        OR OLD.capability IS DISTINCT FROM NEW.capability
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'plan node identity cannot be updated'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: protect_run_backend_ownership(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.protect_run_backend_ownership() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION 'run backend ownership cannot be deleted'
            USING ERRCODE = '23514';
    END IF;

    IF OLD.run_id IS DISTINCT FROM NEW.run_id
        OR OLD.plan_id IS DISTINCT FROM NEW.plan_id
        OR OLD.node_id IS DISTINCT FROM NEW.node_id
        OR OLD.thread_id IS DISTINCT FROM NEW.thread_id
        OR OLD.account_id IS DISTINCT FROM NEW.account_id
        OR OLD.project_id IS DISTINCT FROM NEW.project_id
        OR OLD.backend_kind IS DISTINCT FROM NEW.backend_kind
        OR OLD.backend_name IS DISTINCT FROM NEW.backend_name
        OR OLD.idempotency_key IS DISTINCT FROM NEW.idempotency_key
        OR OLD.created_at IS DISTINCT FROM NEW.created_at THEN
        RAISE EXCEPTION 'run backend ownership identity cannot be updated'
            USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
END;
$$;


--
-- Name: agent_versions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agent_versions (
    version_id text NOT NULL,
    agent_id text NOT NULL,
    version_name character varying(255) DEFAULT ''::character varying NOT NULL,
    system_prompt text DEFAULT ''::text NOT NULL,
    model_ref character varying(255) DEFAULT ''::character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    tool_bindings jsonb DEFAULT '[]'::jsonb NOT NULL,
    change_description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: agentos_artifact_schemas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_artifact_schemas (
    schema_ref text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    schema_json jsonb NOT NULL,
    schema_decl_json jsonb NOT NULL,
    idempotency_key text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_artifact_schemas_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: agentos_capabilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_capabilities (
    backend_kind text NOT NULL,
    backend_name text NOT NULL,
    capability_name text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    capability_json jsonb NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_capabilities_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: agentos_conversation_deferred_projections; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_conversation_deferred_projections (
    thread_id text NOT NULL,
    sequence bigint NOT NULL,
    run_id text NOT NULL,
    event_type text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: agentos_conversation_event_outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_conversation_event_outbox (
    thread_id text NOT NULL,
    sequence bigint NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    last_error text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: agentos_conversation_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_conversation_events (
    thread_id text NOT NULL,
    sequence bigint NOT NULL,
    event_id text NOT NULL,
    run_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    source_event_id text DEFAULT ''::text NOT NULL,
    source_sequence bigint DEFAULT 0 NOT NULL,
    event_type text NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT agentos_conversation_events_sequence_check CHECK ((sequence > 0))
);


--
-- Name: agentos_conversation_runs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_conversation_runs (
    run_id text NOT NULL,
    thread_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    status text NOT NULL,
    outcome text DEFAULT ''::text NOT NULL,
    interrupt jsonb,
    error_code text DEFAULT ''::text NOT NULL,
    error_message text DEFAULT ''::text NOT NULL,
    idempotency_key text NOT NULL,
    resume_interrupt_id text DEFAULT ''::text NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    last_source_sequence bigint DEFAULT 0 NOT NULL,
    created_at timestamp with time zone NOT NULL,
    started_at timestamp with time zone,
    completed_at timestamp with time zone,
    last_activity_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_conversation_runs_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'interrupted'::text, 'cancelled'::text, 'error'::text])))
);


--
-- Name: agentos_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_messages (
    message_id text NOT NULL,
    thread_id text NOT NULL,
    run_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    role text NOT NULL,
    content text DEFAULT ''::text NOT NULL,
    status text NOT NULL,
    attachments jsonb DEFAULT '[]'::jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    completed_at timestamp with time zone,
    CONSTRAINT agentos_messages_role_check CHECK ((role = ANY (ARRAY['user'::text, 'assistant'::text, 'system'::text, 'tool'::text]))),
    CONSTRAINT agentos_messages_status_check CHECK ((status = ANY (ARRAY['streaming'::text, 'completed'::text, 'error'::text])))
);


--
-- Name: agentos_run_event_outbox; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_run_event_outbox (
    run_id text NOT NULL,
    sequence bigint NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    available_at timestamp with time zone DEFAULT now() NOT NULL,
    last_error text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_run_event_outbox_sequence_check CHECK ((sequence > 0))
);


--
-- Name: agentos_run_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_run_events (
    run_id text NOT NULL,
    sequence bigint NOT NULL,
    event_id text NOT NULL,
    event_type text NOT NULL,
    thread_id text DEFAULT ''::text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    source text DEFAULT ''::text NOT NULL,
    occurred_at timestamp with time zone NOT NULL,
    payload jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_run_events_event_type_check CHECK ((event_type <> ''::text)),
    CONSTRAINT agentos_run_events_sequence_check CHECK ((sequence > 0))
);


--
-- Name: agentos_threads; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_threads (
    thread_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    next_sequence bigint DEFAULT 0 NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT agentos_threads_next_sequence_check CHECK ((next_sequence >= 0))
);


--
-- Name: agentos_tool_idempotency; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agentos_tool_idempotency (
    key text NOT NULL,
    run_id text NOT NULL,
    tool_call_id text NOT NULL,
    tool_name text NOT NULL,
    output jsonb NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: agents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.agents (
    agent_id text DEFAULT (gen_random_uuid())::text NOT NULL,
    account_id text NOT NULL,
    name character varying(255) NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    system_prompt text DEFAULT ''::text NOT NULL,
    model_ref character varying(255) DEFAULT ''::character varying NOT NULL,
    config jsonb DEFAULT '{}'::jsonb NOT NULL,
    current_version text DEFAULT ''::text NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: artifacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.artifacts (
    artifact_id text NOT NULL,
    plan_id text DEFAULT ''::text NOT NULL,
    node_id text,
    run_id text,
    name text NOT NULL,
    kind text NOT NULL,
    media_type text DEFAULT ''::text NOT NULL,
    uri text DEFAULT ''::text NOT NULL,
    size_bytes bigint DEFAULT 0 NOT NULL,
    digest text DEFAULT ''::text NOT NULL,
    metadata_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    CONSTRAINT artifacts_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT artifacts_artifact_id_required CHECK ((artifact_id <> ''::text)),
    CONSTRAINT artifacts_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT artifacts_kind_required CHECK ((kind <> ''::text)),
    CONSTRAINT artifacts_name_required CHECK ((name <> ''::text)),
    CONSTRAINT artifacts_node_run_pair CHECK ((((node_id IS NULL) AND (run_id IS NULL)) OR ((node_id IS NOT NULL) AND (run_id IS NOT NULL)))),
    CONSTRAINT artifacts_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT artifacts_project_id_required CHECK ((project_id <> ''::text))
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    audit_id text NOT NULL,
    plan_id text DEFAULT ''::text NOT NULL,
    run_id text,
    node_id text,
    actor_id text DEFAULT ''::text NOT NULL,
    action text NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    prev_hash text DEFAULT ''::text NOT NULL,
    row_hash text DEFAULT ''::text NOT NULL,
    CONSTRAINT audit_logs_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT audit_logs_action_required CHECK ((action <> ''::text)),
    CONSTRAINT audit_logs_audit_id_required CHECK ((audit_id <> ''::text)),
    CONSTRAINT audit_logs_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT audit_logs_node_run_pair CHECK ((((node_id IS NULL) AND (run_id IS NULL)) OR ((node_id IS NOT NULL) AND (run_id IS NOT NULL)))),
    CONSTRAINT audit_logs_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT audit_logs_project_id_required CHECK ((project_id <> ''::text))
);


--
-- Name: credit_accounts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_accounts (
    account_id text NOT NULL,
    balance numeric(12,4) DEFAULT 0 NOT NULL,
    currency text DEFAULT 'USD'::text NOT NULL,
    version bigint DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: credit_ledger; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_ledger (
    id bigint NOT NULL,
    account_id text NOT NULL,
    amount numeric(12,4) NOT NULL,
    type text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: credit_ledger_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.credit_ledger_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: credit_ledger_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.credit_ledger_id_seq OWNED BY public.credit_ledger.id;


--
-- Name: governed_action_status_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.governed_action_status_updates (
    action_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    idempotency_key text NOT NULL,
    status_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT governed_action_status_updates_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: governed_actions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.governed_actions (
    action_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    resource_kind text DEFAULT ''::text NOT NULL,
    resource_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    lifecycle_state text NOT NULL,
    idempotency_key text NOT NULL,
    spec_json jsonb NOT NULL,
    status_json jsonb NOT NULL,
    requested_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT governed_actions_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT governed_actions_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT governed_actions_kind_required CHECK ((kind <> ''::text)),
    CONSTRAINT governed_actions_lifecycle_required CHECK ((lifecycle_state <> ''::text)),
    CONSTRAINT governed_actions_project_id_required CHECK ((project_id <> ''::text))
);


--
-- Name: ledger_entries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ledger_entries (
    entry_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    resource_kind text DEFAULT ''::text NOT NULL,
    resource_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    sequence bigint NOT NULL,
    idempotency_key text NOT NULL,
    entry_json jsonb NOT NULL,
    occurred_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ledger_entries_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT ledger_entries_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT ledger_entries_kind_required CHECK ((kind <> ''::text)),
    CONSTRAINT ledger_entries_project_id_required CHECK ((project_id <> ''::text))
);


--
-- Name: plan_commands; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_commands (
    command_id text NOT NULL,
    plan_id text NOT NULL,
    actor_id text DEFAULT ''::text NOT NULL,
    action text NOT NULL,
    idempotency_key text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    status text NOT NULL,
    failure_reason text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    CONSTRAINT plan_commands_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT plan_commands_action_required CHECK ((action <> ''::text)),
    CONSTRAINT plan_commands_command_id_required CHECK ((command_id <> ''::text)),
    CONSTRAINT plan_commands_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT plan_commands_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plan_commands_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT plan_commands_status_valid CHECK ((status = ANY (ARRAY['pending'::text, 'delivered'::text, 'failed'::text])))
);


--
-- Name: plan_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_events (
    event_id text NOT NULL,
    plan_id text NOT NULL,
    node_id text DEFAULT ''::text NOT NULL,
    run_id text DEFAULT ''::text NOT NULL,
    event_type text NOT NULL,
    sequence bigint NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_json jsonb NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    transition_snapshot_digest text DEFAULT ''::text NOT NULL,
    transition_snapshot_json jsonb,
    CONSTRAINT plan_events_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT plan_events_event_id_required CHECK ((event_id <> ''::text)),
    CONSTRAINT plan_events_event_json_identity_matches_columns CHECK (((event_json ? 'event_id'::text) AND (event_json ? 'event_type'::text) AND (event_json ? 'plan_id'::text) AND (event_json ? 'account_id'::text) AND (event_json ? 'project_id'::text) AND (event_json ? 'sequence'::text) AND (event_json ? 'timestamp'::text) AND ((event_json ->> 'event_id'::text) = event_id) AND ((event_json ->> 'event_type'::text) = event_type) AND ((event_json ->> 'plan_id'::text) = plan_id) AND ((event_json ->> 'account_id'::text) = account_id) AND ((event_json ->> 'project_id'::text) = project_id) AND (COALESCE((event_json ->> 'node_id'::text), ''::text) = node_id) AND (COALESCE((event_json ->> 'run_id'::text), ''::text) = run_id) AND (((event_json ->> 'sequence'::text))::bigint = sequence) AND (((event_json ->> 'timestamp'::text))::timestamp with time zone = "timestamp"))),
    CONSTRAINT plan_events_event_type_required CHECK ((event_type <> ''::text)),
    CONSTRAINT plan_events_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT plan_events_payload_json_matches_event CHECK ((COALESCE((event_json -> 'payload'::text), '{}'::jsonb) = payload_json)),
    CONSTRAINT plan_events_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plan_events_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT plan_events_sequence_positive CHECK ((sequence > 0)),
    CONSTRAINT plan_events_transition_snapshot_pair CHECK ((((transition_snapshot_digest = ''::text) AND (transition_snapshot_json IS NULL)) OR ((transition_snapshot_digest <> ''::text) AND (transition_snapshot_json IS NOT NULL))))
);


--
-- Name: plan_metric_checkpoints; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_metric_checkpoints (
    exporter_id text NOT NULL,
    plan_id text NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    sequence bigint DEFAULT 0 NOT NULL,
    projection_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plan_metric_checkpoints_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT plan_metric_checkpoints_exporter_required CHECK ((exporter_id <> ''::text)),
    CONSTRAINT plan_metric_checkpoints_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plan_metric_checkpoints_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT plan_metric_checkpoints_sequence_non_negative CHECK ((sequence >= 0))
);


--
-- Name: plan_metric_samples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_metric_samples (
    metric_name text NOT NULL,
    plan_id text NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    node_id text DEFAULT ''::text NOT NULL,
    run_id text DEFAULT ''::text NOT NULL,
    event_id text NOT NULL,
    sequence bigint NOT NULL,
    value double precision NOT NULL,
    unit text NOT NULL,
    labels_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    sample_timestamp timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plan_metric_samples_account_required CHECK ((account_id <> ''::text)),
    CONSTRAINT plan_metric_samples_event_required CHECK ((event_id <> ''::text)),
    CONSTRAINT plan_metric_samples_metric_required CHECK ((metric_name <> ''::text)),
    CONSTRAINT plan_metric_samples_plan_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plan_metric_samples_project_required CHECK ((project_id <> ''::text)),
    CONSTRAINT plan_metric_samples_sequence_positive CHECK ((sequence > 0)),
    CONSTRAINT plan_metric_samples_unit_required CHECK ((unit <> ''::text))
);


--
-- Name: plan_nodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_nodes (
    plan_id text NOT NULL,
    node_id text NOT NULL,
    run_id text DEFAULT ''::text NOT NULL,
    backend_kind text DEFAULT ''::text NOT NULL,
    backend_name text DEFAULT ''::text NOT NULL,
    capability text DEFAULT ''::text NOT NULL,
    lifecycle_state text NOT NULL,
    attempts integer DEFAULT 0 NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    status_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plan_nodes_attempts_non_negative CHECK ((attempts >= 0)),
    CONSTRAINT plan_nodes_lifecycle_state_required CHECK ((lifecycle_state <> ''::text)),
    CONSTRAINT plan_nodes_node_id_required CHECK ((node_id <> ''::text)),
    CONSTRAINT plan_nodes_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plan_nodes_status_json_matches_columns CHECK (((status_json ? 'node_id'::text) AND (status_json ? 'backend'::text) AND (status_json ? 'lifecycle_state'::text) AND ((status_json ->> 'node_id'::text) = node_id) AND (COALESCE((status_json ->> 'run_id'::text), ''::text) = run_id) AND (((status_json -> 'backend'::text) ->> 'kind'::text) = backend_kind) AND (((status_json -> 'backend'::text) ->> 'name'::text) = backend_name) AND ((status_json ->> 'lifecycle_state'::text) = lifecycle_state) AND (COALESCE(((status_json ->> 'attempts'::text))::integer, 0) = attempts) AND (COALESCE((status_json ->> 'reason'::text), ''::text) = reason)))
);


--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    plan_id text NOT NULL,
    thread_id text DEFAULT ''::text NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    lifecycle_state text NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    spec_json jsonb NOT NULL,
    status_json jsonb NOT NULL,
    event_sequence bigint DEFAULT 0 NOT NULL,
    requested_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT plans_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT plans_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT plans_lifecycle_state_required CHECK ((lifecycle_state <> ''::text)),
    CONSTRAINT plans_plan_id_required CHECK ((plan_id <> ''::text)),
    CONSTRAINT plans_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT plans_spec_json_identity_matches_columns CHECK (((spec_json ? 'plan_id'::text) AND (spec_json ? 'account_id'::text) AND (spec_json ? 'project_id'::text) AND (spec_json ? 'idempotency_key'::text) AND ((spec_json ->> 'plan_id'::text) = plan_id) AND (COALESCE((spec_json ->> 'thread_id'::text), ''::text) = thread_id) AND ((spec_json ->> 'account_id'::text) = account_id) AND ((spec_json ->> 'project_id'::text) = project_id) AND ((spec_json ->> 'idempotency_key'::text) = idempotency_key) AND (((requested_at IS NULL) AND ((NOT (spec_json ? 'requested_at'::text)) OR ((spec_json ->> 'requested_at'::text) = '0001-01-01T00:00:00Z'::text))) OR ((requested_at IS NOT NULL) AND (spec_json ? 'requested_at'::text) AND (((spec_json ->> 'requested_at'::text))::timestamp with time zone = requested_at))))),
    CONSTRAINT plans_status_json_matches_columns CHECK (((status_json ? 'plan_id'::text) AND (status_json ? 'lifecycle_state'::text) AND ((status_json ->> 'plan_id'::text) = plan_id) AND ((status_json ->> 'lifecycle_state'::text) = lifecycle_state) AND (COALESCE((status_json ->> 'reason'::text), ''::text) = reason)))
);


--
-- Name: process_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.process_events (
    event_id text NOT NULL,
    process_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    resource_kind text NOT NULL,
    resource_id text NOT NULL,
    event_type text NOT NULL,
    sequence bigint NOT NULL,
    idempotency_key text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    event_json jsonb NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT process_events_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT process_events_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT process_events_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT process_events_resource_identity_required CHECK (((resource_kind <> ''::text) AND (resource_id <> ''::text)))
);


--
-- Name: process_status_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.process_status_updates (
    process_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    idempotency_key text NOT NULL,
    status_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT process_status_updates_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: processes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.processes (
    process_id text NOT NULL,
    kind text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    resource_kind text NOT NULL,
    resource_id text NOT NULL,
    idempotency_key text NOT NULL,
    lifecycle_state text NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    spec_json jsonb NOT NULL,
    status_json jsonb NOT NULL,
    event_sequence bigint DEFAULT 0 NOT NULL,
    requested_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT processes_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT processes_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT processes_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT processes_resource_identity_required CHECK (((resource_kind <> ''::text) AND (resource_id <> ''::text)))
);


--
-- Name: run_backend_index; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.run_backend_index (
    run_id text NOT NULL,
    plan_id text,
    node_id text,
    thread_id text DEFAULT ''::text NOT NULL,
    account_id text DEFAULT ''::text NOT NULL,
    project_id text DEFAULT ''::text NOT NULL,
    backend_kind text NOT NULL,
    backend_name text NOT NULL,
    idempotency_key text DEFAULT ''::text NOT NULL,
    lifecycle_state text DEFAULT 'created'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT run_backend_index_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT run_backend_index_backend_kind_required CHECK ((backend_kind <> ''::text)),
    CONSTRAINT run_backend_index_backend_name_required CHECK ((backend_name <> ''::text)),
    CONSTRAINT run_backend_index_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT run_backend_index_lifecycle_state_required CHECK ((lifecycle_state <> ''::text)),
    CONSTRAINT run_backend_index_plan_node_pair CHECK ((((plan_id IS NULL) AND (node_id IS NULL)) OR ((plan_id IS NOT NULL) AND (node_id IS NOT NULL)))),
    CONSTRAINT run_backend_index_project_id_required CHECK ((project_id <> ''::text)),
    CONSTRAINT run_backend_index_run_id_required CHECK ((run_id <> ''::text))
);


--
-- Name: usage_records; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.usage_records (
    id bigint NOT NULL,
    record_id text NOT NULL,
    run_id text NOT NULL,
    account_id text NOT NULL,
    model_id text NOT NULL,
    prompt_tokens integer DEFAULT 0 NOT NULL,
    completion_tokens integer DEFAULT 0 NOT NULL,
    total_tokens integer DEFAULT 0 NOT NULL,
    cost numeric(12,8) DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: usage_records_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.usage_records_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: usage_records_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.usage_records_id_seq OWNED BY public.usage_records.id;


--
-- Name: workflow_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workflow_templates (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    account_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    team_spec jsonb DEFAULT '{}'::jsonb NOT NULL,
    system_prompt text DEFAULT ''::text NOT NULL,
    default_model character varying(255) DEFAULT ''::character varying NOT NULL,
    tags text[] DEFAULT '{}'::text[] NOT NULL,
    is_enabled boolean DEFAULT true NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: workset_chunk_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workset_chunk_results (
    workset_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    chunk_id text NOT NULL,
    idempotency_key text NOT NULL,
    result_json jsonb NOT NULL,
    status_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT workset_chunk_results_chunk_id_required CHECK ((chunk_id <> ''::text)),
    CONSTRAINT workset_chunk_results_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: workset_status_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workset_status_updates (
    workset_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    idempotency_key text NOT NULL,
    status_json jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT workset_status_updates_idempotency_key_required CHECK ((idempotency_key <> ''::text))
);


--
-- Name: worksets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.worksets (
    workset_id text NOT NULL,
    account_id text NOT NULL,
    project_id text NOT NULL,
    process_id text DEFAULT ''::text NOT NULL,
    resource_kind text DEFAULT ''::text NOT NULL,
    resource_id text DEFAULT ''::text NOT NULL,
    kind text NOT NULL,
    lifecycle_state text NOT NULL,
    idempotency_key text NOT NULL,
    spec_json jsonb NOT NULL,
    status_json jsonb NOT NULL,
    requested_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT worksets_account_id_required CHECK ((account_id <> ''::text)),
    CONSTRAINT worksets_idempotency_key_required CHECK ((idempotency_key <> ''::text)),
    CONSTRAINT worksets_kind_required CHECK ((kind <> ''::text)),
    CONSTRAINT worksets_lifecycle_required CHECK ((lifecycle_state <> ''::text)),
    CONSTRAINT worksets_project_id_required CHECK ((project_id <> ''::text))
);


--
-- Name: credit_ledger id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_ledger ALTER COLUMN id SET DEFAULT nextval('public.credit_ledger_id_seq'::regclass);


--
-- Name: usage_records id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_records ALTER COLUMN id SET DEFAULT nextval('public.usage_records_id_seq'::regclass);


--
-- Name: agent_versions agent_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_versions
    ADD CONSTRAINT agent_versions_pkey PRIMARY KEY (version_id);


--
-- Name: agentos_artifact_schemas agentos_artifact_schemas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_artifact_schemas
    ADD CONSTRAINT agentos_artifact_schemas_pkey PRIMARY KEY (schema_ref);


--
-- Name: agentos_capabilities agentos_capabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_capabilities
    ADD CONSTRAINT agentos_capabilities_pkey PRIMARY KEY (backend_kind, backend_name, capability_name);


--
-- Name: agentos_conversation_deferred_projections agentos_conversation_deferred_projections_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_deferred_projections
    ADD CONSTRAINT agentos_conversation_deferred_projections_pkey PRIMARY KEY (thread_id, sequence);


--
-- Name: agentos_conversation_event_outbox agentos_conversation_event_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_event_outbox
    ADD CONSTRAINT agentos_conversation_event_outbox_pkey PRIMARY KEY (thread_id, sequence);


--
-- Name: agentos_conversation_events agentos_conversation_events_event_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_events
    ADD CONSTRAINT agentos_conversation_events_event_id_key UNIQUE (event_id);


--
-- Name: agentos_conversation_events agentos_conversation_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_events
    ADD CONSTRAINT agentos_conversation_events_pkey PRIMARY KEY (thread_id, sequence);


--
-- Name: agentos_conversation_runs agentos_conversation_runs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_runs
    ADD CONSTRAINT agentos_conversation_runs_pkey PRIMARY KEY (run_id);


--
-- Name: agentos_conversation_runs agentos_conversation_runs_thread_id_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_runs
    ADD CONSTRAINT agentos_conversation_runs_thread_id_idempotency_key_key UNIQUE (thread_id, idempotency_key);


--
-- Name: agentos_messages agentos_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_messages
    ADD CONSTRAINT agentos_messages_pkey PRIMARY KEY (message_id);


--
-- Name: agentos_run_event_outbox agentos_run_event_outbox_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_run_event_outbox
    ADD CONSTRAINT agentos_run_event_outbox_pkey PRIMARY KEY (run_id, sequence);


--
-- Name: agentos_run_events agentos_run_events_event_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_run_events
    ADD CONSTRAINT agentos_run_events_event_id_key UNIQUE (event_id);


--
-- Name: agentos_run_events agentos_run_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_run_events
    ADD CONSTRAINT agentos_run_events_pkey PRIMARY KEY (run_id, sequence);


--
-- Name: agentos_threads agentos_threads_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_threads
    ADD CONSTRAINT agentos_threads_pkey PRIMARY KEY (thread_id);


--
-- Name: agentos_tool_idempotency agentos_tool_idempotency_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_tool_idempotency
    ADD CONSTRAINT agentos_tool_idempotency_pkey PRIMARY KEY (key);


--
-- Name: agents agents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (agent_id);


--
-- Name: artifacts artifacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (artifact_id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (audit_id);


--
-- Name: credit_accounts credit_accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_accounts
    ADD CONSTRAINT credit_accounts_pkey PRIMARY KEY (account_id);


--
-- Name: credit_ledger credit_ledger_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_ledger
    ADD CONSTRAINT credit_ledger_pkey PRIMARY KEY (id);


--
-- Name: governed_action_status_updates governed_action_status_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.governed_action_status_updates
    ADD CONSTRAINT governed_action_status_updates_pkey PRIMARY KEY (account_id, project_id, action_id, idempotency_key);


--
-- Name: governed_actions governed_actions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.governed_actions
    ADD CONSTRAINT governed_actions_pkey PRIMARY KEY (action_id);


--
-- Name: ledger_entries ledger_entries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ledger_entries
    ADD CONSTRAINT ledger_entries_pkey PRIMARY KEY (entry_id);


--
-- Name: plan_commands plan_commands_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_commands
    ADD CONSTRAINT plan_commands_pkey PRIMARY KEY (command_id);


--
-- Name: plan_events plan_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_events
    ADD CONSTRAINT plan_events_pkey PRIMARY KEY (event_id);


--
-- Name: plan_events plan_events_plan_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_events
    ADD CONSTRAINT plan_events_plan_id_sequence_key UNIQUE (plan_id, sequence);


--
-- Name: plan_metric_checkpoints plan_metric_checkpoints_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_checkpoints
    ADD CONSTRAINT plan_metric_checkpoints_pkey PRIMARY KEY (exporter_id, plan_id);


--
-- Name: plan_metric_samples plan_metric_samples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_samples
    ADD CONSTRAINT plan_metric_samples_pkey PRIMARY KEY (metric_name, plan_id, node_id, run_id, event_id, sequence);


--
-- Name: plan_nodes plan_nodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_nodes
    ADD CONSTRAINT plan_nodes_pkey PRIMARY KEY (plan_id, node_id);


--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (plan_id);


--
-- Name: plans plans_tenant_plan_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_tenant_plan_unique UNIQUE (account_id, project_id, plan_id);


--
-- Name: process_events process_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_events
    ADD CONSTRAINT process_events_pkey PRIMARY KEY (event_id);


--
-- Name: process_events process_events_process_id_sequence_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_events
    ADD CONSTRAINT process_events_process_id_sequence_key UNIQUE (process_id, sequence);


--
-- Name: process_status_updates process_status_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_status_updates
    ADD CONSTRAINT process_status_updates_pkey PRIMARY KEY (account_id, project_id, process_id, idempotency_key);


--
-- Name: processes processes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.processes
    ADD CONSTRAINT processes_pkey PRIMARY KEY (process_id);


--
-- Name: run_backend_index run_backend_index_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_backend_index
    ADD CONSTRAINT run_backend_index_pkey PRIMARY KEY (run_id);


--
-- Name: run_backend_index run_backend_index_plan_node_run_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_backend_index
    ADD CONSTRAINT run_backend_index_plan_node_run_unique UNIQUE (plan_id, node_id, run_id);


--
-- Name: usage_records usage_records_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_records
    ADD CONSTRAINT usage_records_pkey PRIMARY KEY (id);


--
-- Name: usage_records usage_records_record_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.usage_records
    ADD CONSTRAINT usage_records_record_id_key UNIQUE (record_id);


--
-- Name: workflow_templates workflow_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workflow_templates
    ADD CONSTRAINT workflow_templates_pkey PRIMARY KEY (id);


--
-- Name: workset_chunk_results workset_chunk_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_chunk_results
    ADD CONSTRAINT workset_chunk_results_pkey PRIMARY KEY (account_id, project_id, workset_id, chunk_id, idempotency_key);


--
-- Name: workset_status_updates workset_status_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_status_updates
    ADD CONSTRAINT workset_status_updates_pkey PRIMARY KEY (account_id, project_id, workset_id, idempotency_key);


--
-- Name: worksets worksets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.worksets
    ADD CONSTRAINT worksets_pkey PRIMARY KEY (workset_id);


--
-- Name: idx_agent_versions_agent_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agent_versions_agent_id ON public.agent_versions USING btree (agent_id);


--
-- Name: idx_agentos_artifact_schemas_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_agentos_artifact_schemas_idempotency_key ON public.agentos_artifact_schemas USING btree (idempotency_key);


--
-- Name: idx_agentos_capabilities_backend; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_capabilities_backend ON public.agentos_capabilities USING btree (backend_kind, backend_name);


--
-- Name: idx_agentos_capabilities_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_agentos_capabilities_idempotency_key ON public.agentos_capabilities USING btree (idempotency_key);


--
-- Name: idx_agentos_conversation_deferred_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_conversation_deferred_run ON public.agentos_conversation_deferred_projections USING btree (run_id);


--
-- Name: idx_agentos_conversation_event_outbox_ready; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_conversation_event_outbox_ready ON public.agentos_conversation_event_outbox USING btree (available_at, created_at);


--
-- Name: idx_agentos_conversation_events_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_conversation_events_run ON public.agentos_conversation_events USING btree (run_id, sequence);


--
-- Name: idx_agentos_conversation_events_source; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_agentos_conversation_events_source ON public.agentos_conversation_events USING btree (thread_id, source_event_id) WHERE (source_event_id <> ''::text);


--
-- Name: idx_agentos_conversation_runs_lease; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_conversation_runs_lease ON public.agentos_conversation_runs USING btree (last_activity_at) WHERE (status = 'running'::text);


--
-- Name: idx_agentos_conversation_runs_running; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_agentos_conversation_runs_running ON public.agentos_conversation_runs USING btree (thread_id) WHERE (status = 'running'::text);


--
-- Name: idx_agentos_conversation_runs_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_conversation_runs_thread ON public.agentos_conversation_runs USING btree (thread_id, created_at, run_id);


--
-- Name: idx_agentos_messages_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_messages_run ON public.agentos_messages USING btree (run_id, created_at, message_id);


--
-- Name: idx_agentos_messages_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_messages_thread ON public.agentos_messages USING btree (thread_id, created_at, message_id);


--
-- Name: idx_agentos_run_event_outbox_ready; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_run_event_outbox_ready ON public.agentos_run_event_outbox USING btree (available_at, created_at);


--
-- Name: idx_agentos_run_events_thread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_run_events_thread ON public.agentos_run_events USING btree (thread_id, sequence);


--
-- Name: idx_agentos_threads_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_threads_tenant ON public.agentos_threads USING btree (account_id, project_id, updated_at DESC);


--
-- Name: idx_agentos_tool_idempotency_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agentos_tool_idempotency_created_at ON public.agentos_tool_idempotency USING btree (created_at);


--
-- Name: idx_agents_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_agents_account_id ON public.agents USING btree (account_id);


--
-- Name: idx_artifacts_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_artifacts_idempotency_key ON public.artifacts USING btree (account_id, project_id, plan_id, idempotency_key);


--
-- Name: idx_artifacts_plan_node; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifacts_plan_node ON public.artifacts USING btree (plan_id, node_id);


--
-- Name: idx_artifacts_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifacts_run_id ON public.artifacts USING btree (run_id);


--
-- Name: idx_artifacts_tenant_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_artifacts_tenant_scope ON public.artifacts USING btree (account_id, project_id, plan_id, node_id, run_id, created_at);


--
-- Name: idx_audit_logs_chain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_chain ON public.audit_logs USING btree (account_id, project_id, created_at, audit_id);


--
-- Name: idx_audit_logs_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_audit_logs_idempotency_key ON public.audit_logs USING btree (account_id, project_id, plan_id, idempotency_key);


--
-- Name: idx_audit_logs_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_plan ON public.audit_logs USING btree (plan_id, created_at);


--
-- Name: idx_audit_logs_tenant_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_tenant_scope ON public.audit_logs USING btree (account_id, project_id, plan_id, created_at);


--
-- Name: idx_credit_ledger_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credit_ledger_account ON public.credit_ledger USING btree (account_id);


--
-- Name: idx_credit_ledger_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_credit_ledger_created ON public.credit_ledger USING btree (created_at DESC);


--
-- Name: idx_governed_actions_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_governed_actions_idempotency_key ON public.governed_actions USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_governed_actions_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_governed_actions_kind ON public.governed_actions USING btree (account_id, project_id, kind);


--
-- Name: idx_governed_actions_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_governed_actions_lifecycle ON public.governed_actions USING btree (account_id, project_id, lifecycle_state);


--
-- Name: idx_governed_actions_process; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_governed_actions_process ON public.governed_actions USING btree (account_id, project_id, process_id);


--
-- Name: idx_governed_actions_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_governed_actions_resource ON public.governed_actions USING btree (account_id, project_id, resource_kind, resource_id);


--
-- Name: idx_governed_actions_tenant_action; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_governed_actions_tenant_action ON public.governed_actions USING btree (account_id, project_id, action_id);


--
-- Name: idx_ledger_entries_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_ledger_entries_idempotency_key ON public.ledger_entries USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_ledger_entries_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ledger_entries_kind ON public.ledger_entries USING btree (account_id, project_id, kind, sequence);


--
-- Name: idx_ledger_entries_process; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ledger_entries_process ON public.ledger_entries USING btree (account_id, project_id, process_id, sequence);


--
-- Name: idx_ledger_entries_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ledger_entries_resource ON public.ledger_entries USING btree (account_id, project_id, resource_kind, resource_id, sequence);


--
-- Name: idx_ledger_entries_sequence; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_ledger_entries_sequence ON public.ledger_entries USING btree (account_id, project_id, sequence);


--
-- Name: idx_plan_commands_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_plan_commands_idempotency_key ON public.plan_commands USING btree (account_id, project_id, plan_id, idempotency_key);


--
-- Name: idx_plan_commands_plan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_commands_plan ON public.plan_commands USING btree (plan_id, created_at);


--
-- Name: idx_plan_commands_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_commands_status ON public.plan_commands USING btree (status, updated_at);


--
-- Name: idx_plan_commands_tenant_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_commands_tenant_status ON public.plan_commands USING btree (account_id, project_id, status, updated_at);


--
-- Name: idx_plan_events_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_plan_events_idempotency_key ON public.plan_events USING btree (account_id, project_id, plan_id, idempotency_key);


--
-- Name: idx_plan_events_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_events_scope ON public.plan_events USING btree (plan_id, node_id, run_id, sequence);


--
-- Name: idx_plan_events_tenant_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_events_tenant_scope ON public.plan_events USING btree (account_id, project_id, plan_id, sequence);


--
-- Name: idx_plan_events_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_events_type ON public.plan_events USING btree (event_type);


--
-- Name: idx_plan_metric_checkpoints_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_metric_checkpoints_tenant ON public.plan_metric_checkpoints USING btree (account_id, project_id, updated_at);


--
-- Name: idx_plan_metric_samples_name_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_metric_samples_name_time ON public.plan_metric_samples USING btree (metric_name, sample_timestamp);


--
-- Name: idx_plan_metric_samples_tenant_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_metric_samples_tenant_time ON public.plan_metric_samples USING btree (account_id, project_id, sample_timestamp);


--
-- Name: idx_plan_nodes_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_nodes_lifecycle ON public.plan_nodes USING btree (lifecycle_state);


--
-- Name: idx_plan_nodes_run_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plan_nodes_run_id ON public.plan_nodes USING btree (run_id);


--
-- Name: idx_plans_account_project; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_account_project ON public.plans USING btree (account_id, project_id);


--
-- Name: idx_plans_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_plans_idempotency_key ON public.plans USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_plans_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_lifecycle ON public.plans USING btree (lifecycle_state);


--
-- Name: idx_plans_thread_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_plans_thread_id ON public.plans USING btree (thread_id);


--
-- Name: idx_process_events_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_process_events_idempotency_key ON public.process_events USING btree (account_id, project_id, process_id, idempotency_key);


--
-- Name: idx_process_events_scope; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_process_events_scope ON public.process_events USING btree (account_id, project_id, process_id, sequence);


--
-- Name: idx_process_events_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_process_events_type ON public.process_events USING btree (event_type);


--
-- Name: idx_processes_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_processes_idempotency_key ON public.processes USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_processes_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_processes_lifecycle ON public.processes USING btree (lifecycle_state);


--
-- Name: idx_processes_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_processes_resource ON public.processes USING btree (account_id, project_id, resource_kind, resource_id);


--
-- Name: idx_processes_tenant_process; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_processes_tenant_process ON public.processes USING btree (account_id, project_id, process_id);


--
-- Name: idx_run_backend_index_backend; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_backend_index_backend ON public.run_backend_index USING btree (backend_kind, backend_name);


--
-- Name: idx_run_backend_index_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_run_backend_index_idempotency_key ON public.run_backend_index USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_run_backend_index_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_backend_index_lifecycle ON public.run_backend_index USING btree (lifecycle_state);


--
-- Name: idx_run_backend_index_plan_node; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_run_backend_index_plan_node ON public.run_backend_index USING btree (plan_id, node_id);


--
-- Name: idx_usage_records_account; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usage_records_account ON public.usage_records USING btree (account_id);


--
-- Name: idx_usage_records_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usage_records_created ON public.usage_records USING btree (created_at DESC);


--
-- Name: idx_usage_records_run; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_usage_records_run ON public.usage_records USING btree (run_id);


--
-- Name: idx_workflow_templates_account_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workflow_templates_account_id ON public.workflow_templates USING btree (account_id);


--
-- Name: idx_workflow_templates_tags; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_workflow_templates_tags ON public.workflow_templates USING gin (tags);


--
-- Name: idx_worksets_idempotency_key; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_worksets_idempotency_key ON public.worksets USING btree (account_id, project_id, idempotency_key);


--
-- Name: idx_worksets_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worksets_kind ON public.worksets USING btree (account_id, project_id, kind);


--
-- Name: idx_worksets_lifecycle; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worksets_lifecycle ON public.worksets USING btree (account_id, project_id, lifecycle_state);


--
-- Name: idx_worksets_process; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worksets_process ON public.worksets USING btree (account_id, project_id, process_id);


--
-- Name: idx_worksets_resource; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_worksets_resource ON public.worksets USING btree (account_id, project_id, resource_kind, resource_id);


--
-- Name: idx_worksets_tenant_workset; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_worksets_tenant_workset ON public.worksets USING btree (account_id, project_id, workset_id);


--
-- Name: agentos_run_events agentos_run_events_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER agentos_run_events_append_only BEFORE DELETE OR UPDATE ON public.agentos_run_events FOR EACH ROW EXECUTE FUNCTION public.protect_agentos_run_events_append_only();


--
-- Name: artifacts artifacts_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER artifacts_append_only BEFORE DELETE OR UPDATE ON public.artifacts FOR EACH ROW EXECUTE FUNCTION public.protect_artifacts_append_only();


--
-- Name: audit_logs audit_logs_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER audit_logs_append_only BEFORE DELETE OR UPDATE ON public.audit_logs FOR EACH ROW EXECUTE FUNCTION public.protect_audit_logs_append_only();


--
-- Name: plan_commands plan_commands_delivered_audit; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_commands_delivered_audit BEFORE INSERT OR UPDATE OF status, plan_id, account_id, project_id, actor_id, action, idempotency_key, payload_json ON public.plan_commands FOR EACH ROW EXECUTE FUNCTION public.enforce_delivered_plan_command_audit();


--
-- Name: plan_commands plan_commands_identity_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_commands_identity_immutable BEFORE DELETE OR UPDATE ON public.plan_commands FOR EACH ROW EXECUTE FUNCTION public.protect_plan_command_identity();


--
-- Name: plan_commands plan_commands_status_lifecycle; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_commands_status_lifecycle BEFORE INSERT OR UPDATE OF status ON public.plan_commands FOR EACH ROW EXECUTE FUNCTION public.enforce_plan_command_status_lifecycle();


--
-- Name: plan_events plan_events_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_events_append_only BEFORE DELETE OR UPDATE ON public.plan_events FOR EACH ROW EXECUTE FUNCTION public.protect_plan_events_append_only();


--
-- Name: plans plan_identity_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_identity_immutable BEFORE DELETE OR UPDATE ON public.plans FOR EACH ROW EXECUTE FUNCTION public.protect_plan_identity();


--
-- Name: plan_metric_samples plan_metric_samples_append_only; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_metric_samples_append_only BEFORE DELETE OR UPDATE ON public.plan_metric_samples FOR EACH ROW EXECUTE FUNCTION public.protect_plan_metric_samples_append_only();


--
-- Name: plan_nodes plan_node_identity_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER plan_node_identity_immutable BEFORE DELETE OR UPDATE ON public.plan_nodes FOR EACH ROW EXECUTE FUNCTION public.protect_plan_node_identity();


--
-- Name: run_backend_index run_backend_ownership_immutable; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER run_backend_ownership_immutable BEFORE DELETE OR UPDATE ON public.run_backend_index FOR EACH ROW EXECUTE FUNCTION public.protect_run_backend_ownership();


--
-- Name: agent_versions agent_versions_agent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agent_versions
    ADD CONSTRAINT agent_versions_agent_id_fkey FOREIGN KEY (agent_id) REFERENCES public.agents(agent_id) ON DELETE CASCADE;


--
-- Name: agentos_conversation_deferred_projections agentos_conversation_deferred_projectio_thread_id_sequence_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_deferred_projections
    ADD CONSTRAINT agentos_conversation_deferred_projectio_thread_id_sequence_fkey FOREIGN KEY (thread_id, sequence) REFERENCES public.agentos_conversation_events(thread_id, sequence) ON DELETE CASCADE;


--
-- Name: agentos_conversation_deferred_projections agentos_conversation_deferred_projections_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_deferred_projections
    ADD CONSTRAINT agentos_conversation_deferred_projections_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agentos_conversation_runs(run_id) ON DELETE CASCADE;


--
-- Name: agentos_conversation_deferred_projections agentos_conversation_deferred_projections_thread_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_deferred_projections
    ADD CONSTRAINT agentos_conversation_deferred_projections_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.agentos_threads(thread_id) ON DELETE CASCADE;


--
-- Name: agentos_conversation_event_outbox agentos_conversation_event_outbox_thread_id_sequence_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_event_outbox
    ADD CONSTRAINT agentos_conversation_event_outbox_thread_id_sequence_fkey FOREIGN KEY (thread_id, sequence) REFERENCES public.agentos_conversation_events(thread_id, sequence) ON DELETE CASCADE;


--
-- Name: agentos_conversation_events agentos_conversation_events_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_events
    ADD CONSTRAINT agentos_conversation_events_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agentos_conversation_runs(run_id) ON DELETE CASCADE;


--
-- Name: agentos_conversation_events agentos_conversation_events_thread_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_events
    ADD CONSTRAINT agentos_conversation_events_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.agentos_threads(thread_id) ON DELETE CASCADE;


--
-- Name: agentos_conversation_runs agentos_conversation_runs_thread_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_conversation_runs
    ADD CONSTRAINT agentos_conversation_runs_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.agentos_threads(thread_id) ON DELETE CASCADE;


--
-- Name: agentos_messages agentos_messages_run_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_messages
    ADD CONSTRAINT agentos_messages_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.agentos_conversation_runs(run_id) ON DELETE CASCADE;


--
-- Name: agentos_messages agentos_messages_thread_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_messages
    ADD CONSTRAINT agentos_messages_thread_id_fkey FOREIGN KEY (thread_id) REFERENCES public.agentos_threads(thread_id) ON DELETE CASCADE;


--
-- Name: agentos_run_event_outbox agentos_run_event_outbox_run_id_sequence_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.agentos_run_event_outbox
    ADD CONSTRAINT agentos_run_event_outbox_run_id_sequence_fkey FOREIGN KEY (run_id, sequence) REFERENCES public.agentos_run_events(run_id, sequence) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_plan_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_plan_fk FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_plan_node_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_plan_node_fk FOREIGN KEY (plan_id, node_id) REFERENCES public.plan_nodes(plan_id, node_id) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_plan_node_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_plan_node_run_fk FOREIGN KEY (plan_id, node_id, run_id) REFERENCES public.run_backend_index(plan_id, node_id, run_id) ON DELETE CASCADE;


--
-- Name: artifacts artifacts_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: audit_logs audit_logs_plan_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_plan_fk FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: audit_logs audit_logs_plan_node_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_plan_node_fk FOREIGN KEY (plan_id, node_id) REFERENCES public.plan_nodes(plan_id, node_id) ON DELETE CASCADE;


--
-- Name: audit_logs audit_logs_plan_node_run_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_plan_node_run_fk FOREIGN KEY (plan_id, node_id, run_id) REFERENCES public.run_backend_index(plan_id, node_id, run_id) ON DELETE CASCADE;


--
-- Name: audit_logs audit_logs_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: credit_ledger credit_ledger_account_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_ledger
    ADD CONSTRAINT credit_ledger_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.credit_accounts(account_id);


--
-- Name: governed_action_status_updates governed_action_status_updates_action_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.governed_action_status_updates
    ADD CONSTRAINT governed_action_status_updates_action_id_fkey FOREIGN KEY (action_id) REFERENCES public.governed_actions(action_id) ON DELETE RESTRICT;


--
-- Name: governed_action_status_updates governed_action_status_updates_action_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.governed_action_status_updates
    ADD CONSTRAINT governed_action_status_updates_action_tenant_fk FOREIGN KEY (account_id, project_id, action_id) REFERENCES public.governed_actions(account_id, project_id, action_id) ON DELETE RESTRICT;


--
-- Name: plan_commands plan_commands_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_commands
    ADD CONSTRAINT plan_commands_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: plan_commands plan_commands_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_commands
    ADD CONSTRAINT plan_commands_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: plan_events plan_events_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_events
    ADD CONSTRAINT plan_events_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: plan_events plan_events_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_events
    ADD CONSTRAINT plan_events_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: plan_metric_checkpoints plan_metric_checkpoints_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_checkpoints
    ADD CONSTRAINT plan_metric_checkpoints_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: plan_metric_checkpoints plan_metric_checkpoints_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_checkpoints
    ADD CONSTRAINT plan_metric_checkpoints_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: plan_metric_samples plan_metric_samples_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_samples
    ADD CONSTRAINT plan_metric_samples_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: plan_metric_samples plan_metric_samples_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_metric_samples
    ADD CONSTRAINT plan_metric_samples_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: plan_nodes plan_nodes_plan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_nodes
    ADD CONSTRAINT plan_nodes_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(plan_id) ON DELETE CASCADE;


--
-- Name: process_events process_events_process_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_events
    ADD CONSTRAINT process_events_process_id_fkey FOREIGN KEY (process_id) REFERENCES public.processes(process_id) ON DELETE RESTRICT;


--
-- Name: process_events process_events_process_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_events
    ADD CONSTRAINT process_events_process_tenant_fk FOREIGN KEY (account_id, project_id, process_id) REFERENCES public.processes(account_id, project_id, process_id) ON DELETE RESTRICT;


--
-- Name: process_status_updates process_status_updates_process_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_status_updates
    ADD CONSTRAINT process_status_updates_process_id_fkey FOREIGN KEY (process_id) REFERENCES public.processes(process_id) ON DELETE RESTRICT;


--
-- Name: process_status_updates process_status_updates_process_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.process_status_updates
    ADD CONSTRAINT process_status_updates_process_tenant_fk FOREIGN KEY (account_id, project_id, process_id) REFERENCES public.processes(account_id, project_id, process_id) ON DELETE RESTRICT;


--
-- Name: run_backend_index run_backend_index_plan_node_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_backend_index
    ADD CONSTRAINT run_backend_index_plan_node_fk FOREIGN KEY (plan_id, node_id) REFERENCES public.plan_nodes(plan_id, node_id) ON DELETE CASCADE;


--
-- Name: run_backend_index run_backend_index_plan_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.run_backend_index
    ADD CONSTRAINT run_backend_index_plan_tenant_fk FOREIGN KEY (account_id, project_id, plan_id) REFERENCES public.plans(account_id, project_id, plan_id) ON DELETE CASCADE;


--
-- Name: workset_chunk_results workset_chunk_results_workset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_chunk_results
    ADD CONSTRAINT workset_chunk_results_workset_id_fkey FOREIGN KEY (workset_id) REFERENCES public.worksets(workset_id) ON DELETE RESTRICT;


--
-- Name: workset_chunk_results workset_chunk_results_workset_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_chunk_results
    ADD CONSTRAINT workset_chunk_results_workset_tenant_fk FOREIGN KEY (account_id, project_id, workset_id) REFERENCES public.worksets(account_id, project_id, workset_id) ON DELETE RESTRICT;


--
-- Name: workset_status_updates workset_status_updates_workset_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_status_updates
    ADD CONSTRAINT workset_status_updates_workset_id_fkey FOREIGN KEY (workset_id) REFERENCES public.worksets(workset_id) ON DELETE RESTRICT;


--
-- Name: workset_status_updates workset_status_updates_workset_tenant_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workset_status_updates
    ADD CONSTRAINT workset_status_updates_workset_tenant_fk FOREIGN KEY (account_id, project_id, workset_id) REFERENCES public.worksets(account_id, project_id, workset_id) ON DELETE RESTRICT;


--
