// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/usecase/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/usecase/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/TekkenSteve/GoAgent/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStreamEventWriter is a mock of StreamEventWriter interface.
type MockStreamEventWriter struct {
	ctrl     *gomock.Controller
	recorder *MockStreamEventWriterMockRecorder
	isgomock struct{}
}

// MockStreamEventWriterMockRecorder is the mock recorder for MockStreamEventWriter.
type MockStreamEventWriterMockRecorder struct {
	mock *MockStreamEventWriter
}

// NewMockStreamEventWriter creates a new mock instance.
func NewMockStreamEventWriter(ctrl *gomock.Controller) *MockStreamEventWriter {
	mock := &MockStreamEventWriter{ctrl: ctrl}
	mock.recorder = &MockStreamEventWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStreamEventWriter) EXPECT() *MockStreamEventWriterMockRecorder {
	return m.recorder
}

// WriteEvent mocks base method.
func (m *MockStreamEventWriter) WriteEvent(ctx context.Context, event entity.StreamEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteEvent indicates an expected call of WriteEvent.
func (mr *MockStreamEventWriterMockRecorder) WriteEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteEvent", reflect.TypeOf((*MockStreamEventWriter)(nil).WriteEvent), ctx, event)
}

// MockToolDefProvider is a mock of ToolDefProvider interface.
type MockToolDefProvider struct {
	ctrl     *gomock.Controller
	recorder *MockToolDefProviderMockRecorder
	isgomock struct{}
}

// MockToolDefProviderMockRecorder is the mock recorder for MockToolDefProvider.
type MockToolDefProviderMockRecorder struct {
	mock *MockToolDefProvider
}

// NewMockToolDefProvider creates a new mock instance.
func NewMockToolDefProvider(ctrl *gomock.Controller) *MockToolDefProvider {
	mock := &MockToolDefProvider{ctrl: ctrl}
	mock.recorder = &MockToolDefProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolDefProvider) EXPECT() *MockToolDefProviderMockRecorder {
	return m.recorder
}

// Definitions mocks base method.
func (m *MockToolDefProvider) Definitions() []entity.ToolDef {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Definitions")
	ret0, _ := ret[0].([]entity.ToolDef)
	return ret0
}

// Definitions indicates an expected call of Definitions.
func (mr *MockToolDefProviderMockRecorder) Definitions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Definitions", reflect.TypeOf((*MockToolDefProvider)(nil).Definitions))
}

// MockTemplateManager is a mock of TemplateManager interface.
type MockTemplateManager struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateManagerMockRecorder
	isgomock struct{}
}

// MockTemplateManagerMockRecorder is the mock recorder for MockTemplateManager.
type MockTemplateManagerMockRecorder struct {
	mock *MockTemplateManager
}

// NewMockTemplateManager creates a new mock instance.
func NewMockTemplateManager(ctrl *gomock.Controller) *MockTemplateManager {
	mock := &MockTemplateManager{ctrl: ctrl}
	mock.recorder = &MockTemplateManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateManager) EXPECT() *MockTemplateManagerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTemplateManager) Create(ctx context.Context, req *entity.CreateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTemplateManagerMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTemplateManager)(nil).Create), ctx, req)
}

// CreateFromYAML mocks base method.
func (m *MockTemplateManager) CreateFromYAML(ctx context.Context, accountID string, yamlData []byte) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFromYAML", ctx, accountID, yamlData)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateFromYAML indicates an expected call of CreateFromYAML.
func (mr *MockTemplateManagerMockRecorder) CreateFromYAML(ctx, accountID, yamlData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFromYAML", reflect.TypeOf((*MockTemplateManager)(nil).CreateFromYAML), ctx, accountID, yamlData)
}

// Delete mocks base method.
func (m *MockTemplateManager) Delete(ctx context.Context, accountID, templateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, accountID, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTemplateManagerMockRecorder) Delete(ctx, accountID, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTemplateManager)(nil).Delete), ctx, accountID, templateID)
}

// Get mocks base method.
func (m *MockTemplateManager) Get(ctx context.Context, accountID, templateID string) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, accountID, templateID)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTemplateManagerMockRecorder) Get(ctx, accountID, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTemplateManager)(nil).Get), ctx, accountID, templateID)
}

// ListByAccount mocks base method.
func (m *MockTemplateManager) ListByAccount(ctx context.Context, accountID string) ([]entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockTemplateManagerMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockTemplateManager)(nil).ListByAccount), ctx, accountID)
}

// Update mocks base method.
func (m *MockTemplateManager) Update(ctx context.Context, accountID, templateID string, req entity.UpdateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, accountID, templateID, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTemplateManagerMockRecorder) Update(ctx, accountID, templateID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTemplateManager)(nil).Update), ctx, accountID, templateID, req)
}
