// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./internal/repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/TekkenSteve/GoAgent/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentRepo is a mock of AgentRepo interface.
type MockAgentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRepoMockRecorder
	isgomock struct{}
}

// MockAgentRepoMockRecorder is the mock recorder for MockAgentRepo.
type MockAgentRepoMockRecorder struct {
	mock *MockAgentRepo
}

// NewMockAgentRepo creates a new mock instance.
func NewMockAgentRepo(ctrl *gomock.Controller) *MockAgentRepo {
	mock := &MockAgentRepo{ctrl: ctrl}
	mock.recorder = &MockAgentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRepo) EXPECT() *MockAgentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentRepo) Create(ctx context.Context, req *entity.CreateAgentRequest) (entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentRepoMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentRepo)(nil).Create), ctx, req)
}

// CreateVersion mocks base method.
func (m *MockAgentRepo) CreateVersion(ctx context.Context, record *entity.AgentVersionRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockAgentRepoMockRecorder) CreateVersion(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockAgentRepo)(nil).CreateVersion), ctx, record)
}

// Delete mocks base method.
func (m *MockAgentRepo) Delete(ctx context.Context, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentRepoMockRecorder) Delete(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentRepo)(nil).Delete), ctx, agentID)
}

// Get mocks base method.
func (m *MockAgentRepo) Get(ctx context.Context, agentID string) (entity.AgentRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, agentID)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAgentRepoMockRecorder) Get(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentRepo)(nil).Get), ctx, agentID)
}

// GetVersion mocks base method.
func (m *MockAgentRepo) GetVersion(ctx context.Context, versionID string) (entity.AgentVersionRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, versionID)
	ret0, _ := ret[0].(entity.AgentVersionRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockAgentRepoMockRecorder) GetVersion(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockAgentRepo)(nil).GetVersion), ctx, versionID)
}

// ListByAccount mocks base method.
func (m *MockAgentRepo) ListByAccount(ctx context.Context, accountID string) ([]entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockAgentRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockAgentRepo)(nil).ListByAccount), ctx, accountID)
}

// ListVersions mocks base method.
func (m *MockAgentRepo) ListVersions(ctx context.Context, agentID string) ([]entity.AgentVersionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, agentID)
	ret0, _ := ret[0].([]entity.AgentVersionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockAgentRepoMockRecorder) ListVersions(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockAgentRepo)(nil).ListVersions), ctx, agentID)
}

// Update mocks base method.
func (m *MockAgentRepo) Update(ctx context.Context, agentID string, req entity.UpdateAgentRequest) (entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, agentID, req)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAgentRepoMockRecorder) Update(ctx, agentID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentRepo)(nil).Update), ctx, agentID, req)
}

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockLLMProvider) Chat(ctx context.Context, req *entity.LLMRequest) (entity.LLMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(entity.LLMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockLLMProviderMockRecorder) Chat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLLMProvider)(nil).Chat), ctx, req)
}

// MockLLMStreamProvider is a mock of LLMStreamProvider interface.
type MockLLMStreamProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMStreamProviderMockRecorder
	isgomock struct{}
}

// MockLLMStreamProviderMockRecorder is the mock recorder for MockLLMStreamProvider.
type MockLLMStreamProviderMockRecorder struct {
	mock *MockLLMStreamProvider
}

// NewMockLLMStreamProvider creates a new mock instance.
func NewMockLLMStreamProvider(ctrl *gomock.Controller) *MockLLMStreamProvider {
	mock := &MockLLMStreamProvider{ctrl: ctrl}
	mock.recorder = &MockLLMStreamProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMStreamProvider) EXPECT() *MockLLMStreamProviderMockRecorder {
	return m.recorder
}

// ChatStream mocks base method.
func (m *MockLLMStreamProvider) ChatStream(ctx context.Context, req *entity.LLMRequest) (<-chan entity.LLMStreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, req)
	ret0, _ := ret[0].(<-chan entity.LLMStreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockLLMStreamProviderMockRecorder) ChatStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockLLMStreamProvider)(nil).ChatStream), ctx, req)
}

// MockToolExecutor is a mock of ToolExecutor interface.
type MockToolExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockToolExecutorMockRecorder
	isgomock struct{}
}

// MockToolExecutorMockRecorder is the mock recorder for MockToolExecutor.
type MockToolExecutorMockRecorder struct {
	mock *MockToolExecutor
}

// NewMockToolExecutor creates a new mock instance.
func NewMockToolExecutor(ctrl *gomock.Controller) *MockToolExecutor {
	mock := &MockToolExecutor{ctrl: ctrl}
	mock.recorder = &MockToolExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolExecutor) EXPECT() *MockToolExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockToolExecutor) Execute(ctx context.Context, req *entity.ToolRequest) (entity.ToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(entity.ToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolExecutorMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockToolExecutor)(nil).Execute), ctx, req)
}

// MockContextCompressor is a mock of ContextCompressor interface.
type MockContextCompressor struct {
	ctrl     *gomock.Controller
	recorder *MockContextCompressorMockRecorder
	isgomock struct{}
}

// MockContextCompressorMockRecorder is the mock recorder for MockContextCompressor.
type MockContextCompressorMockRecorder struct {
	mock *MockContextCompressor
}

// NewMockContextCompressor creates a new mock instance.
func NewMockContextCompressor(ctrl *gomock.Controller) *MockContextCompressor {
	mock := &MockContextCompressor{ctrl: ctrl}
	mock.recorder = &MockContextCompressorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextCompressor) EXPECT() *MockContextCompressorMockRecorder {
	return m.recorder
}

// Compress mocks base method.
func (m *MockContextCompressor) Compress(ctx context.Context, messages []entity.Message, config entity.LLMConfig) ([]entity.Message, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compress", ctx, messages, config)
	ret0, _ := ret[0].([]entity.Message)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Compress indicates an expected call of Compress.
func (mr *MockContextCompressorMockRecorder) Compress(ctx, messages, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compress", reflect.TypeOf((*MockContextCompressor)(nil).Compress), ctx, messages, config)
}

// MockWorkflowTemplateRepo is a mock of WorkflowTemplateRepo interface.
type MockWorkflowTemplateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowTemplateRepoMockRecorder
	isgomock struct{}
}

// MockWorkflowTemplateRepoMockRecorder is the mock recorder for MockWorkflowTemplateRepo.
type MockWorkflowTemplateRepoMockRecorder struct {
	mock *MockWorkflowTemplateRepo
}

// NewMockWorkflowTemplateRepo creates a new mock instance.
func NewMockWorkflowTemplateRepo(ctrl *gomock.Controller) *MockWorkflowTemplateRepo {
	mock := &MockWorkflowTemplateRepo{ctrl: ctrl}
	mock.recorder = &MockWorkflowTemplateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowTemplateRepo) EXPECT() *MockWorkflowTemplateRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowTemplateRepo) Create(ctx context.Context, req *entity.CreateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowTemplateRepoMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockWorkflowTemplateRepo) Delete(ctx context.Context, accountID, templateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, accountID, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowTemplateRepoMockRecorder) Delete(ctx, accountID, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Delete), ctx, accountID, templateID)
}

// Get mocks base method.
func (m *MockWorkflowTemplateRepo) Get(ctx context.Context, accountID, templateID string) (entity.WorkflowTemplate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, accountID, templateID)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockWorkflowTemplateRepoMockRecorder) Get(ctx, accountID, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Get), ctx, accountID, templateID)
}

// ListByAccount mocks base method.
func (m *MockWorkflowTemplateRepo) ListByAccount(ctx context.Context, accountID string) ([]entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockWorkflowTemplateRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).ListByAccount), ctx, accountID)
}

// Update mocks base method.
func (m *MockWorkflowTemplateRepo) Update(ctx context.Context, accountID, templateID string, req entity.UpdateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, accountID, templateID, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowTemplateRepoMockRecorder) Update(ctx, accountID, templateID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Update), ctx, accountID, templateID, req)
}

// MockCreditManager is a mock of CreditManager interface.
type MockCreditManager struct {
	ctrl     *gomock.Controller
	recorder *MockCreditManagerMockRecorder
	isgomock struct{}
}

// MockCreditManagerMockRecorder is the mock recorder for MockCreditManager.
type MockCreditManagerMockRecorder struct {
	mock *MockCreditManager
}

// NewMockCreditManager creates a new mock instance.
func NewMockCreditManager(ctrl *gomock.Controller) *MockCreditManager {
	mock := &MockCreditManager{ctrl: ctrl}
	mock.recorder = &MockCreditManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditManager) EXPECT() *MockCreditManagerMockRecorder {
	return m.recorder
}

// AddCredits mocks base method.
func (m *MockCreditManager) AddCredits(ctx context.Context, accountID string, amount entity.Money, description string) (entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredits", ctx, accountID, amount, description)
	ret0, _ := ret[0].(entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCredits indicates an expected call of AddCredits.
func (mr *MockCreditManagerMockRecorder) AddCredits(ctx, accountID, amount, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredits", reflect.TypeOf((*MockCreditManager)(nil).AddCredits), ctx, accountID, amount, description)
}

// Deduct mocks base method.
func (m *MockCreditManager) Deduct(ctx context.Context, accountID string, amount entity.Money, description string) (entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deduct", ctx, accountID, amount, description)
	ret0, _ := ret[0].(entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deduct indicates an expected call of Deduct.
func (mr *MockCreditManagerMockRecorder) Deduct(ctx, accountID, amount, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deduct", reflect.TypeOf((*MockCreditManager)(nil).Deduct), ctx, accountID, amount, description)
}

// GetBalance mocks base method.
func (m *MockCreditManager) GetBalance(ctx context.Context, accountID string) (entity.CreditAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(entity.CreditAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockCreditManagerMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockCreditManager)(nil).GetBalance), ctx, accountID)
}

// GetHistory mocks base method.
func (m *MockCreditManager) GetHistory(ctx context.Context, accountID string, limit, offset int) ([]entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockCreditManagerMockRecorder) GetHistory(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockCreditManager)(nil).GetHistory), ctx, accountID, limit, offset)
}

// MockCostCalculator is a mock of CostCalculator interface.
type MockCostCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCostCalculatorMockRecorder
	isgomock struct{}
}

// MockCostCalculatorMockRecorder is the mock recorder for MockCostCalculator.
type MockCostCalculatorMockRecorder struct {
	mock *MockCostCalculator
}

// NewMockCostCalculator creates a new mock instance.
func NewMockCostCalculator(ctrl *gomock.Controller) *MockCostCalculator {
	mock := &MockCostCalculator{ctrl: ctrl}
	mock.recorder = &MockCostCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostCalculator) EXPECT() *MockCostCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCostCalculator) Calculate(ctx context.Context, modelID string, usage entity.Usage) (entity.Money, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, modelID, usage)
	ret0, _ := ret[0].(entity.Money)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCostCalculatorMockRecorder) Calculate(ctx, modelID, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCostCalculator)(nil).Calculate), ctx, modelID, usage)
}

// MockUsageRecordRepo is a mock of UsageRecordRepo interface.
type MockUsageRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsageRecordRepoMockRecorder
	isgomock struct{}
}

// MockUsageRecordRepoMockRecorder is the mock recorder for MockUsageRecordRepo.
type MockUsageRecordRepoMockRecorder struct {
	mock *MockUsageRecordRepo
}

// NewMockUsageRecordRepo creates a new mock instance.
func NewMockUsageRecordRepo(ctrl *gomock.Controller) *MockUsageRecordRepo {
	mock := &MockUsageRecordRepo{ctrl: ctrl}
	mock.recorder = &MockUsageRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageRecordRepo) EXPECT() *MockUsageRecordRepoMockRecorder {
	return m.recorder
}

// CreateUsageRecord mocks base method.
func (m *MockUsageRecordRepo) CreateUsageRecord(ctx context.Context, record *entity.UsageRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsageRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUsageRecord indicates an expected call of CreateUsageRecord.
func (mr *MockUsageRecordRepoMockRecorder) CreateUsageRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsageRecord", reflect.TypeOf((*MockUsageRecordRepo)(nil).CreateUsageRecord), ctx, record)
}
