// Code generated by MockGen. DO NOT EDIT.
// Source: ./repo/contracts.go
//
// Generated by this command:
//
//	mockgen -source ./repo/contracts.go -package usecase_test
//

// Package usecase_test is a generated GoMock package.
package usecase_test

import (
	context "context"
	reflect "reflect"

	entity "github.com/TekkenSteve/GoAgent/internal/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockWarmStateRepo is a mock of WarmStateRepo interface.
type MockWarmStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWarmStateRepoMockRecorder
	isgomock struct{}
}

// MockWarmStateRepoMockRecorder is the mock recorder for MockWarmStateRepo.
type MockWarmStateRepoMockRecorder struct {
	mock *MockWarmStateRepo
}

// NewMockWarmStateRepo creates a new mock instance.
func NewMockWarmStateRepo(ctrl *gomock.Controller) *MockWarmStateRepo {
	mock := &MockWarmStateRepo{ctrl: ctrl}
	mock.recorder = &MockWarmStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWarmStateRepo) EXPECT() *MockWarmStateRepoMockRecorder {
	return m.recorder
}

// GetMessage mocks base method.
func (m *MockWarmStateRepo) GetMessage(ctx context.Context, ref string) (entity.MessageRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, ref)
	ret0, _ := ret[0].(entity.MessageRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockWarmStateRepoMockRecorder) GetMessage(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockWarmStateRepo)(nil).GetMessage), ctx, ref)
}

// GetToolResult mocks base method.
func (m *MockWarmStateRepo) GetToolResult(ctx context.Context, ref string) (entity.ToolResultRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolResult", ctx, ref)
	ret0, _ := ret[0].(entity.ToolResultRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetToolResult indicates an expected call of GetToolResult.
func (mr *MockWarmStateRepoMockRecorder) GetToolResult(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolResult", reflect.TypeOf((*MockWarmStateRepo)(nil).GetToolResult), ctx, ref)
}

// ListMessagesByRun mocks base method.
func (m *MockWarmStateRepo) ListMessagesByRun(ctx context.Context, runID string, limit, offset uint64) ([]entity.MessageRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagesByRun", ctx, runID, limit, offset)
	ret0, _ := ret[0].([]entity.MessageRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessagesByRun indicates an expected call of ListMessagesByRun.
func (mr *MockWarmStateRepoMockRecorder) ListMessagesByRun(ctx, runID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagesByRun", reflect.TypeOf((*MockWarmStateRepo)(nil).ListMessagesByRun), ctx, runID, limit, offset)
}

// ListToolResultsByRun mocks base method.
func (m *MockWarmStateRepo) ListToolResultsByRun(ctx context.Context, runID string, limit, offset uint64) ([]entity.ToolResultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToolResultsByRun", ctx, runID, limit, offset)
	ret0, _ := ret[0].([]entity.ToolResultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToolResultsByRun indicates an expected call of ListToolResultsByRun.
func (mr *MockWarmStateRepoMockRecorder) ListToolResultsByRun(ctx, runID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToolResultsByRun", reflect.TypeOf((*MockWarmStateRepo)(nil).ListToolResultsByRun), ctx, runID, limit, offset)
}

// PersistMessage mocks base method.
func (m *MockWarmStateRepo) PersistMessage(ctx context.Context, record entity.MessageRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistMessage", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistMessage indicates an expected call of PersistMessage.
func (mr *MockWarmStateRepoMockRecorder) PersistMessage(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistMessage", reflect.TypeOf((*MockWarmStateRepo)(nil).PersistMessage), ctx, record)
}

// PersistToolResult mocks base method.
func (m *MockWarmStateRepo) PersistToolResult(ctx context.Context, record entity.ToolResultRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistToolResult", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistToolResult indicates an expected call of PersistToolResult.
func (mr *MockWarmStateRepoMockRecorder) PersistToolResult(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistToolResult", reflect.TypeOf((*MockWarmStateRepo)(nil).PersistToolResult), ctx, record)
}

// MockColdStateRepo is a mock of ColdStateRepo interface.
type MockColdStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockColdStateRepoMockRecorder
	isgomock struct{}
}

// MockColdStateRepoMockRecorder is the mock recorder for MockColdStateRepo.
type MockColdStateRepoMockRecorder struct {
	mock *MockColdStateRepo
}

// NewMockColdStateRepo creates a new mock instance.
func NewMockColdStateRepo(ctrl *gomock.Controller) *MockColdStateRepo {
	mock := &MockColdStateRepo{ctrl: ctrl}
	mock.recorder = &MockColdStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStateRepo) EXPECT() *MockColdStateRepoMockRecorder {
	return m.recorder
}

// GetArchive mocks base method.
func (m *MockColdStateRepo) GetArchive(ctx context.Context, ref string) (entity.ArchiveRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchive", ctx, ref)
	ret0, _ := ret[0].(entity.ArchiveRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchive indicates an expected call of GetArchive.
func (mr *MockColdStateRepoMockRecorder) GetArchive(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchive", reflect.TypeOf((*MockColdStateRepo)(nil).GetArchive), ctx, ref)
}

// PersistArchive mocks base method.
func (m *MockColdStateRepo) PersistArchive(ctx context.Context, record entity.ArchiveRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistArchive", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistArchive indicates an expected call of PersistArchive.
func (mr *MockColdStateRepoMockRecorder) PersistArchive(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistArchive", reflect.TypeOf((*MockColdStateRepo)(nil).PersistArchive), ctx, record)
}

// MockWorkflowStateRepo is a mock of WorkflowStateRepo interface.
type MockWorkflowStateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowStateRepoMockRecorder
	isgomock struct{}
}

// MockWorkflowStateRepoMockRecorder is the mock recorder for MockWorkflowStateRepo.
type MockWorkflowStateRepoMockRecorder struct {
	mock *MockWorkflowStateRepo
}

// NewMockWorkflowStateRepo creates a new mock instance.
func NewMockWorkflowStateRepo(ctrl *gomock.Controller) *MockWorkflowStateRepo {
	mock := &MockWorkflowStateRepo{ctrl: ctrl}
	mock.recorder = &MockWorkflowStateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowStateRepo) EXPECT() *MockWorkflowStateRepoMockRecorder {
	return m.recorder
}

// GetArchive mocks base method.
func (m *MockWorkflowStateRepo) GetArchive(ctx context.Context, ref string) (entity.ArchiveRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetArchive", ctx, ref)
	ret0, _ := ret[0].(entity.ArchiveRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetArchive indicates an expected call of GetArchive.
func (mr *MockWorkflowStateRepoMockRecorder) GetArchive(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetArchive", reflect.TypeOf((*MockWorkflowStateRepo)(nil).GetArchive), ctx, ref)
}

// GetMessage mocks base method.
func (m *MockWorkflowStateRepo) GetMessage(ctx context.Context, ref string) (entity.MessageRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, ref)
	ret0, _ := ret[0].(entity.MessageRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockWorkflowStateRepoMockRecorder) GetMessage(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockWorkflowStateRepo)(nil).GetMessage), ctx, ref)
}

// GetToolResult mocks base method.
func (m *MockWorkflowStateRepo) GetToolResult(ctx context.Context, ref string) (entity.ToolResultRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToolResult", ctx, ref)
	ret0, _ := ret[0].(entity.ToolResultRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetToolResult indicates an expected call of GetToolResult.
func (mr *MockWorkflowStateRepoMockRecorder) GetToolResult(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToolResult", reflect.TypeOf((*MockWorkflowStateRepo)(nil).GetToolResult), ctx, ref)
}

// ListMessagesByRun mocks base method.
func (m *MockWorkflowStateRepo) ListMessagesByRun(ctx context.Context, runID string, limit, offset uint64) ([]entity.MessageRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMessagesByRun", ctx, runID, limit, offset)
	ret0, _ := ret[0].([]entity.MessageRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMessagesByRun indicates an expected call of ListMessagesByRun.
func (mr *MockWorkflowStateRepoMockRecorder) ListMessagesByRun(ctx, runID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMessagesByRun", reflect.TypeOf((*MockWorkflowStateRepo)(nil).ListMessagesByRun), ctx, runID, limit, offset)
}

// ListToolResultsByRun mocks base method.
func (m *MockWorkflowStateRepo) ListToolResultsByRun(ctx context.Context, runID string, limit, offset uint64) ([]entity.ToolResultRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToolResultsByRun", ctx, runID, limit, offset)
	ret0, _ := ret[0].([]entity.ToolResultRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToolResultsByRun indicates an expected call of ListToolResultsByRun.
func (mr *MockWorkflowStateRepoMockRecorder) ListToolResultsByRun(ctx, runID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToolResultsByRun", reflect.TypeOf((*MockWorkflowStateRepo)(nil).ListToolResultsByRun), ctx, runID, limit, offset)
}

// PersistArchive mocks base method.
func (m *MockWorkflowStateRepo) PersistArchive(ctx context.Context, record entity.ArchiveRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistArchive", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistArchive indicates an expected call of PersistArchive.
func (mr *MockWorkflowStateRepoMockRecorder) PersistArchive(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistArchive", reflect.TypeOf((*MockWorkflowStateRepo)(nil).PersistArchive), ctx, record)
}

// PersistMessage mocks base method.
func (m *MockWorkflowStateRepo) PersistMessage(ctx context.Context, record entity.MessageRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistMessage", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistMessage indicates an expected call of PersistMessage.
func (mr *MockWorkflowStateRepoMockRecorder) PersistMessage(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistMessage", reflect.TypeOf((*MockWorkflowStateRepo)(nil).PersistMessage), ctx, record)
}

// PersistToolResult mocks base method.
func (m *MockWorkflowStateRepo) PersistToolResult(ctx context.Context, record entity.ToolResultRecord) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PersistToolResult", ctx, record)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PersistToolResult indicates an expected call of PersistToolResult.
func (mr *MockWorkflowStateRepoMockRecorder) PersistToolResult(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PersistToolResult", reflect.TypeOf((*MockWorkflowStateRepo)(nil).PersistToolResult), ctx, record)
}

// MockAgentRepo is a mock of AgentRepo interface.
type MockAgentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAgentRepoMockRecorder
	isgomock struct{}
}

// MockAgentRepoMockRecorder is the mock recorder for MockAgentRepo.
type MockAgentRepoMockRecorder struct {
	mock *MockAgentRepo
}

// NewMockAgentRepo creates a new mock instance.
func NewMockAgentRepo(ctrl *gomock.Controller) *MockAgentRepo {
	mock := &MockAgentRepo{ctrl: ctrl}
	mock.recorder = &MockAgentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentRepo) EXPECT() *MockAgentRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAgentRepo) Create(ctx context.Context, req *entity.CreateAgentRequest) (entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAgentRepoMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAgentRepo)(nil).Create), ctx, req)
}

// CreateVersion mocks base method.
func (m *MockAgentRepo) CreateVersion(ctx context.Context, record *entity.AgentVersionRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockAgentRepoMockRecorder) CreateVersion(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockAgentRepo)(nil).CreateVersion), ctx, record)
}

// Delete mocks base method.
func (m *MockAgentRepo) Delete(ctx context.Context, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAgentRepoMockRecorder) Delete(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAgentRepo)(nil).Delete), ctx, agentID)
}

// Get mocks base method.
func (m *MockAgentRepo) Get(ctx context.Context, agentID string) (entity.AgentRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, agentID)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockAgentRepoMockRecorder) Get(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAgentRepo)(nil).Get), ctx, agentID)
}

// GetVersion mocks base method.
func (m *MockAgentRepo) GetVersion(ctx context.Context, versionID string) (entity.AgentVersionRecord, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, versionID)
	ret0, _ := ret[0].(entity.AgentVersionRecord)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockAgentRepoMockRecorder) GetVersion(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockAgentRepo)(nil).GetVersion), ctx, versionID)
}

// ListByAccount mocks base method.
func (m *MockAgentRepo) ListByAccount(ctx context.Context, accountID string) ([]entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockAgentRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockAgentRepo)(nil).ListByAccount), ctx, accountID)
}

// ListVersions mocks base method.
func (m *MockAgentRepo) ListVersions(ctx context.Context, agentID string) ([]entity.AgentVersionRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, agentID)
	ret0, _ := ret[0].([]entity.AgentVersionRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockAgentRepoMockRecorder) ListVersions(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockAgentRepo)(nil).ListVersions), ctx, agentID)
}

// Update mocks base method.
func (m *MockAgentRepo) Update(ctx context.Context, agentID string, req entity.UpdateAgentRequest) (entity.AgentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, agentID, req)
	ret0, _ := ret[0].(entity.AgentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockAgentRepoMockRecorder) Update(ctx, agentID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAgentRepo)(nil).Update), ctx, agentID, req)
}

// MockLLMProvider is a mock of LLMProvider interface.
type MockLLMProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMProviderMockRecorder
	isgomock struct{}
}

// MockLLMProviderMockRecorder is the mock recorder for MockLLMProvider.
type MockLLMProviderMockRecorder struct {
	mock *MockLLMProvider
}

// NewMockLLMProvider creates a new mock instance.
func NewMockLLMProvider(ctrl *gomock.Controller) *MockLLMProvider {
	mock := &MockLLMProvider{ctrl: ctrl}
	mock.recorder = &MockLLMProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMProvider) EXPECT() *MockLLMProviderMockRecorder {
	return m.recorder
}

// Chat mocks base method.
func (m *MockLLMProvider) Chat(ctx context.Context, req *entity.LLMRequest) (entity.LLMResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Chat", ctx, req)
	ret0, _ := ret[0].(entity.LLMResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Chat indicates an expected call of Chat.
func (mr *MockLLMProviderMockRecorder) Chat(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Chat", reflect.TypeOf((*MockLLMProvider)(nil).Chat), ctx, req)
}

// MockLLMStreamProvider is a mock of LLMStreamProvider interface.
type MockLLMStreamProvider struct {
	ctrl     *gomock.Controller
	recorder *MockLLMStreamProviderMockRecorder
	isgomock struct{}
}

// MockLLMStreamProviderMockRecorder is the mock recorder for MockLLMStreamProvider.
type MockLLMStreamProviderMockRecorder struct {
	mock *MockLLMStreamProvider
}

// NewMockLLMStreamProvider creates a new mock instance.
func NewMockLLMStreamProvider(ctrl *gomock.Controller) *MockLLMStreamProvider {
	mock := &MockLLMStreamProvider{ctrl: ctrl}
	mock.recorder = &MockLLMStreamProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLLMStreamProvider) EXPECT() *MockLLMStreamProviderMockRecorder {
	return m.recorder
}

// ChatStream mocks base method.
func (m *MockLLMStreamProvider) ChatStream(ctx context.Context, req *entity.LLMRequest) (<-chan entity.LLMStreamChunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChatStream", ctx, req)
	ret0, _ := ret[0].(<-chan entity.LLMStreamChunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChatStream indicates an expected call of ChatStream.
func (mr *MockLLMStreamProviderMockRecorder) ChatStream(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChatStream", reflect.TypeOf((*MockLLMStreamProvider)(nil).ChatStream), ctx, req)
}

// MockToolExecutor is a mock of ToolExecutor interface.
type MockToolExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockToolExecutorMockRecorder
	isgomock struct{}
}

// MockToolExecutorMockRecorder is the mock recorder for MockToolExecutor.
type MockToolExecutorMockRecorder struct {
	mock *MockToolExecutor
}

// NewMockToolExecutor creates a new mock instance.
func NewMockToolExecutor(ctrl *gomock.Controller) *MockToolExecutor {
	mock := &MockToolExecutor{ctrl: ctrl}
	mock.recorder = &MockToolExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockToolExecutor) EXPECT() *MockToolExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockToolExecutor) Execute(ctx context.Context, req *entity.ToolRequest) (entity.ToolResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(entity.ToolResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockToolExecutorMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockToolExecutor)(nil).Execute), ctx, req)
}

// MockWALAppender is a mock of WALAppender interface.
type MockWALAppender struct {
	ctrl     *gomock.Controller
	recorder *MockWALAppenderMockRecorder
	isgomock struct{}
}

// MockWALAppenderMockRecorder is the mock recorder for MockWALAppender.
type MockWALAppenderMockRecorder struct {
	mock *MockWALAppender
}

// NewMockWALAppender creates a new mock instance.
func NewMockWALAppender(ctrl *gomock.Controller) *MockWALAppender {
	mock := &MockWALAppender{ctrl: ctrl}
	mock.recorder = &MockWALAppenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWALAppender) EXPECT() *MockWALAppenderMockRecorder {
	return m.recorder
}

// AppendMessage mocks base method.
func (m *MockWALAppender) AppendMessage(ctx context.Context, runID string, record entity.MessageRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendMessage", ctx, runID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendMessage indicates an expected call of AppendMessage.
func (mr *MockWALAppenderMockRecorder) AppendMessage(ctx, runID, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendMessage", reflect.TypeOf((*MockWALAppender)(nil).AppendMessage), ctx, runID, record)
}

// AppendToolResult mocks base method.
func (m *MockWALAppender) AppendToolResult(ctx context.Context, runID string, record entity.ToolResultRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendToolResult", ctx, runID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendToolResult indicates an expected call of AppendToolResult.
func (mr *MockWALAppenderMockRecorder) AppendToolResult(ctx, runID, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendToolResult", reflect.TypeOf((*MockWALAppender)(nil).AppendToolResult), ctx, runID, record)
}

// MockContextCompressor is a mock of ContextCompressor interface.
type MockContextCompressor struct {
	ctrl     *gomock.Controller
	recorder *MockContextCompressorMockRecorder
	isgomock struct{}
}

// MockContextCompressorMockRecorder is the mock recorder for MockContextCompressor.
type MockContextCompressorMockRecorder struct {
	mock *MockContextCompressor
}

// NewMockContextCompressor creates a new mock instance.
func NewMockContextCompressor(ctrl *gomock.Controller) *MockContextCompressor {
	mock := &MockContextCompressor{ctrl: ctrl}
	mock.recorder = &MockContextCompressorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContextCompressor) EXPECT() *MockContextCompressorMockRecorder {
	return m.recorder
}

// Compress mocks base method.
func (m *MockContextCompressor) Compress(ctx context.Context, messages []entity.Message, config entity.LLMConfig) ([]entity.Message, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compress", ctx, messages, config)
	ret0, _ := ret[0].([]entity.Message)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Compress indicates an expected call of Compress.
func (mr *MockContextCompressorMockRecorder) Compress(ctx, messages, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compress", reflect.TypeOf((*MockContextCompressor)(nil).Compress), ctx, messages, config)
}

// MockExecutorRepo is a mock of ExecutorRepo interface.
type MockExecutorRepo struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorRepoMockRecorder
	isgomock struct{}
}

// MockExecutorRepoMockRecorder is the mock recorder for MockExecutorRepo.
type MockExecutorRepoMockRecorder struct {
	mock *MockExecutorRepo
}

// NewMockExecutorRepo creates a new mock instance.
func NewMockExecutorRepo(ctrl *gomock.Controller) *MockExecutorRepo {
	mock := &MockExecutorRepo{ctrl: ctrl}
	mock.recorder = &MockExecutorRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutorRepo) EXPECT() *MockExecutorRepoMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockExecutorRepo) Cancel(ctx context.Context, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockExecutorRepoMockRecorder) Cancel(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockExecutorRepo)(nil).Cancel), ctx, runID)
}

// GetOrchestrationStatus mocks base method.
func (m *MockExecutorRepo) GetOrchestrationStatus(ctx context.Context, runID string) (entity.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrchestrationStatus", ctx, runID)
	ret0, _ := ret[0].(entity.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrchestrationStatus indicates an expected call of GetOrchestrationStatus.
func (mr *MockExecutorRepoMockRecorder) GetOrchestrationStatus(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrchestrationStatus", reflect.TypeOf((*MockExecutorRepo)(nil).GetOrchestrationStatus), ctx, runID)
}

// GetStatus mocks base method.
func (m *MockExecutorRepo) GetStatus(ctx context.Context, runID string) (entity.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus", ctx, runID)
	ret0, _ := ret[0].(entity.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockExecutorRepoMockRecorder) GetStatus(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockExecutorRepo)(nil).GetStatus), ctx, runID)
}

// Pause mocks base method.
func (m *MockExecutorRepo) Pause(ctx context.Context, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockExecutorRepoMockRecorder) Pause(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockExecutorRepo)(nil).Pause), ctx, runID)
}

// Resume mocks base method.
func (m *MockExecutorRepo) Resume(ctx context.Context, runID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resume", ctx, runID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resume indicates an expected call of Resume.
func (mr *MockExecutorRepoMockRecorder) Resume(ctx, runID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resume", reflect.TypeOf((*MockExecutorRepo)(nil).Resume), ctx, runID)
}

// StartExecution mocks base method.
func (m *MockExecutorRepo) StartExecution(ctx context.Context, req *entity.ExecuteRequest) (entity.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExecution", ctx, req)
	ret0, _ := ret[0].(entity.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartExecution indicates an expected call of StartExecution.
func (mr *MockExecutorRepoMockRecorder) StartExecution(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExecution", reflect.TypeOf((*MockExecutorRepo)(nil).StartExecution), ctx, req)
}

// StartOrchestration mocks base method.
func (m *MockExecutorRepo) StartOrchestration(ctx context.Context, input *entity.OrchestrationInput) (entity.RunStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartOrchestration", ctx, input)
	ret0, _ := ret[0].(entity.RunStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartOrchestration indicates an expected call of StartOrchestration.
func (mr *MockExecutorRepoMockRecorder) StartOrchestration(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartOrchestration", reflect.TypeOf((*MockExecutorRepo)(nil).StartOrchestration), ctx, input)
}

// MockWorkflowTemplateRepo is a mock of WorkflowTemplateRepo interface.
type MockWorkflowTemplateRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowTemplateRepoMockRecorder
	isgomock struct{}
}

// MockWorkflowTemplateRepoMockRecorder is the mock recorder for MockWorkflowTemplateRepo.
type MockWorkflowTemplateRepoMockRecorder struct {
	mock *MockWorkflowTemplateRepo
}

// NewMockWorkflowTemplateRepo creates a new mock instance.
func NewMockWorkflowTemplateRepo(ctrl *gomock.Controller) *MockWorkflowTemplateRepo {
	mock := &MockWorkflowTemplateRepo{ctrl: ctrl}
	mock.recorder = &MockWorkflowTemplateRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowTemplateRepo) EXPECT() *MockWorkflowTemplateRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockWorkflowTemplateRepo) Create(ctx context.Context, req *entity.CreateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockWorkflowTemplateRepoMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockWorkflowTemplateRepo) Delete(ctx context.Context, templateID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, templateID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockWorkflowTemplateRepoMockRecorder) Delete(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Delete), ctx, templateID)
}

// Get mocks base method.
func (m *MockWorkflowTemplateRepo) Get(ctx context.Context, templateID string) (entity.WorkflowTemplate, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, templateID)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockWorkflowTemplateRepoMockRecorder) Get(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Get), ctx, templateID)
}

// ListByAccount mocks base method.
func (m *MockWorkflowTemplateRepo) ListByAccount(ctx context.Context, accountID string) ([]entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAccount", ctx, accountID)
	ret0, _ := ret[0].([]entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAccount indicates an expected call of ListByAccount.
func (mr *MockWorkflowTemplateRepoMockRecorder) ListByAccount(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAccount", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).ListByAccount), ctx, accountID)
}

// Update mocks base method.
func (m *MockWorkflowTemplateRepo) Update(ctx context.Context, templateID string, req entity.UpdateWorkflowTemplateRequest) (entity.WorkflowTemplate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, templateID, req)
	ret0, _ := ret[0].(entity.WorkflowTemplate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockWorkflowTemplateRepoMockRecorder) Update(ctx, templateID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockWorkflowTemplateRepo)(nil).Update), ctx, templateID, req)
}

// MockTriggerRepo is a mock of TriggerRepo interface.
type MockTriggerRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerRepoMockRecorder
	isgomock struct{}
}

// MockTriggerRepoMockRecorder is the mock recorder for MockTriggerRepo.
type MockTriggerRepoMockRecorder struct {
	mock *MockTriggerRepo
}

// NewMockTriggerRepo creates a new mock instance.
func NewMockTriggerRepo(ctrl *gomock.Controller) *MockTriggerRepo {
	mock := &MockTriggerRepo{ctrl: ctrl}
	mock.recorder = &MockTriggerRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerRepo) EXPECT() *MockTriggerRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTriggerRepo) Create(ctx context.Context, req *entity.CreateTriggerRequest) (entity.TriggerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(entity.TriggerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTriggerRepoMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTriggerRepo)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockTriggerRepo) Delete(ctx context.Context, triggerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, triggerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTriggerRepoMockRecorder) Delete(ctx, triggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTriggerRepo)(nil).Delete), ctx, triggerID)
}

// Get mocks base method.
func (m *MockTriggerRepo) Get(ctx context.Context, triggerID string) (entity.TriggerSpec, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, triggerID)
	ret0, _ := ret[0].(entity.TriggerSpec)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockTriggerRepoMockRecorder) Get(ctx, triggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTriggerRepo)(nil).Get), ctx, triggerID)
}

// InsertTriggerEvent mocks base method.
func (m *MockTriggerRepo) InsertTriggerEvent(ctx context.Context, event *entity.TriggerEventLog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTriggerEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTriggerEvent indicates an expected call of InsertTriggerEvent.
func (mr *MockTriggerRepoMockRecorder) InsertTriggerEvent(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTriggerEvent", reflect.TypeOf((*MockTriggerRepo)(nil).InsertTriggerEvent), ctx, event)
}

// ListActive mocks base method.
func (m *MockTriggerRepo) ListActive(ctx context.Context) ([]entity.TriggerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]entity.TriggerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockTriggerRepoMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockTriggerRepo)(nil).ListActive), ctx)
}

// ListByTemplate mocks base method.
func (m *MockTriggerRepo) ListByTemplate(ctx context.Context, templateID string) ([]entity.TriggerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByTemplate", ctx, templateID)
	ret0, _ := ret[0].([]entity.TriggerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByTemplate indicates an expected call of ListByTemplate.
func (mr *MockTriggerRepoMockRecorder) ListByTemplate(ctx, templateID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByTemplate", reflect.TypeOf((*MockTriggerRepo)(nil).ListByTemplate), ctx, templateID)
}

// ListByType mocks base method.
func (m *MockTriggerRepo) ListByType(ctx context.Context, triggerType entity.TriggerType) ([]entity.TriggerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByType", ctx, triggerType)
	ret0, _ := ret[0].([]entity.TriggerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByType indicates an expected call of ListByType.
func (mr *MockTriggerRepoMockRecorder) ListByType(ctx, triggerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByType", reflect.TypeOf((*MockTriggerRepo)(nil).ListByType), ctx, triggerType)
}

// RecordFired mocks base method.
func (m *MockTriggerRepo) RecordFired(ctx context.Context, triggerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordFired", ctx, triggerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordFired indicates an expected call of RecordFired.
func (mr *MockTriggerRepoMockRecorder) RecordFired(ctx, triggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordFired", reflect.TypeOf((*MockTriggerRepo)(nil).RecordFired), ctx, triggerID)
}

// Update mocks base method.
func (m *MockTriggerRepo) Update(ctx context.Context, triggerID string, req entity.UpdateTriggerRequest) (entity.TriggerSpec, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, triggerID, req)
	ret0, _ := ret[0].(entity.TriggerSpec)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTriggerRepoMockRecorder) Update(ctx, triggerID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTriggerRepo)(nil).Update), ctx, triggerID, req)
}

// MockTriggerScheduler is a mock of TriggerScheduler interface.
type MockTriggerScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockTriggerSchedulerMockRecorder
	isgomock struct{}
}

// MockTriggerSchedulerMockRecorder is the mock recorder for MockTriggerScheduler.
type MockTriggerSchedulerMockRecorder struct {
	mock *MockTriggerScheduler
}

// NewMockTriggerScheduler creates a new mock instance.
func NewMockTriggerScheduler(ctrl *gomock.Controller) *MockTriggerScheduler {
	mock := &MockTriggerScheduler{ctrl: ctrl}
	mock.recorder = &MockTriggerSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTriggerScheduler) EXPECT() *MockTriggerSchedulerMockRecorder {
	return m.recorder
}

// Schedule mocks base method.
func (m *MockTriggerScheduler) Schedule(ctx context.Context, trigger *entity.TriggerSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", ctx, trigger)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockTriggerSchedulerMockRecorder) Schedule(ctx, trigger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockTriggerScheduler)(nil).Schedule), ctx, trigger)
}

// Unschedule mocks base method.
func (m *MockTriggerScheduler) Unschedule(ctx context.Context, triggerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unschedule", ctx, triggerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unschedule indicates an expected call of Unschedule.
func (mr *MockTriggerSchedulerMockRecorder) Unschedule(ctx, triggerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unschedule", reflect.TypeOf((*MockTriggerScheduler)(nil).Unschedule), ctx, triggerID)
}

// MockCreditManager is a mock of CreditManager interface.
type MockCreditManager struct {
	ctrl     *gomock.Controller
	recorder *MockCreditManagerMockRecorder
	isgomock struct{}
}

// MockCreditManagerMockRecorder is the mock recorder for MockCreditManager.
type MockCreditManagerMockRecorder struct {
	mock *MockCreditManager
}

// NewMockCreditManager creates a new mock instance.
func NewMockCreditManager(ctrl *gomock.Controller) *MockCreditManager {
	mock := &MockCreditManager{ctrl: ctrl}
	mock.recorder = &MockCreditManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreditManager) EXPECT() *MockCreditManagerMockRecorder {
	return m.recorder
}

// AddCredits mocks base method.
func (m *MockCreditManager) AddCredits(ctx context.Context, accountID string, amount entity.Money, description string) (entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCredits", ctx, accountID, amount, description)
	ret0, _ := ret[0].(entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddCredits indicates an expected call of AddCredits.
func (mr *MockCreditManagerMockRecorder) AddCredits(ctx, accountID, amount, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCredits", reflect.TypeOf((*MockCreditManager)(nil).AddCredits), ctx, accountID, amount, description)
}

// Deduct mocks base method.
func (m *MockCreditManager) Deduct(ctx context.Context, accountID string, amount entity.Money, description string) (entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deduct", ctx, accountID, amount, description)
	ret0, _ := ret[0].(entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Deduct indicates an expected call of Deduct.
func (mr *MockCreditManagerMockRecorder) Deduct(ctx, accountID, amount, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deduct", reflect.TypeOf((*MockCreditManager)(nil).Deduct), ctx, accountID, amount, description)
}

// GetBalance mocks base method.
func (m *MockCreditManager) GetBalance(ctx context.Context, accountID string) (entity.CreditAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx, accountID)
	ret0, _ := ret[0].(entity.CreditAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockCreditManagerMockRecorder) GetBalance(ctx, accountID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockCreditManager)(nil).GetBalance), ctx, accountID)
}

// GetHistory mocks base method.
func (m *MockCreditManager) GetHistory(ctx context.Context, accountID string, limit, offset int) ([]entity.CreditTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, accountID, limit, offset)
	ret0, _ := ret[0].([]entity.CreditTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockCreditManagerMockRecorder) GetHistory(ctx, accountID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockCreditManager)(nil).GetHistory), ctx, accountID, limit, offset)
}

// MockCostCalculator is a mock of CostCalculator interface.
type MockCostCalculator struct {
	ctrl     *gomock.Controller
	recorder *MockCostCalculatorMockRecorder
	isgomock struct{}
}

// MockCostCalculatorMockRecorder is the mock recorder for MockCostCalculator.
type MockCostCalculatorMockRecorder struct {
	mock *MockCostCalculator
}

// NewMockCostCalculator creates a new mock instance.
func NewMockCostCalculator(ctrl *gomock.Controller) *MockCostCalculator {
	mock := &MockCostCalculator{ctrl: ctrl}
	mock.recorder = &MockCostCalculatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCostCalculator) EXPECT() *MockCostCalculatorMockRecorder {
	return m.recorder
}

// Calculate mocks base method.
func (m *MockCostCalculator) Calculate(ctx context.Context, modelID string, usage entity.Usage) (entity.Money, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Calculate", ctx, modelID, usage)
	ret0, _ := ret[0].(entity.Money)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Calculate indicates an expected call of Calculate.
func (mr *MockCostCalculatorMockRecorder) Calculate(ctx, modelID, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Calculate", reflect.TypeOf((*MockCostCalculator)(nil).Calculate), ctx, modelID, usage)
}

// MockUsageRecordRepo is a mock of UsageRecordRepo interface.
type MockUsageRecordRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUsageRecordRepoMockRecorder
	isgomock struct{}
}

// MockUsageRecordRepoMockRecorder is the mock recorder for MockUsageRecordRepo.
type MockUsageRecordRepoMockRecorder struct {
	mock *MockUsageRecordRepo
}

// NewMockUsageRecordRepo creates a new mock instance.
func NewMockUsageRecordRepo(ctrl *gomock.Controller) *MockUsageRecordRepo {
	mock := &MockUsageRecordRepo{ctrl: ctrl}
	mock.recorder = &MockUsageRecordRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageRecordRepo) EXPECT() *MockUsageRecordRepoMockRecorder {
	return m.recorder
}

// CreateUsageRecord mocks base method.
func (m *MockUsageRecordRepo) CreateUsageRecord(ctx context.Context, record *entity.UsageRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUsageRecord", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUsageRecord indicates an expected call of CreateUsageRecord.
func (mr *MockUsageRecordRepoMockRecorder) CreateUsageRecord(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUsageRecord", reflect.TypeOf((*MockUsageRecordRepo)(nil).CreateUsageRecord), ctx, record)
}
