// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/agentos/runs": {
            "post": {
                "description": "Start a generic AgentOS run on the selected backend.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentos"
                ],
                "summary": "Start AgentOS run",
                "operationId": "agentos-start-run",
                "parameters": [
                    {
                        "description": "AgentOS run request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AgentOSStart"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/agentos.RunStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/agentos/runs/{run_id}/control": {
            "post": {
                "description": "Send lifecycle control such as pause, resume, or cancel to an AgentOS run.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentos"
                ],
                "summary": "Control AgentOS run",
                "operationId": "agentos-control-run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AgentOS control operation",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AgentOSControl"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/agentos/runs/{run_id}/events": {
            "post": {
                "description": "Accept a normalized event from an external AgentOS backend.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentos"
                ],
                "summary": "Ingest AgentOS event",
                "operationId": "agentos-ingest-event",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AgentOS event",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/eventing.IngestEvent"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/v1.ingestAgentOSEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/agentos/runs/{run_id}/signals": {
            "post": {
                "description": "Send business input such as user.message to an AgentOS run.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentos"
                ],
                "summary": "Signal AgentOS run",
                "operationId": "agentos-signal-run",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AgentOS signal",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.AgentOSSignal"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/agentos/runs/{run_id}/status": {
            "get": {
                "description": "Query the current status of an AgentOS run.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agentos"
                ],
                "summary": "Get AgentOS run status",
                "operationId": "agentos-run-status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/agentos.RunStatus"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/orchestration/execute": {
            "post": {
                "description": "Start a multi-step orchestration workflow from a TeamSpec or step queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestration"
                ],
                "summary": "Execute orchestration workflow",
                "operationId": "orchestrate",
                "parameters": [
                    {
                        "description": "Orchestration request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Orchestrate"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RunStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        },
        "/orchestration/status/{run_id}": {
            "get": {
                "description": "Query the current status of an orchestration workflow",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "orchestration"
                ],
                "summary": "Get orchestration workflow status",
                "operationId": "orchestration-status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Run ID",
                        "name": "run_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.RunStatus"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "agentos.BackendKind": {
            "type": "string",
            "enum": [
                "native",
                "temporal_external",
                "http",
                "grpc"
            ],
            "x-enum-varnames": [
                "BackendKindNative",
                "BackendKindTemporalExternal",
                "BackendKindHTTP",
                "BackendKindGRPC"
            ]
        },
        "agentos.BackendRef": {
            "type": "object",
            "properties": {
                "kind": {
                    "$ref": "#/definitions/agentos.BackendKind"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "agentos.ControlOperation": {
            "type": "string",
            "enum": [
                "pause",
                "resume",
                "cancel"
            ],
            "x-enum-varnames": [
                "ControlPause",
                "ControlResume",
                "ControlCancel"
            ]
        },
        "agentos.RunStatus": {
            "type": "object",
            "properties": {
                "lifecycleState": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "runID": {
                    "type": "string"
                },
                "step": {
                    "type": "integer",
                    "format": "int32"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "agentos.SignalType": {
            "type": "string",
            "enum": [
                "control.pause",
                "control.resume",
                "control.cancel",
                "user.message",
                "user.approval",
                "user.reject",
                "tool.result",
                "human.feedback",
                "config.patch",
                "memory.patch"
            ],
            "x-enum-varnames": [
                "SignalControlPause",
                "SignalControlResume",
                "SignalControlCancel",
                "SignalUserMessage",
                "SignalUserApproval",
                "SignalUserReject",
                "SignalToolResult",
                "SignalHumanFeedback",
                "SignalConfigPatch",
                "SignalMemoryPatch"
            ]
        },
        "entity.AgentOSEventType": {
            "type": "string",
            "enum": [
                "run.started",
                "run.completed",
                "run.failed",
                "run.cancelled",
                "run.paused",
                "run.resumed",
                "agent.step.started",
                "agent.step.completed",
                "agent.step.failed",
                "agent.message.delta",
                "agent.message.completed",
                "tool.call.started",
                "tool.call.delta",
                "tool.call.completed",
                "tool.call.failed",
                "approval.requested",
                "approval.resolved",
                "usage.reported",
                "checkpoint.created"
            ],
            "x-enum-varnames": [
                "AgentOSEventRunStarted",
                "AgentOSEventRunCompleted",
                "AgentOSEventRunFailed",
                "AgentOSEventRunCancelled",
                "AgentOSEventRunPaused",
                "AgentOSEventRunResumed",
                "AgentOSEventAgentStepStarted",
                "AgentOSEventAgentStepCompleted",
                "AgentOSEventAgentStepFailed",
                "AgentOSEventAgentMessageDelta",
                "AgentOSEventAgentMessageCompleted",
                "AgentOSEventToolCallStarted",
                "AgentOSEventToolCallDelta",
                "AgentOSEventToolCallCompleted",
                "AgentOSEventToolCallFailed",
                "AgentOSEventApprovalRequested",
                "AgentOSEventApprovalResolved",
                "AgentOSEventUsageReported",
                "AgentOSEventCheckpointCreated"
            ]
        },
        "entity.AgentSpec": {
            "type": "object",
            "properties": {
                "config": {
                    "$ref": "#/definitions/entity.LLMConfig"
                },
                "id": {
                    "type": "string"
                },
                "model_ref": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                },
                "tools": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.ToolBinding"
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "entity.ContinuePolicy": {
            "type": "object",
            "properties": {
                "max_depth": {
                    "description": "max step queue length",
                    "type": "integer"
                },
                "max_rounds": {
                    "description": "max workflow loop iterations",
                    "type": "integer"
                }
            }
        },
        "entity.LLMConfig": {
            "type": "object",
            "properties": {
                "max_tokens": {
                    "type": "integer"
                },
                "model": {
                    "type": "string"
                },
                "provider": {
                    "description": "target provider name; empty = use default",
                    "type": "string"
                },
                "temperature": {
                    "type": "number"
                }
            }
        },
        "entity.Step": {
            "type": "object",
            "properties": {
                "agent_id": {
                    "description": "StepAgent",
                    "type": "string"
                },
                "depends_on": {
                    "description": "step IDs this depends on",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "error": {
                    "description": "failure reason",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "name": {
                    "type": "string"
                },
                "on_result": {
                    "description": "dynamic queue mutation",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.StepMutation"
                        }
                    ]
                },
                "result": {
                    "description": "populated after execution",
                    "type": "object",
                    "additionalProperties": {}
                },
                "status": {
                    "$ref": "#/definitions/entity.StepStatus"
                },
                "tool": {
                    "description": "StepTool",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entity.StepType"
                },
                "wait_for": {
                    "description": "StepWait config",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.WaitCondition"
                        }
                    ]
                }
            }
        },
        "entity.StepMutation": {
            "type": "object",
            "properties": {
                "append_after": {
                    "description": "insert after this step ID",
                    "type": "string"
                },
                "delete_steps": {
                    "description": "delete these step IDs",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "insert_steps": {
                    "description": "steps to insert",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Step"
                    }
                },
                "modify_step": {
                    "description": "replace this step ID",
                    "type": "string"
                }
            }
        },
        "entity.StepStatus": {
            "type": "string",
            "enum": [
                "pending",
                "running",
                "completed",
                "failed",
                "waiting",
                "blocked"
            ],
            "x-enum-comments": {
                "StepBlocked": "blocked on dependency",
                "StepWaiting": "blocked on signal/timer"
            },
            "x-enum-descriptions": [
                "",
                "",
                "",
                "",
                "blocked on signal/timer",
                "blocked on dependency"
            ],
            "x-enum-varnames": [
                "StepPending",
                "StepRunning",
                "StepCompleted",
                "StepFailed",
                "StepWaiting",
                "StepBlocked"
            ]
        },
        "entity.StepTemplate": {
            "type": "object",
            "properties": {
                "agent_ref": {
                    "description": "TeamSpec.Agents[i].ID",
                    "type": "string"
                },
                "depends_on": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "on_result": {
                    "$ref": "#/definitions/entity.StepMutation"
                },
                "tool": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entity.StepType"
                },
                "wait_for": {
                    "$ref": "#/definitions/entity.WaitCondition"
                }
            }
        },
        "entity.StepType": {
            "type": "string",
            "enum": [
                "agent",
                "tool",
                "wait",
                "split",
                "join",
                "eval"
            ],
            "x-enum-comments": {
                "StepAgent": "Start child AgentWorkflow and wait",
                "StepEval": "Conditional branch based on prior result",
                "StepJoin": "Fan-in from parallel sub-steps",
                "StepSplit": "Fan-out into parallel sub-steps",
                "StepTool": "Execute tool directly",
                "StepWait": "Wait for Temporal Signal or Timer"
            },
            "x-enum-descriptions": [
                "Start child AgentWorkflow and wait",
                "Execute tool directly",
                "Wait for Temporal Signal or Timer",
                "Fan-out into parallel sub-steps",
                "Fan-in from parallel sub-steps",
                "Conditional branch based on prior result"
            ],
            "x-enum-varnames": [
                "StepAgent",
                "StepTool",
                "StepWait",
                "StepSplit",
                "StepJoin",
                "StepEval"
            ]
        },
        "entity.TeamSpec": {
            "type": "object",
            "properties": {
                "agents": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.AgentSpec"
                    }
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.StepTemplate"
                    }
                },
                "sub_teams": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.TeamSpec"
                    }
                }
            }
        },
        "entity.ToolBinding": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "override default",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "required": {
                    "description": "fail if unavailable",
                    "type": "boolean"
                }
            }
        },
        "entity.WaitCondition": {
            "type": "object",
            "properties": {
                "on_timeout": {
                    "description": "\"timeout\" | \"skip\" | \"fail\"",
                    "type": "string"
                },
                "signal_name": {
                    "description": "Temporal Signal to wait for",
                    "type": "string"
                },
                "timeout": {
                    "description": "max wait duration",
                    "allOf": [
                        {
                            "$ref": "#/definitions/time.Duration"
                        }
                    ]
                }
            }
        },
        "eventing.IngestEvent": {
            "type": "object",
            "properties": {
                "event_id": {
                    "type": "string"
                },
                "event_type": {
                    "$ref": "#/definitions/entity.AgentOSEventType"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "run_id": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                },
                "source": {
                    "type": "string"
                },
                "tags": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "thread_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "trace_id": {
                    "type": "string"
                }
            }
        },
        "request.AgentOSControl": {
            "type": "object",
            "required": [
                "operation"
            ],
            "properties": {
                "operation": {
                    "$ref": "#/definitions/agentos.ControlOperation"
                }
            }
        },
        "request.AgentOSSignal": {
            "type": "object",
            "required": [
                "type"
            ],
            "properties": {
                "idempotency_key": {
                    "type": "string"
                },
                "payload": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "sent_at": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/agentos.SignalType"
                }
            }
        },
        "request.AgentOSStart": {
            "type": "object",
            "required": [
                "account_id",
                "backend",
                "run_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string"
                },
                "agent_id": {
                    "type": "string"
                },
                "backend": {
                    "$ref": "#/definitions/agentos.BackendRef"
                },
                "idempotency_key": {
                    "type": "string"
                },
                "input": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "metadata": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "model_ref": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "system_prompt": {
                    "type": "string"
                },
                "thread_id": {
                    "type": "string"
                },
                "user_message": {
                    "type": "string"
                }
            }
        },
        "request.Orchestrate": {
            "type": "object",
            "required": [
                "account_id",
                "run_id"
            ],
            "properties": {
                "account_id": {
                    "type": "string",
                    "example": "acct-001"
                },
                "continue_policy": {
                    "$ref": "#/definitions/entity.ContinuePolicy"
                },
                "max_depth": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string",
                    "example": "run-550e8400-e29b-41d4-a716-446655440000"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Step"
                    }
                },
                "system_prompt": {
                    "type": "string"
                },
                "team_spec": {
                    "$ref": "#/definitions/entity.TeamSpec"
                }
            }
        },
        "response.Error": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "message"
                }
            }
        },
        "response.RunStatus": {
            "type": "object",
            "properties": {
                "lifecycle_state": {
                    "type": "string"
                },
                "reason": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "step": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "integer"
                }
            }
        },
        "time.Duration": {
            "type": "integer",
            "format": "int64",
            "enum": [
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000,
                -9223372036854775808,
                9223372036854775807,
                1,
                1000,
                1000000,
                1000000000,
                60000000000,
                3600000000000
            ],
            "x-enum-varnames": [
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour",
                "minDuration",
                "maxDuration",
                "Nanosecond",
                "Microsecond",
                "Millisecond",
                "Second",
                "Minute",
                "Hour"
            ]
        },
        "v1.ingestAgentOSEventResponse": {
            "type": "object",
            "properties": {
                "duplicate": {
                    "type": "boolean"
                },
                "event_id": {
                    "type": "string"
                },
                "run_id": {
                    "type": "string"
                },
                "sequence": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "GoAgent API",
	Description:      "Agent Framework API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
