// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents
WHERE agent_id = $1
`

// DeleteAgent removes an agent and, by foreign key, its versions.
func (q *Queries) DeleteAgent(ctx context.Context, agentID string) error {
	_, err := q.db.Exec(ctx, deleteAgent, agentID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT agent_id, account_id, name, description, system_prompt, model_ref, config, current_version, is_default, created_at, updated_at
FROM agents
WHERE agent_id = $1
`

// GetAgent loads one agent by ID.
func (q *Queries) GetAgent(ctx context.Context, agentID string) (Agent, error) {
	row := q.db.QueryRow(ctx, getAgent, agentID)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ModelRef,
		&i.Config,
		&i.CurrentVersion,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentVersion = `-- name: GetAgentVersion :one
SELECT version_id, agent_id, version_name, system_prompt, model_ref, config, tool_bindings, change_description, created_at
FROM agent_versions
WHERE version_id = $1
`

// GetAgentVersion loads one version snapshot by ID.
func (q *Queries) GetAgentVersion(ctx context.Context, versionID string) (AgentVersion, error) {
	row := q.db.QueryRow(ctx, getAgentVersion, versionID)
	var i AgentVersion
	err := row.Scan(
		&i.VersionID,
		&i.AgentID,
		&i.VersionName,
		&i.SystemPrompt,
		&i.ModelRef,
		&i.Config,
		&i.ToolBindings,
		&i.ChangeDescription,
		&i.CreatedAt,
	)
	return i, err
}

const insertAgent = `-- name: InsertAgent :one

INSERT INTO agents (
    account_id,
    name,
    description,
    system_prompt,
    model_ref,
    config,
    current_version,
    is_default
) VALUES ($1,$2,$3,$4,$5,$6,$7,FALSE)
RETURNING agent_id, account_id, name, description, system_prompt, model_ref, config, current_version, is_default, created_at, updated_at
`

type InsertAgentParams struct {
	AccountID      string
	Name           string
	Description    string
	SystemPrompt   string
	ModelRef       string
	Config         []byte
	CurrentVersion string
}

// Agent definitions and their version snapshots.
// InsertAgent creates an agent definition. The ID is minted by the database,
// and a new agent is never the account default — promotion happens through a
// later update.
func (q *Queries) InsertAgent(ctx context.Context, arg InsertAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, insertAgent,
		arg.AccountID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ModelRef,
		arg.Config,
		arg.CurrentVersion,
	)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ModelRef,
		&i.Config,
		&i.CurrentVersion,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentVersion = `-- name: InsertAgentVersion :exec
INSERT INTO agent_versions (
    version_id,
    agent_id,
    version_name,
    system_prompt,
    model_ref,
    config,
    tool_bindings,
    change_description
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertAgentVersionParams struct {
	VersionID         string
	AgentID           string
	VersionName       string
	SystemPrompt      string
	ModelRef          string
	Config            []byte
	ToolBindings      []byte
	ChangeDescription string
}

// InsertAgentVersion stores one version snapshot.
func (q *Queries) InsertAgentVersion(ctx context.Context, arg InsertAgentVersionParams) error {
	_, err := q.db.Exec(ctx, insertAgentVersion,
		arg.VersionID,
		arg.AgentID,
		arg.VersionName,
		arg.SystemPrompt,
		arg.ModelRef,
		arg.Config,
		arg.ToolBindings,
		arg.ChangeDescription,
	)
	return err
}

const listAgentVersions = `-- name: ListAgentVersions :many
SELECT version_id, agent_id, version_name, system_prompt, model_ref, config, tool_bindings, change_description, created_at
FROM agent_versions
WHERE agent_id = $1
ORDER BY created_at DESC
`

// ListAgentVersions returns an agent's snapshots newest first.
func (q *Queries) ListAgentVersions(ctx context.Context, agentID string) ([]AgentVersion, error) {
	rows, err := q.db.Query(ctx, listAgentVersions, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentVersion
	for rows.Next() {
		var i AgentVersion
		if err := rows.Scan(
			&i.VersionID,
			&i.AgentID,
			&i.VersionName,
			&i.SystemPrompt,
			&i.ModelRef,
			&i.Config,
			&i.ToolBindings,
			&i.ChangeDescription,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByAccount = `-- name: ListAgentsByAccount :many
SELECT agent_id, account_id, name, description, system_prompt, model_ref, config, current_version, is_default, created_at, updated_at
FROM agents
WHERE account_id = $1
ORDER BY created_at DESC
`

// ListAgentsByAccount returns an account's agents newest first.
func (q *Queries) ListAgentsByAccount(ctx context.Context, accountID string) ([]Agent, error) {
	rows, err := q.db.Query(ctx, listAgentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.AgentID,
			&i.AccountID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ModelRef,
			&i.Config,
			&i.CurrentVersion,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents
SET name = COALESCE($1::varchar, name),
    description = COALESCE($2::text, description),
    system_prompt = COALESCE($3::text, system_prompt),
    model_ref = COALESCE($4::varchar, model_ref),
    config = COALESCE($5::jsonb, config),
    is_default = COALESCE($6::boolean, is_default),
    current_version = COALESCE($7::text, current_version)
WHERE agent_id = $8
RETURNING agent_id, account_id, name, description, system_prompt, model_ref, config, current_version, is_default, created_at, updated_at
`

type UpdateAgentParams struct {
	Name           pgtype.Text
	Description    pgtype.Text
	SystemPrompt   pgtype.Text
	ModelRef       pgtype.Text
	Config         []byte
	IsDefault      pgtype.Bool
	CurrentVersion pgtype.Text
	AgentID        string
}

// UpdateAgent applies a partial update: every NULL parameter keeps the stored
// value, so a caller only sends what changed.
func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ModelRef,
		arg.Config,
		arg.IsDefault,
		arg.CurrentVersion,
		arg.AgentID,
	)
	var i Agent
	err := row.Scan(
		&i.AgentID,
		&i.AccountID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ModelRef,
		&i.Config,
		&i.CurrentVersion,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
