// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact_schema_catalog.sql

package sqlcgen

import (
	"context"
)

const getArtifactSchemaByIdempotencyKey = `-- name: GetArtifactSchemaByIdempotencyKey :one
SELECT schema_decl_json
FROM agentos_artifact_schemas
WHERE idempotency_key = $1
`

// GetArtifactSchemaByIdempotencyKey loads a declaration by its registration
// key.
func (q *Queries) GetArtifactSchemaByIdempotencyKey(ctx context.Context, idempotencyKey string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getArtifactSchemaByIdempotencyKey, idempotencyKey)
	var schema_decl_json []byte
	err := row.Scan(&schema_decl_json)
	return schema_decl_json, err
}

const getArtifactSchemaByRef = `-- name: GetArtifactSchemaByRef :one
SELECT schema_decl_json
FROM agentos_artifact_schemas
WHERE schema_ref = $1
`

// GetArtifactSchemaByRef loads the full declaration by schema reference, so
// a replayed registration can compare declarations for equality.
func (q *Queries) GetArtifactSchemaByRef(ctx context.Context, schemaRef string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getArtifactSchemaByRef, schemaRef)
	var schema_decl_json []byte
	err := row.Scan(&schema_decl_json)
	return schema_decl_json, err
}

const getArtifactSchemaJSON = `-- name: GetArtifactSchemaJSON :one
SELECT schema_json
FROM agentos_artifact_schemas
WHERE schema_ref = $1
`

// GetArtifactSchemaJSON loads the raw JSON Schema registered under a
// reference — what artifact validation fetches.
func (q *Queries) GetArtifactSchemaJSON(ctx context.Context, schemaRef string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getArtifactSchemaJSON, schemaRef)
	var schema_json []byte
	err := row.Scan(&schema_json)
	return schema_json, err
}

const upsertArtifactSchema = `-- name: UpsertArtifactSchema :one

INSERT INTO agentos_artifact_schemas (
    schema_ref, description, schema_json, schema_decl_json, idempotency_key
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (schema_ref) DO UPDATE SET
    description = EXCLUDED.description,
    schema_json = EXCLUDED.schema_json,
    schema_decl_json = EXCLUDED.schema_decl_json,
    idempotency_key = EXCLUDED.idempotency_key,
    updated_at = NOW()
WHERE agentos_artifact_schemas.idempotency_key = EXCLUDED.idempotency_key
RETURNING schema_decl_json
`

type UpsertArtifactSchemaParams struct {
	SchemaRef      string
	Description    string
	SchemaJson     []byte
	SchemaDeclJson []byte
	IdempotencyKey string
}

// Artifact JSON Schema declarations. Two documents live per row: the raw
// JSON Schema (what validators fetch) and the full declaration (what
// registration replays compare against).
// UpsertArtifactSchema registers a declaration. The conditional DO UPDATE
// means a conflicting declaration under the same schema_ref updates nothing
// and returns no row — ErrNoRows to the caller, which turns it into an
// invalid-artifact error naming the conflict.
func (q *Queries) UpsertArtifactSchema(ctx context.Context, arg UpsertArtifactSchemaParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertArtifactSchema,
		arg.SchemaRef,
		arg.Description,
		arg.SchemaJson,
		arg.SchemaDeclJson,
		arg.IdempotencyKey,
	)
	var schema_decl_json []byte
	err := row.Scan(&schema_decl_json)
	return schema_decl_json, err
}
