// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: artifact.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT artifact_id,
       plan_id,
       COALESCE(node_id, '') AS node_id,
       COALESCE(run_id, '') AS run_id,
       name,
       kind,
       media_type,
       uri,
       size_bytes,
       digest,
       metadata_json,
       created_at
FROM artifacts
WHERE artifact_id = $1
`

type GetArtifactByIDRow struct {
	ArtifactID   string
	PlanID       string
	NodeID       string
	RunID        string
	Name         string
	Kind         string
	MediaType    string
	Uri          string
	SizeBytes    int64
	Digest       string
	MetadataJson []byte
	CreatedAt    time.Time
}

// GetArtifactByID loads one artifact's metadata by ID.
func (q *Queries) GetArtifactByID(ctx context.Context, artifactID string) (GetArtifactByIDRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, artifactID)
	var i GetArtifactByIDRow
	err := row.Scan(
		&i.ArtifactID,
		&i.PlanID,
		&i.NodeID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.MediaType,
		&i.Uri,
		&i.SizeBytes,
		&i.Digest,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByIdempotencyKey = `-- name: GetArtifactByIdempotencyKey :one

SELECT artifact_id,
       plan_id,
       COALESCE(node_id, '') AS node_id,
       COALESCE(run_id, '') AS run_id,
       name,
       kind,
       media_type,
       uri,
       size_bytes,
       digest,
       metadata_json,
       created_at
FROM artifacts
WHERE plan_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetArtifactByIdempotencyKeyParams struct {
	PlanID         string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetArtifactByIdempotencyKeyRow struct {
	ArtifactID   string
	PlanID       string
	NodeID       string
	RunID        string
	Name         string
	Kind         string
	MediaType    string
	Uri          string
	SizeBytes    int64
	Digest       string
	MetadataJson []byte
	CreatedAt    time.Time
}

// The node/run ownership join lives in queries/plan.sql as
// GetPlanNodeRunOwnership; the artifact publish path and the audit path
// check the same durable ownership with that one statement.
// GetArtifactByIdempotencyKey resolves a publish through its tenant-scoped
// idempotency key.
func (q *Queries) GetArtifactByIdempotencyKey(ctx context.Context, arg GetArtifactByIdempotencyKeyParams) (GetArtifactByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByIdempotencyKey,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var i GetArtifactByIdempotencyKeyRow
	err := row.Scan(
		&i.ArtifactID,
		&i.PlanID,
		&i.NodeID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.MediaType,
		&i.Uri,
		&i.SizeBytes,
		&i.Digest,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifactByScope = `-- name: GetArtifactByScope :one
SELECT artifact_id,
       plan_id,
       COALESCE(node_id, '') AS node_id,
       COALESCE(run_id, '') AS run_id,
       name,
       kind,
       media_type,
       uri,
       size_bytes,
       digest,
       metadata_json,
       created_at
FROM artifacts
WHERE plan_id = $1
  AND account_id = $2
  AND project_id = $3
  AND ($4::text = '' OR artifact_id = $4::text)
  AND ($5::text = '' OR node_id = $5::text)
  AND ($6::text = '' OR run_id = $6::text)
`

type GetArtifactByScopeParams struct {
	PlanID     string
	AccountID  string
	ProjectID  string
	ArtifactID string
	NodeID     string
	RunID      string
}

type GetArtifactByScopeRow struct {
	ArtifactID   string
	PlanID       string
	NodeID       string
	RunID        string
	Name         string
	Kind         string
	MediaType    string
	Uri          string
	SizeBytes    int64
	Digest       string
	MetadataJson []byte
	CreatedAt    time.Time
}

// GetArtifactByScope loads one artifact's metadata by plan scope. Optional
// filters are empty-string-means-absent.
func (q *Queries) GetArtifactByScope(ctx context.Context, arg GetArtifactByScopeParams) (GetArtifactByScopeRow, error) {
	row := q.db.QueryRow(ctx, getArtifactByScope,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.ArtifactID,
		arg.NodeID,
		arg.RunID,
	)
	var i GetArtifactByScopeRow
	err := row.Scan(
		&i.ArtifactID,
		&i.PlanID,
		&i.NodeID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.MediaType,
		&i.Uri,
		&i.SizeBytes,
		&i.Digest,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one

INSERT INTO artifacts (
    artifact_id,
    plan_id,
    account_id,
    project_id,
    node_id,
    run_id,
    name,
    kind,
    media_type,
    uri,
    size_bytes,
    digest,
    metadata_json,
    idempotency_key,
    created_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15)
ON CONFLICT DO NOTHING
RETURNING artifact_id,
          plan_id,
          COALESCE(node_id, '') AS node_id,
          COALESCE(run_id, '') AS run_id,
          name,
          kind,
          media_type,
          uri,
          size_bytes,
          digest,
          metadata_json,
          created_at
`

type InsertArtifactParams struct {
	ArtifactID     string
	PlanID         string
	AccountID      string
	ProjectID      string
	NodeID         pgtype.Text
	RunID          pgtype.Text
	Name           string
	Kind           string
	MediaType      string
	Uri            string
	SizeBytes      int64
	Digest         string
	MetadataJson   []byte
	IdempotencyKey string
	CreatedAt      time.Time
}

type InsertArtifactRow struct {
	ArtifactID   string
	PlanID       string
	NodeID       string
	RunID        string
	Name         string
	Kind         string
	MediaType    string
	Uri          string
	SizeBytes    int64
	Digest       string
	MetadataJson []byte
	CreatedAt    time.Time
}

// Plan artifacts: metadata rows in Postgres, payload bytes in a blob store;
// the URI column is the pointer between them.
// InsertArtifact publishes metadata. ON CONFLICT DO NOTHING plus RETURNING
// means no row comes back on any unique collision — the caller resolves it
// through the idempotency path, which distinguishes a replay from a
// conflicting artifact ID.
func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (InsertArtifactRow, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.ArtifactID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.NodeID,
		arg.RunID,
		arg.Name,
		arg.Kind,
		arg.MediaType,
		arg.Uri,
		arg.SizeBytes,
		arg.Digest,
		arg.MetadataJson,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i InsertArtifactRow
	err := row.Scan(
		&i.ArtifactID,
		&i.PlanID,
		&i.NodeID,
		&i.RunID,
		&i.Name,
		&i.Kind,
		&i.MediaType,
		&i.Uri,
		&i.SizeBytes,
		&i.Digest,
		&i.MetadataJson,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifacts = `-- name: ListArtifacts :many
SELECT artifact_id,
       plan_id,
       COALESCE(node_id, '') AS node_id,
       COALESCE(run_id, '') AS run_id,
       name,
       kind,
       media_type,
       uri,
       size_bytes,
       digest,
       metadata_json,
       created_at
FROM artifacts
WHERE plan_id = $1
  AND account_id = $2
  AND project_id = $3
  AND ($4::text = '' OR artifact_id = $4::text)
  AND ($5::text = '' OR node_id = $5::text)
  AND ($6::text = '' OR run_id = $6::text)
ORDER BY created_at ASC
LIMIT $7::bigint
`

type ListArtifactsParams struct {
	PlanID     string
	AccountID  string
	ProjectID  string
	ArtifactID string
	NodeID     string
	RunID      string
	RowLimit   pgtype.Int8
}

type ListArtifactsRow struct {
	ArtifactID   string
	PlanID       string
	NodeID       string
	RunID        string
	Name         string
	Kind         string
	MediaType    string
	Uri          string
	SizeBytes    int64
	Digest       string
	MetadataJson []byte
	CreatedAt    time.Time
}

// ListArtifacts pages a plan scope's artifacts oldest-first. Optional filters
// are empty-string-means-absent; a NULL row_limit is LIMIT ALL.
func (q *Queries) ListArtifacts(ctx context.Context, arg ListArtifactsParams) ([]ListArtifactsRow, error) {
	rows, err := q.db.Query(ctx, listArtifacts,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.ArtifactID,
		arg.NodeID,
		arg.RunID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListArtifactsRow
	for rows.Next() {
		var i ListArtifactsRow
		if err := rows.Scan(
			&i.ArtifactID,
			&i.PlanID,
			&i.NodeID,
			&i.RunID,
			&i.Name,
			&i.Kind,
			&i.MediaType,
			&i.Uri,
			&i.SizeBytes,
			&i.Digest,
			&i.MetadataJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
