// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlcgen

import (
	"context"
	"time"
)

const deductCreditBalance = `-- name: DeductCreditBalance :execrows
UPDATE credit_accounts
SET balance = balance - $2, version = version + 1, updated_at = NOW()
WHERE account_id = $1 AND balance >= $2
`

type DeductCreditBalanceParams struct {
	AccountID string
	Balance   float64
}

// DeductCreditBalance decrements the balance under its own guard: the WHERE
// clause is the sufficiency check, so zero affected rows means the balance
// was too low. The version bump keeps optimistic locking honest for readers.
func (q *Queries) DeductCreditBalance(ctx context.Context, arg DeductCreditBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deductCreditBalance, arg.AccountID, arg.Balance)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCreditAccount = `-- name: GetCreditAccount :one

SELECT account_id, balance, currency, version, updated_at
FROM credit_accounts
WHERE account_id = $1
`

type GetCreditAccountRow struct {
	AccountID string
	Balance   float64
	Currency  string
	Version   int64
	UpdatedAt time.Time
}

// Prepaid credit accounts and their ledger. Money moves in whole
// transactions: the balance changes and the ledger row is written by the same
// repo call, with the amount's sign carrying the direction.
// GetCreditAccount reads an account's balance. Absence is not an error: an
// account with no row has a zero balance.
func (q *Queries) GetCreditAccount(ctx context.Context, accountID string) (GetCreditAccountRow, error) {
	row := q.db.QueryRow(ctx, getCreditAccount, accountID)
	var i GetCreditAccountRow
	err := row.Scan(
		&i.AccountID,
		&i.Balance,
		&i.Currency,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCreditLedger = `-- name: InsertCreditLedger :one
INSERT INTO credit_ledger (account_id, amount, type, description)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, amount, type, description, created_at
`

type InsertCreditLedgerParams struct {
	AccountID   string
	Amount      float64
	Type        string
	Description string
}

// InsertCreditLedger records one money movement; the caller passes the amount
// with its sign (negative for usage, positive for top-up).
func (q *Queries) InsertCreditLedger(ctx context.Context, arg InsertCreditLedgerParams) (CreditLedger, error) {
	row := q.db.QueryRow(ctx, insertCreditLedger,
		arg.AccountID,
		arg.Amount,
		arg.Type,
		arg.Description,
	)
	var i CreditLedger
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.Type,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertUsageRecord = `-- name: InsertUsageRecord :exec
INSERT INTO usage_records (record_id, run_id, account_id, model_id, prompt_tokens, completion_tokens, total_tokens, cost)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertUsageRecordParams struct {
	RecordID         string
	RunID            string
	AccountID        string
	ModelID          string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	Cost             float64
}

// InsertUsageRecord persists one LLM usage record for audit and billing
// history.
func (q *Queries) InsertUsageRecord(ctx context.Context, arg InsertUsageRecordParams) error {
	_, err := q.db.Exec(ctx, insertUsageRecord,
		arg.RecordID,
		arg.RunID,
		arg.AccountID,
		arg.ModelID,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.TotalTokens,
		arg.Cost,
	)
	return err
}

const listCreditHistory = `-- name: ListCreditHistory :many
SELECT id, account_id, amount, type, description, created_at
FROM credit_ledger
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCreditHistoryParams struct {
	AccountID string
	Limit     int32
	Offset    int32
}

// ListCreditHistory pages an account's ledger newest-first.
func (q *Queries) ListCreditHistory(ctx context.Context, arg ListCreditHistoryParams) ([]CreditLedger, error) {
	rows, err := q.db.Query(ctx, listCreditHistory, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreditLedger
	for rows.Next() {
		var i CreditLedger
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.Type,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCreditAccount = `-- name: UpsertCreditAccount :exec
INSERT INTO credit_accounts (account_id, balance, currency)
VALUES ($1, $2, 'USD')
ON CONFLICT (account_id)
DO UPDATE SET balance = credit_accounts.balance + $2,
              version = credit_accounts.version + 1,
              updated_at = NOW()
`

type UpsertCreditAccountParams struct {
	AccountID string
	Balance   float64
}

// UpsertCreditAccount adds credits, creating the account on first top-up.
func (q *Queries) UpsertCreditAccount(ctx context.Context, arg UpsertCreditAccountParams) error {
	_, err := q.db.Exec(ctx, upsertCreditAccount, arg.AccountID, arg.Balance)
	return err
}
