// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capability_catalog.sql

package sqlcgen

import (
	"context"
)

const getCapabilityByIdempotencyKey = `-- name: GetCapabilityByIdempotencyKey :one
SELECT capability_json
FROM agentos_capabilities
WHERE idempotency_key = $1
`

// GetCapabilityByIdempotencyKey loads a declaration by its registration key,
// so a replayed registration finds the original.
func (q *Queries) GetCapabilityByIdempotencyKey(ctx context.Context, idempotencyKey string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCapabilityByIdempotencyKey, idempotencyKey)
	var capability_json []byte
	err := row.Scan(&capability_json)
	return capability_json, err
}

const getCapabilityByName = `-- name: GetCapabilityByName :one
SELECT capability_json
FROM agentos_capabilities
WHERE backend_kind = $1 AND backend_name = $2 AND capability_name = $3
`

type GetCapabilityByNameParams struct {
	BackendKind    string
	BackendName    string
	CapabilityName string
}

// GetCapabilityByName loads the declaration registered for a backend and
// capability name.
func (q *Queries) GetCapabilityByName(ctx context.Context, arg GetCapabilityByNameParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCapabilityByName, arg.BackendKind, arg.BackendName, arg.CapabilityName)
	var capability_json []byte
	err := row.Scan(&capability_json)
	return capability_json, err
}

const upsertCapability = `-- name: UpsertCapability :one

INSERT INTO agentos_capabilities (
    backend_kind, backend_name, capability_name, description,
    capability_json, idempotency_key
)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (backend_kind, backend_name, capability_name) DO UPDATE SET
    description = EXCLUDED.description,
    capability_json = EXCLUDED.capability_json,
    idempotency_key = EXCLUDED.idempotency_key,
    updated_at = NOW()
WHERE agentos_capabilities.idempotency_key = EXCLUDED.idempotency_key
RETURNING capability_json
`

type UpsertCapabilityParams struct {
	BackendKind    string
	BackendName    string
	CapabilityName string
	Description    string
	CapabilityJson []byte
	IdempotencyKey string
}

// Backend capability declarations. The declaration itself is the JSON
// document; the typed columns exist for conflict detection and lookups.
// UpsertCapability registers a declaration. The conditional DO UPDATE means a
// conflicting declaration (same backend and name, different idempotency key)
// updates nothing and returns no row — ErrNoRows to the caller, which turns
// it into an invalid-plan error naming the conflict.
func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, upsertCapability,
		arg.BackendKind,
		arg.BackendName,
		arg.CapabilityName,
		arg.Description,
		arg.CapabilityJson,
		arg.IdempotencyKey,
	)
	var capability_json []byte
	err := row.Scan(&capability_json)
	return capability_json, err
}
