// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message.sql

package sqlcgen

import (
	"context"
)

const getArchiveByRef = `-- name: GetArchiveByRef :one
SELECT run_id, payload_type, content
FROM archives
WHERE id = $1
`

type GetArchiveByRefRow struct {
	RunID       string
	PayloadType string
	Content     []byte
}

// GetArchiveByRef reads one archival payload by its ref.
func (q *Queries) GetArchiveByRef(ctx context.Context, id int64) (GetArchiveByRefRow, error) {
	row := q.db.QueryRow(ctx, getArchiveByRef, id)
	var i GetArchiveByRefRow
	err := row.Scan(&i.RunID, &i.PayloadType, &i.Content)
	return i, err
}

const getMessageByRef = `-- name: GetMessageByRef :one
SELECT run_id, role, content, tool_call_id
FROM messages
WHERE id = $1
`

type GetMessageByRefRow struct {
	RunID      string
	Role       string
	Content    string
	ToolCallID string
}

// GetMessageByRef reads one chat message by its ref.
func (q *Queries) GetMessageByRef(ctx context.Context, id int64) (GetMessageByRefRow, error) {
	row := q.db.QueryRow(ctx, getMessageByRef, id)
	var i GetMessageByRefRow
	err := row.Scan(
		&i.RunID,
		&i.Role,
		&i.Content,
		&i.ToolCallID,
	)
	return i, err
}

const getToolResultByRef = `-- name: GetToolResultByRef :one
SELECT run_id, tool_call_id, tool_name, result_json
FROM tool_results
WHERE id = $1
`

type GetToolResultByRefRow struct {
	RunID      string
	ToolCallID string
	ToolName   string
	ResultJson string
}

// GetToolResultByRef reads one tool output by its ref.
func (q *Queries) GetToolResultByRef(ctx context.Context, id int64) (GetToolResultByRefRow, error) {
	row := q.db.QueryRow(ctx, getToolResultByRef, id)
	var i GetToolResultByRefRow
	err := row.Scan(
		&i.RunID,
		&i.ToolCallID,
		&i.ToolName,
		&i.ResultJson,
	)
	return i, err
}

const insertArchive = `-- name: InsertArchive :one
INSERT INTO archives (run_id, payload_type, content)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertArchiveParams struct {
	RunID       string
	PayloadType string
	Content     []byte
}

// InsertArchive stores one opaque archival payload and returns its ref.
func (q *Queries) InsertArchive(ctx context.Context, arg InsertArchiveParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertArchive, arg.RunID, arg.PayloadType, arg.Content)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertMessage = `-- name: InsertMessage :one

INSERT INTO messages (run_id, role, content, tool_call_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertMessageParams struct {
	RunID      string
	Role       string
	Content    string
	ToolCallID string
}

// Run-scoped warm and cold state: chat messages, normalized tool results,
// and opaque archives. Ref IDs handed out by the inserts are the BIGSERIAL
// primary keys formatted as decimal strings.
// InsertMessage stores one chat message and returns its ref.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.RunID,
		arg.Role,
		arg.Content,
		arg.ToolCallID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertToolResult = `-- name: InsertToolResult :one
INSERT INTO tool_results (run_id, tool_call_id, tool_name, result_json)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type InsertToolResultParams struct {
	RunID      string
	ToolCallID string
	ToolName   string
	ResultJson string
}

// InsertToolResult stores one normalized tool output and returns its ref.
func (q *Queries) InsertToolResult(ctx context.Context, arg InsertToolResultParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertToolResult,
		arg.RunID,
		arg.ToolCallID,
		arg.ToolName,
		arg.ResultJson,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listMessagesByRun = `-- name: ListMessagesByRun :many
SELECT run_id, role, content, tool_call_id
FROM messages
WHERE run_id = $1
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ListMessagesByRunParams struct {
	RunID  string
	Limit  int32
	Offset int32
}

type ListMessagesByRunRow struct {
	RunID      string
	Role       string
	Content    string
	ToolCallID string
}

// ListMessagesByRun pages a run's chat messages oldest-first; the serial id
// is the write order.
func (q *Queries) ListMessagesByRun(ctx context.Context, arg ListMessagesByRunParams) ([]ListMessagesByRunRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByRun, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagesByRunRow
	for rows.Next() {
		var i ListMessagesByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.Role,
			&i.Content,
			&i.ToolCallID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolResultsByRun = `-- name: ListToolResultsByRun :many
SELECT run_id, tool_call_id, tool_name, result_json
FROM tool_results
WHERE run_id = $1
ORDER BY id ASC
LIMIT $2 OFFSET $3
`

type ListToolResultsByRunParams struct {
	RunID  string
	Limit  int32
	Offset int32
}

type ListToolResultsByRunRow struct {
	RunID      string
	ToolCallID string
	ToolName   string
	ResultJson string
}

// ListToolResultsByRun pages a run's tool outputs oldest-first.
func (q *Queries) ListToolResultsByRun(ctx context.Context, arg ListToolResultsByRunParams) ([]ListToolResultsByRunRow, error) {
	rows, err := q.db.Query(ctx, listToolResultsByRun, arg.RunID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListToolResultsByRunRow
	for rows.Next() {
		var i ListToolResultsByRunRow
		if err := rows.Scan(
			&i.RunID,
			&i.ToolCallID,
			&i.ToolName,
			&i.ResultJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
