// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Agent struct {
	AgentID        string
	AccountID      string
	Name           string
	Description    string
	SystemPrompt   string
	ModelRef       string
	Config         []byte
	CurrentVersion string
	IsDefault      bool
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AgentVersion struct {
	VersionID         string
	AgentID           string
	VersionName       string
	SystemPrompt      string
	ModelRef          string
	Config            []byte
	ToolBindings      []byte
	ChangeDescription string
	CreatedAt         time.Time
}

type AgentosArtifactSchema struct {
	SchemaRef      string
	Description    string
	SchemaJson     []byte
	SchemaDeclJson []byte
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AgentosCapability struct {
	BackendKind    string
	BackendName    string
	CapabilityName string
	Description    string
	CapabilityJson []byte
	IdempotencyKey string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type AgentosConversationDeferredProjection struct {
	ThreadID  string
	Sequence  int64
	RunID     string
	EventType string
	Attempts  int32
	CreatedAt time.Time
}

type AgentosConversationEvent struct {
	ThreadID       string
	Sequence       int64
	EventID        string
	RunID          string
	ProcessID      string
	SourceEventID  string
	SourceSequence int64
	EventType      string
	OccurredAt     time.Time
	Payload        []byte
}

type AgentosConversationEventOutbox struct {
	ThreadID    string
	Sequence    int64
	Attempts    int32
	AvailableAt time.Time
	LastError   string
	CreatedAt   time.Time
}

type AgentosConversationRun struct {
	RunID              string
	ThreadID           string
	ProcessID          string
	AccountID          string
	ProjectID          string
	Status             string
	Outcome            string
	Interrupt          []byte
	ErrorCode          string
	ErrorMessage       string
	IdempotencyKey     string
	ResumeInterruptID  string
	Metadata           []byte
	LastSourceSequence int64
	CreatedAt          time.Time
	StartedAt          pgtype.Timestamptz
	CompletedAt        pgtype.Timestamptz
	LastActivityAt     time.Time
}

type AgentosMessage struct {
	MessageID   string
	ThreadID    string
	RunID       string
	ProcessID   string
	Role        string
	Content     string
	Status      string
	Attachments []byte
	Metadata    []byte
	CreatedAt   time.Time
	CompletedAt pgtype.Timestamptz
}

type AgentosRunEvent struct {
	RunID      string
	Sequence   int64
	EventID    string
	EventType  string
	ThreadID   string
	ProcessID  string
	Source     string
	OccurredAt time.Time
	Payload    []byte
	CreatedAt  time.Time
}

type AgentosRunEventOutbox struct {
	RunID       string
	Sequence    int64
	Attempts    int32
	AvailableAt time.Time
	LastError   string
	CreatedAt   time.Time
}

type AgentosThread struct {
	ThreadID     string
	AccountID    string
	ProjectID    string
	NextSequence int64
	Metadata     []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AgentosToolIdempotency struct {
	Key        string
	RunID      string
	ToolCallID string
	ToolName   string
	Output     []byte
	Attempts   int32
	CreatedAt  time.Time
}

type Artifact struct {
	ArtifactID     string
	PlanID         string
	NodeID         pgtype.Text
	RunID          pgtype.Text
	Name           string
	Kind           string
	MediaType      string
	Uri            string
	SizeBytes      int64
	Digest         string
	MetadataJson   []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	IdempotencyKey string
	AccountID      string
	ProjectID      string
}

type AuditLog struct {
	AuditID        string
	PlanID         string
	RunID          pgtype.Text
	NodeID         pgtype.Text
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	CreatedAt      time.Time
	AccountID      string
	ProjectID      string
	PrevHash       string
	RowHash        string
}

type CreditAccount struct {
	AccountID string
	Balance   float64
	Currency  string
	Version   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CreditLedger struct {
	ID          int64
	AccountID   string
	Amount      float64
	Type        string
	Description string
	CreatedAt   time.Time
}

type GovernedAction struct {
	ActionID       string
	AccountID      string
	ProjectID      string
	ProcessID      string
	ResourceKind   string
	ResourceID     string
	Kind           string
	LifecycleState string
	IdempotencyKey string
	SpecJson       []byte
	StatusJson     []byte
	RequestedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type GovernedActionStatusUpdate struct {
	ActionID       string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	StatusJson     []byte
	CreatedAt      time.Time
}

type History struct {
	ID          int32
	Source      pgtype.Text
	Destination pgtype.Text
	Original    pgtype.Text
	Translation pgtype.Text
}

type LedgerEntry struct {
	EntryID        string
	AccountID      string
	ProjectID      string
	ProcessID      string
	ResourceKind   string
	ResourceID     string
	Kind           string
	Sequence       int64
	IdempotencyKey string
	EntryJson      []byte
	OccurredAt     pgtype.Timestamptz
	CreatedAt      time.Time
}

type Plan struct {
	PlanID         string
	ThreadID       string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	LifecycleState string
	Reason         string
	SpecJson       []byte
	StatusJson     []byte
	EventSequence  int64
	RequestedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PlanCommand struct {
	CommandID      string
	PlanID         string
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	Status         string
	FailureReason  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	AccountID      string
	ProjectID      string
}

type PlanEvent struct {
	EventID                  string
	PlanID                   string
	NodeID                   string
	RunID                    string
	EventType                string
	Sequence                 int64
	IdempotencyKey           string
	PayloadJson              []byte
	EventJson                []byte
	Timestamp                time.Time
	CreatedAt                time.Time
	AccountID                string
	ProjectID                string
	TransitionSnapshotDigest string
	TransitionSnapshotJson   []byte
}

type PlanMetricCheckpoint struct {
	ExporterID     string
	PlanID         string
	AccountID      string
	ProjectID      string
	Sequence       int64
	ProjectionJson []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PlanMetricSample struct {
	MetricName      string
	PlanID          string
	AccountID       string
	ProjectID       string
	NodeID          string
	RunID           string
	EventID         string
	Sequence        int64
	Value           float64
	Unit            string
	LabelsJson      []byte
	SampleTimestamp time.Time
	CreatedAt       time.Time
}

type PlanNode struct {
	PlanID         string
	NodeID         string
	RunID          string
	BackendKind    string
	BackendName    string
	Capability     string
	LifecycleState string
	Attempts       int32
	Reason         string
	StatusJson     []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Process struct {
	ProcessID      string
	Kind           string
	AccountID      string
	ProjectID      string
	ResourceKind   string
	ResourceID     string
	IdempotencyKey string
	LifecycleState string
	Reason         string
	SpecJson       []byte
	StatusJson     []byte
	EventSequence  int64
	RequestedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ProcessEvent struct {
	EventID        string
	ProcessID      string
	AccountID      string
	ProjectID      string
	ResourceKind   string
	ResourceID     string
	EventType      string
	Sequence       int64
	IdempotencyKey string
	PayloadJson    []byte
	EventJson      []byte
	Timestamp      time.Time
	CreatedAt      time.Time
}

type ProcessStatusUpdate struct {
	ProcessID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	StatusJson     []byte
	CreatedAt      time.Time
}

type RunBackendIndex struct {
	RunID          string
	PlanID         pgtype.Text
	NodeID         pgtype.Text
	ThreadID       string
	AccountID      string
	ProjectID      string
	BackendKind    string
	BackendName    string
	IdempotencyKey string
	LifecycleState string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type UsageRecord struct {
	ID               int64
	RecordID         string
	RunID            string
	AccountID        string
	ModelID          string
	PromptTokens     int32
	CompletionTokens int32
	TotalTokens      int32
	Cost             float64
	CreatedAt        time.Time
}

type WorkflowTemplate struct {
	ID           string
	AccountID    string
	Name         string
	Description  string
	TeamSpec     []byte
	SystemPrompt string
	DefaultModel string
	Tags         []string
	IsEnabled    bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Workset struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	ProcessID      string
	ResourceKind   string
	ResourceID     string
	Kind           string
	LifecycleState string
	IdempotencyKey string
	SpecJson       []byte
	StatusJson     []byte
	RequestedAt    pgtype.Timestamptz
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type WorksetChunkResult struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	ChunkID        string
	IdempotencyKey string
	ResultJson     []byte
	StatusJson     []byte
	CreatedAt      time.Time
}

type WorksetStatusUpdate struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	StatusJson     []byte
	CreatedAt      time.Time
}
