// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advancePlanEventSequence = `-- name: AdvancePlanEventSequence :exec
UPDATE plans
SET event_sequence = $2
WHERE plan_id = $1
`

type AdvancePlanEventSequenceParams struct {
	PlanID        string
	EventSequence int64
}

// AdvancePlanEventSequence publishes the sequence number the locked append
// handed out.
func (q *Queries) AdvancePlanEventSequence(ctx context.Context, arg AdvancePlanEventSequenceParams) error {
	_, err := q.db.Exec(ctx, advancePlanEventSequence, arg.PlanID, arg.EventSequence)
	return err
}

const deletePlanNodesByPlanID = `-- name: DeletePlanNodesByPlanID :exec
DELETE FROM plan_nodes
WHERE plan_id = $1
`

// DeletePlanNodesByPlanID removes every node of a plan; the caller uses it
// when a snapshot carries no nodes.
func (q *Queries) DeletePlanNodesByPlanID(ctx context.Context, planID string) error {
	_, err := q.db.Exec(ctx, deletePlanNodesByPlanID, planID)
	return err
}

const deletePlanNodesNotIn = `-- name: DeletePlanNodesNotIn :exec
DELETE FROM plan_nodes
WHERE plan_id = $1 AND NOT (node_id = ANY($2::text[]))
`

type DeletePlanNodesNotInParams struct {
	PlanID  string
	NodeIds []string
}

// DeletePlanNodesNotIn removes the nodes a snapshot dropped, keeping the
// ones it still carries.
func (q *Queries) DeletePlanNodesNotIn(ctx context.Context, arg DeletePlanNodesNotInParams) error {
	_, err := q.db.Exec(ctx, deletePlanNodesNotIn, arg.PlanID, arg.NodeIds)
	return err
}

const getAuditRecord = `-- name: GetAuditRecord :one

SELECT audit_id,
       plan_id,
       account_id,
       project_id,
       COALESCE(run_id, '') AS run_id,
       COALESCE(node_id, '') AS node_id,
       actor_id,
       action,
       idempotency_key,
       payload_json,
       created_at
FROM audit_logs
WHERE plan_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetAuditRecordParams struct {
	PlanID         string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetAuditRecordRow struct {
	AuditID        string
	PlanID         string
	AccountID      string
	ProjectID      string
	RunID          string
	NodeID         string
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	CreatedAt      time.Time
}

// Plan audit logs: one append-only record per control-plane action, identified
// inside a tenant by its plan and idempotency key. run_id and node_id are
// nullable — a record either names a durable node/run pair or names neither —
// and read back as empty strings.
// GetAuditRecord loads one audit record by its tenant-scoped idempotency key.
func (q *Queries) GetAuditRecord(ctx context.Context, arg GetAuditRecordParams) (GetAuditRecordRow, error) {
	row := q.db.QueryRow(ctx, getAuditRecord,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var i GetAuditRecordRow
	err := row.Scan(
		&i.AuditID,
		&i.PlanID,
		&i.AccountID,
		&i.ProjectID,
		&i.RunID,
		&i.NodeID,
		&i.ActorID,
		&i.Action,
		&i.IdempotencyKey,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getPlanByIdempotencyKey = `-- name: GetPlanByIdempotencyKey :one
SELECT spec_json, status_json
FROM plans
WHERE account_id = $1 AND project_id = $2 AND idempotency_key = $3
`

type GetPlanByIdempotencyKeyParams struct {
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetPlanByIdempotencyKeyRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetPlanByIdempotencyKey resolves a plan through its tenant-scoped
// idempotency key, so a replayed create finds the original.
func (q *Queries) GetPlanByIdempotencyKey(ctx context.Context, arg GetPlanByIdempotencyKeyParams) (GetPlanByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPlanByIdempotencyKey, arg.AccountID, arg.ProjectID, arg.IdempotencyKey)
	var i GetPlanByIdempotencyKeyRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getPlanCommand = `-- name: GetPlanCommand :one
SELECT command_id,
       plan_id,
       actor_id,
       action,
       idempotency_key,
       payload_json,
       status,
       failure_reason,
       created_at,
       updated_at,
       account_id,
       project_id
FROM plan_commands
WHERE plan_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetPlanCommandParams struct {
	PlanID         string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

// GetPlanCommand loads one outbox command by its tenant-scoped idempotency
// key.
func (q *Queries) GetPlanCommand(ctx context.Context, arg GetPlanCommandParams) (PlanCommand, error) {
	row := q.db.QueryRow(ctx, getPlanCommand,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var i PlanCommand
	err := row.Scan(
		&i.CommandID,
		&i.PlanID,
		&i.ActorID,
		&i.Action,
		&i.IdempotencyKey,
		&i.PayloadJson,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.ProjectID,
	)
	return i, err
}

const getPlanEventByIdempotencyKey = `-- name: GetPlanEventByIdempotencyKey :one
SELECT event_json, transition_snapshot_digest
FROM plan_events
WHERE account_id = $1 AND project_id = $2 AND plan_id = $3 AND idempotency_key = $4
`

type GetPlanEventByIdempotencyKeyParams struct {
	AccountID      string
	ProjectID      string
	PlanID         string
	IdempotencyKey string
}

type GetPlanEventByIdempotencyKeyRow struct {
	EventJson                []byte
	TransitionSnapshotDigest string
}

// GetPlanEventByIdempotencyKey resolves an event through its tenant-scoped
// idempotency key, so a replayed append finds the original.
func (q *Queries) GetPlanEventByIdempotencyKey(ctx context.Context, arg GetPlanEventByIdempotencyKeyParams) (GetPlanEventByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getPlanEventByIdempotencyKey,
		arg.AccountID,
		arg.ProjectID,
		arg.PlanID,
		arg.IdempotencyKey,
	)
	var i GetPlanEventByIdempotencyKeyRow
	err := row.Scan(&i.EventJson, &i.TransitionSnapshotDigest)
	return i, err
}

const getPlanMetricCheckpoint = `-- name: GetPlanMetricCheckpoint :one

SELECT exporter_id,
       plan_id,
       account_id,
       project_id,
       sequence,
       projection_json,
       updated_at
FROM plan_metric_checkpoints
WHERE exporter_id = $1 AND plan_id = $2 AND account_id = $3 AND project_id = $4
`

type GetPlanMetricCheckpointParams struct {
	ExporterID string
	PlanID     string
	AccountID  string
	ProjectID  string
}

type GetPlanMetricCheckpointRow struct {
	ExporterID     string
	PlanID         string
	AccountID      string
	ProjectID      string
	Sequence       int64
	ProjectionJson []byte
	UpdatedAt      time.Time
}

// Plan metrics: per-exporter checkpoints a sequence can only move forward,
// and append-only samples keyed by their full identity.
// GetPlanMetricCheckpoint loads the checkpoint one exporter stored for a plan.
func (q *Queries) GetPlanMetricCheckpoint(ctx context.Context, arg GetPlanMetricCheckpointParams) (GetPlanMetricCheckpointRow, error) {
	row := q.db.QueryRow(ctx, getPlanMetricCheckpoint,
		arg.ExporterID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
	)
	var i GetPlanMetricCheckpointRow
	err := row.Scan(
		&i.ExporterID,
		&i.PlanID,
		&i.AccountID,
		&i.ProjectID,
		&i.Sequence,
		&i.ProjectionJson,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlanMetricSampleByKey = `-- name: GetPlanMetricSampleByKey :one
SELECT metric_name,
       plan_id,
       account_id,
       project_id,
       node_id,
       run_id,
       event_id,
       sequence,
       value,
       unit,
       labels_json,
       sample_timestamp
FROM plan_metric_samples
WHERE metric_name = $1
  AND plan_id = $2
  AND node_id = $3
  AND run_id = $4
  AND event_id = $5
  AND sequence = $6
`

type GetPlanMetricSampleByKeyParams struct {
	MetricName string
	PlanID     string
	NodeID     string
	RunID      string
	EventID    string
	Sequence   int64
}

type GetPlanMetricSampleByKeyRow struct {
	MetricName      string
	PlanID          string
	AccountID       string
	ProjectID       string
	NodeID          string
	RunID           string
	EventID         string
	Sequence        int64
	Value           float64
	Unit            string
	LabelsJson      []byte
	SampleTimestamp time.Time
}

// GetPlanMetricSampleByKey resolves one metric sample through its full
// identity, so a DO NOTHING collision can find what was stored.
func (q *Queries) GetPlanMetricSampleByKey(ctx context.Context, arg GetPlanMetricSampleByKeyParams) (GetPlanMetricSampleByKeyRow, error) {
	row := q.db.QueryRow(ctx, getPlanMetricSampleByKey,
		arg.MetricName,
		arg.PlanID,
		arg.NodeID,
		arg.RunID,
		arg.EventID,
		arg.Sequence,
	)
	var i GetPlanMetricSampleByKeyRow
	err := row.Scan(
		&i.MetricName,
		&i.PlanID,
		&i.AccountID,
		&i.ProjectID,
		&i.NodeID,
		&i.RunID,
		&i.EventID,
		&i.Sequence,
		&i.Value,
		&i.Unit,
		&i.LabelsJson,
		&i.SampleTimestamp,
	)
	return i, err
}

const getPlanNodeRunOwnership = `-- name: GetPlanNodeRunOwnership :one
SELECT n.run_id AS node_run_id, r.run_id AS owned_run_id
FROM plan_nodes n
LEFT JOIN run_backend_index r
    ON r.plan_id = n.plan_id
   AND r.node_id = n.node_id
   AND r.run_id = $3
   AND r.account_id = $4
   AND r.project_id = $5
WHERE n.plan_id = $1
  AND n.node_id = $2
`

type GetPlanNodeRunOwnershipParams struct {
	PlanID    string
	NodeID    string
	RunID     string
	AccountID string
	ProjectID string
}

type GetPlanNodeRunOwnershipRow struct {
	NodeRunID  string
	OwnedRunID pgtype.Text
}

// ValidateAuditOwnership reads a plan node's durable run together with the
// run's registration in one join: the LEFT JOIN keeps the read working when
// the run has no ownership row, which is itself the "run not registered" case.
func (q *Queries) GetPlanNodeRunOwnership(ctx context.Context, arg GetPlanNodeRunOwnershipParams) (GetPlanNodeRunOwnershipRow, error) {
	row := q.db.QueryRow(ctx, getPlanNodeRunOwnership,
		arg.PlanID,
		arg.NodeID,
		arg.RunID,
		arg.AccountID,
		arg.ProjectID,
	)
	var i GetPlanNodeRunOwnershipRow
	err := row.Scan(&i.NodeRunID, &i.OwnedRunID)
	return i, err
}

const getPlanSpecForUpdate = `-- name: GetPlanSpecForUpdate :one
SELECT spec_json
FROM plans
WHERE plan_id = $1
FOR UPDATE
`

// GetPlanSpecForUpdate takes the plan row lock a state save orders itself
// against and returns the stored spec for identity validation.
func (q *Queries) GetPlanSpecForUpdate(ctx context.Context, planID string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getPlanSpecForUpdate, planID)
	var spec_json []byte
	err := row.Scan(&spec_json)
	return spec_json, err
}

const getPlanStateByID = `-- name: GetPlanStateByID :one
SELECT spec_json, status_json
FROM plans
WHERE plan_id = $1
`

type GetPlanStateByIDRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetPlanStateByID loads a plan's spec and status documents by id.
func (q *Queries) GetPlanStateByID(ctx context.Context, planID string) (GetPlanStateByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlanStateByID, planID)
	var i GetPlanStateByIDRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getPlanStateByRef = `-- name: GetPlanStateByRef :one
SELECT spec_json, status_json
FROM plans
WHERE plan_id = $1 AND account_id = $2 AND project_id = $3
`

type GetPlanStateByRefParams struct {
	PlanID    string
	AccountID string
	ProjectID string
}

type GetPlanStateByRefRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetPlanStateByRef loads a plan's spec and status documents by
// tenant-scoped reference.
func (q *Queries) GetPlanStateByRef(ctx context.Context, arg GetPlanStateByRefParams) (GetPlanStateByRefRow, error) {
	row := q.db.QueryRow(ctx, getPlanStateByRef, arg.PlanID, arg.AccountID, arg.ProjectID)
	var i GetPlanStateByRefRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getPlanTenantScope = `-- name: GetPlanTenantScope :one
SELECT account_id, project_id
FROM plans
WHERE plan_id = $1
`

type GetPlanTenantScopeRow struct {
	AccountID string
	ProjectID string
}

// GetPlanTenantScope resolves the tenant a plan belongs to; a missing plan
// is the caller's not-found case.
func (q *Queries) GetPlanTenantScope(ctx context.Context, planID string) (GetPlanTenantScopeRow, error) {
	row := q.db.QueryRow(ctx, getPlanTenantScope, planID)
	var i GetPlanTenantScopeRow
	err := row.Scan(&i.AccountID, &i.ProjectID)
	return i, err
}

const insertAuditRecord = `-- name: InsertAuditRecord :exec
INSERT INTO audit_logs (
    audit_id,
    plan_id,
    account_id,
    project_id,
    run_id,
    node_id,
    actor_id,
    action,
    idempotency_key,
    payload_json,
    created_at,
    prev_hash,
    row_hash
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertAuditRecordParams struct {
	AuditID        string
	PlanID         string
	AccountID      string
	ProjectID      string
	RunID          pgtype.Text
	NodeID         pgtype.Text
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	CreatedAt      time.Time
	PrevHash       string
	RowHash        string
}

// InsertAuditRecord appends one audit record. A unique collision is the
// caller's replay case, resolved through the idempotency key against the
// stored record.
func (q *Queries) InsertAuditRecord(ctx context.Context, arg InsertAuditRecordParams) error {
	_, err := q.db.Exec(ctx, insertAuditRecord,
		arg.AuditID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.RunID,
		arg.NodeID,
		arg.ActorID,
		arg.Action,
		arg.IdempotencyKey,
		arg.PayloadJson,
		arg.CreatedAt,
		arg.PrevHash,
		arg.RowHash,
	)
	return err
}

const insertPlanCommand = `-- name: InsertPlanCommand :exec

INSERT INTO plan_commands (
    command_id,
    plan_id,
    account_id,
    project_id,
    actor_id,
    action,
    idempotency_key,
    payload_json,
    status,
    failure_reason,
    created_at,
    updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertPlanCommandParams struct {
	CommandID      string
	PlanID         string
	AccountID      string
	ProjectID      string
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	Status         string
	FailureReason  string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Plan commands: the durable control-plane outbox. A command enters pending,
// and delivered is terminal.
// InsertPlanCommand appends one outbox command. A unique collision is the
// caller's replay case, resolved through the idempotency key against the
// stored command.
func (q *Queries) InsertPlanCommand(ctx context.Context, arg InsertPlanCommandParams) error {
	_, err := q.db.Exec(ctx, insertPlanCommand,
		arg.CommandID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.ActorID,
		arg.Action,
		arg.IdempotencyKey,
		arg.PayloadJson,
		arg.Status,
		arg.FailureReason,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertPlanEvent = `-- name: InsertPlanEvent :one
INSERT INTO plan_events (
    event_id,
    plan_id,
    account_id,
    project_id,
    node_id,
    run_id,
    event_type,
    sequence,
    idempotency_key,
    transition_snapshot_digest,
    transition_snapshot_json,
    payload_json,
    event_json,
    timestamp
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)
RETURNING event_json
`

type InsertPlanEventParams struct {
	EventID                  string
	PlanID                   string
	AccountID                string
	ProjectID                string
	NodeID                   string
	RunID                    string
	EventType                string
	Sequence                 int64
	IdempotencyKey           string
	TransitionSnapshotDigest string
	TransitionSnapshotJson   []byte
	PayloadJson              []byte
	EventJson                []byte
	Timestamp                time.Time
}

// InsertPlanEvent appends one durable plan event and returns the stored
// event document. A NULL transition_snapshot_json is an append outside a
// transition.
func (q *Queries) InsertPlanEvent(ctx context.Context, arg InsertPlanEventParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, insertPlanEvent,
		arg.EventID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.NodeID,
		arg.RunID,
		arg.EventType,
		arg.Sequence,
		arg.IdempotencyKey,
		arg.TransitionSnapshotDigest,
		arg.TransitionSnapshotJson,
		arg.PayloadJson,
		arg.EventJson,
		arg.Timestamp,
	)
	var event_json []byte
	err := row.Scan(&event_json)
	return event_json, err
}

const latestAuditRowHash = `-- name: LatestAuditRowHash :one
SELECT COALESCE((
    SELECT row_hash FROM audit_logs
    WHERE account_id = $1 AND project_id = $2 AND row_hash <> ''
    ORDER BY created_at DESC, audit_id DESC
    LIMIT 1
), '')::text AS prev_hash
`

type LatestAuditRowHashParams struct {
	AccountID string
	ProjectID string
}

// LatestAuditRowHash returns the tenant's most recent chain hash, which is the
// predecessor of the next row. Empty when the tenant has no chained row yet.
func (q *Queries) LatestAuditRowHash(ctx context.Context, arg LatestAuditRowHashParams) (string, error) {
	row := q.db.QueryRow(ctx, latestAuditRowHash, arg.AccountID, arg.ProjectID)
	var prev_hash string
	err := row.Scan(&prev_hash)
	return prev_hash, err
}

const listAuditChain = `-- name: ListAuditChain :many
SELECT audit_id,
       plan_id,
       account_id,
       project_id,
       COALESCE(run_id, '')::text    AS run_id,
       COALESCE(node_id, '')::text   AS node_id,
       actor_id,
       action,
       idempotency_key,
       payload_json,
       created_at,
       prev_hash,
       row_hash
FROM audit_logs
WHERE account_id = $1 AND project_id = $2
ORDER BY created_at, audit_id
`

type ListAuditChainParams struct {
	AccountID string
	ProjectID string
}

type ListAuditChainRow struct {
	AuditID        string
	PlanID         string
	AccountID      string
	ProjectID      string
	RunID          string
	NodeID         string
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	CreatedAt      time.Time
	PrevHash       string
	RowHash        string
}

// ListAuditChain walks a tenant's audit rows in chain order, which is the only
// order in which the chain can be verified.
func (q *Queries) ListAuditChain(ctx context.Context, arg ListAuditChainParams) ([]ListAuditChainRow, error) {
	rows, err := q.db.Query(ctx, listAuditChain, arg.AccountID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditChainRow
	for rows.Next() {
		var i ListAuditChainRow
		if err := rows.Scan(
			&i.AuditID,
			&i.PlanID,
			&i.AccountID,
			&i.ProjectID,
			&i.RunID,
			&i.NodeID,
			&i.ActorID,
			&i.Action,
			&i.IdempotencyKey,
			&i.PayloadJson,
			&i.CreatedAt,
			&i.PrevHash,
			&i.RowHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditRecords = `-- name: ListAuditRecords :many
SELECT audit_id,
       plan_id,
       account_id,
       project_id,
       COALESCE(run_id, '') AS run_id,
       COALESCE(node_id, '') AS node_id,
       actor_id,
       action,
       idempotency_key,
       payload_json,
       created_at
FROM audit_logs
WHERE plan_id = $1
  AND account_id = $2
  AND project_id = $3
  AND ($4::text = '' OR COALESCE(node_id, '') = $4::text)
  AND ($5::text = '' OR COALESCE(run_id, '') = $5::text)
  AND ($6::text = '' OR action = $6::text)
ORDER BY created_at ASC, audit_id ASC
LIMIT $7::bigint
`

type ListAuditRecordsParams struct {
	PlanID    string
	AccountID string
	ProjectID string
	NodeID    string
	RunID     string
	Action    string
	RowLimit  pgtype.Int8
}

type ListAuditRecordsRow struct {
	AuditID        string
	PlanID         string
	AccountID      string
	ProjectID      string
	RunID          string
	NodeID         string
	ActorID        string
	Action         string
	IdempotencyKey string
	PayloadJson    []byte
	CreatedAt      time.Time
}

// ListAuditRecords lists a plan's audit records oldest-first. The node, run
// and action filters are empty-string-means-absent; a NULL node/run filter
// compares against the COALESCEd empty string so absent stays absent; a NULL
// row_limit is LIMIT ALL.
func (q *Queries) ListAuditRecords(ctx context.Context, arg ListAuditRecordsParams) ([]ListAuditRecordsRow, error) {
	rows, err := q.db.Query(ctx, listAuditRecords,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.NodeID,
		arg.RunID,
		arg.Action,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRecordsRow
	for rows.Next() {
		var i ListAuditRecordsRow
		if err := rows.Scan(
			&i.AuditID,
			&i.PlanID,
			&i.AccountID,
			&i.ProjectID,
			&i.RunID,
			&i.NodeID,
			&i.ActorID,
			&i.Action,
			&i.IdempotencyKey,
			&i.PayloadJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanEvents = `-- name: ListPlanEvents :many
SELECT event_json
FROM plan_events
WHERE plan_id = $1
  AND account_id = $2
  AND project_id = $3
  AND sequence > $4
  AND ($5::text = '' OR node_id = $5::text)
  AND ($6::text = '' OR run_id = $6::text)
ORDER BY sequence ASC
LIMIT $7::bigint
`

type ListPlanEventsParams struct {
	PlanID    string
	AccountID string
	ProjectID string
	Sequence  int64
	NodeID    string
	RunID     string
	RowLimit  pgtype.Int8
}

// ListPlanEvents pages a plan's events by sequence ascending, starting after
// the given sequence. The optional node and run filters are
// empty-string-means-absent; a NULL row_limit is LIMIT ALL.
func (q *Queries) ListPlanEvents(ctx context.Context, arg ListPlanEventsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listPlanEvents,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.Sequence,
		arg.NodeID,
		arg.RunID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event_json []byte
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanNodesByPlanID = `-- name: ListPlanNodesByPlanID :many
SELECT status_json
FROM plan_nodes
WHERE plan_id = $1
ORDER BY node_id ASC
`

// ListPlanNodesByPlanID loads one plan's node status documents ordered by
// node id.
func (q *Queries) ListPlanNodesByPlanID(ctx context.Context, planID string) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listPlanNodesByPlanID, planID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var status_json []byte
		if err := rows.Scan(&status_json); err != nil {
			return nil, err
		}
		items = append(items, status_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlanRefs = `-- name: ListPlanRefs :many

SELECT plan_id, account_id, project_id
FROM plans
WHERE ($1::text = '' OR account_id = $1::text)
  AND ($2::text = '' OR project_id = $2::text)
  AND (COALESCE(cardinality($3::text[]), 0) = 0
       OR lifecycle_state = ANY($3::text[]))
  AND ($4::timestamptz IS NULL OR updated_at > $4::timestamptz)
ORDER BY updated_at ASC, plan_id ASC
LIMIT $5::bigint
`

type ListPlanRefsParams struct {
	AccountID       string
	ProjectID       string
	LifecycleStates []string
	UpdatedAfter    pgtype.Timestamptz
	RowLimit        pgtype.Int8
}

type ListPlanRefsRow struct {
	PlanID    string
	AccountID string
	ProjectID string
}

// RunPlan aggregate persistence: the plans row holds the spec and status
// documents, plan_nodes holds one status document per node, and plan_events
// is the append-only, idempotency-keyed event stream. Sequence allocation
// and the create/append idempotency protocols live in the repository; these
// statements are the SQL they drive.
// ListPlanRefs lists plan references matching the scope filters, oldest
// update first. Optional text filters are empty-string-means-absent; an
// empty lifecycle state array disables that predicate; a NULL updated_after
// or row_limit is "no bound".
func (q *Queries) ListPlanRefs(ctx context.Context, arg ListPlanRefsParams) ([]ListPlanRefsRow, error) {
	rows, err := q.db.Query(ctx, listPlanRefs,
		arg.AccountID,
		arg.ProjectID,
		arg.LifecycleStates,
		arg.UpdatedAfter,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlanRefsRow
	for rows.Next() {
		var i ListPlanRefsRow
		if err := rows.Scan(&i.PlanID, &i.AccountID, &i.ProjectID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecoverablePlanCommands = `-- name: ListRecoverablePlanCommands :many
SELECT command_id,
       plan_id,
       actor_id,
       action,
       idempotency_key,
       payload_json,
       status,
       failure_reason,
       created_at,
       updated_at,
       account_id,
       project_id
FROM plan_commands
WHERE (COALESCE(cardinality($1::text[]), 0) = 0
       OR status = ANY($1::text[]))
  AND ($2::text = '' OR plan_id = $2::text)
  AND ($3::text = '' OR account_id = $3::text)
  AND ($4::text = '' OR project_id = $4::text)
  AND ($5::text = '' OR action = $5::text)
ORDER BY updated_at ASC, command_id ASC
LIMIT $6::bigint
`

type ListRecoverablePlanCommandsParams struct {
	Statuses  []string
	PlanID    string
	AccountID string
	ProjectID string
	Action    string
	RowLimit  pgtype.Int8
}

// ListRecoverablePlanCommands lists commands in the recoverable states
// oldest-update-first. An empty status array disables that predicate; the
// plan/account/project/action filters are empty-string-means-absent; a NULL
// row_limit is LIMIT ALL.
func (q *Queries) ListRecoverablePlanCommands(ctx context.Context, arg ListRecoverablePlanCommandsParams) ([]PlanCommand, error) {
	rows, err := q.db.Query(ctx, listRecoverablePlanCommands,
		arg.Statuses,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.Action,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanCommand
	for rows.Next() {
		var i PlanCommand
		if err := rows.Scan(
			&i.CommandID,
			&i.PlanID,
			&i.ActorID,
			&i.Action,
			&i.IdempotencyKey,
			&i.PayloadJson,
			&i.Status,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccountID,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlanEventSequence = `-- name: LockPlanEventSequence :one
SELECT event_sequence, account_id, project_id
FROM plans
WHERE plan_id = $1
FOR UPDATE
`

type LockPlanEventSequenceRow struct {
	EventSequence int64
	AccountID     string
	ProjectID     string
}

// LockPlanEventSequence takes the plan row lock that serializes event
// appends and returns the current sequence plus the tenant scope.
func (q *Queries) LockPlanEventSequence(ctx context.Context, planID string) (LockPlanEventSequenceRow, error) {
	row := q.db.QueryRow(ctx, lockPlanEventSequence, planID)
	var i LockPlanEventSequenceRow
	err := row.Scan(&i.EventSequence, &i.AccountID, &i.ProjectID)
	return i, err
}

const lockPlanRow = `-- name: LockPlanRow :one
SELECT account_id, project_id
FROM plans
WHERE plan_id = $1
FOR UPDATE
`

type LockPlanRowRow struct {
	AccountID string
	ProjectID string
}

// LockPlanRow takes the plan row lock that serializes a transition save and
// returns the tenant scope.
func (q *Queries) LockPlanRow(ctx context.Context, planID string) (LockPlanRowRow, error) {
	row := q.db.QueryRow(ctx, lockPlanRow, planID)
	var i LockPlanRowRow
	err := row.Scan(&i.AccountID, &i.ProjectID)
	return i, err
}

const recordPlanMetric = `-- name: RecordPlanMetric :execrows
INSERT INTO plan_metric_samples (
    metric_name,
    plan_id,
    account_id,
    project_id,
    node_id,
    run_id,
    event_id,
    sequence,
    value,
    unit,
    labels_json,
    sample_timestamp
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
ON CONFLICT DO NOTHING
`

type RecordPlanMetricParams struct {
	MetricName      string
	PlanID          string
	AccountID       string
	ProjectID       string
	NodeID          string
	RunID           string
	EventID         string
	Sequence        int64
	Value           float64
	Unit            string
	LabelsJson      []byte
	SampleTimestamp time.Time
}

// RecordPlanMetric appends one metric sample. DO NOTHING keeps the first
// sample for an identity; zero affected rows means the identity already
// exists and the caller resolves the collision through the key.
func (q *Queries) RecordPlanMetric(ctx context.Context, arg RecordPlanMetricParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordPlanMetric,
		arg.MetricName,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.NodeID,
		arg.RunID,
		arg.EventID,
		arg.Sequence,
		arg.Value,
		arg.Unit,
		arg.LabelsJson,
		arg.SampleTimestamp,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const savePlanMetricCheckpoint = `-- name: SavePlanMetricCheckpoint :execrows
INSERT INTO plan_metric_checkpoints (
    exporter_id,
    plan_id,
    account_id,
    project_id,
    sequence,
    projection_json,
    updated_at
) VALUES ($1,$2,$3,$4,$5,$6,NOW())
ON CONFLICT (exporter_id, plan_id) DO UPDATE SET
    account_id = EXCLUDED.account_id,
    project_id = EXCLUDED.project_id,
    sequence = EXCLUDED.sequence,
    projection_json = EXCLUDED.projection_json,
    updated_at = NOW()
WHERE plan_metric_checkpoints.sequence <= EXCLUDED.sequence
`

type SavePlanMetricCheckpointParams struct {
	ExporterID     string
	PlanID         string
	AccountID      string
	ProjectID      string
	Sequence       int64
	ProjectionJson []byte
}

// SavePlanMetricCheckpoint writes a checkpoint, updating only when the stored
// sequence has not moved past the incoming one. Zero affected rows is the
// caller's backward-sequence case.
func (q *Queries) SavePlanMetricCheckpoint(ctx context.Context, arg SavePlanMetricCheckpointParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePlanMetricCheckpoint,
		arg.ExporterID,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.Sequence,
		arg.ProjectionJson,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlanCommandStatus = `-- name: UpdatePlanCommandStatus :one
UPDATE plan_commands
SET status = $1,
    failure_reason = $2,
    updated_at = $3
WHERE plan_id = $4
  AND account_id = $5
  AND project_id = $6
  AND idempotency_key = $7
RETURNING command_id,
          plan_id,
          actor_id,
          action,
          idempotency_key,
          payload_json,
          status,
          failure_reason,
          created_at,
          updated_at,
          account_id,
          project_id
`

type UpdatePlanCommandStatusParams struct {
	Status         string
	FailureReason  string
	UpdatedAt      time.Time
	PlanID         string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

// UpdatePlanCommandStatus writes a command's lifecycle state and returns the
// stored row; the tenant-scoped idempotency key identifies it.
func (q *Queries) UpdatePlanCommandStatus(ctx context.Context, arg UpdatePlanCommandStatusParams) (PlanCommand, error) {
	row := q.db.QueryRow(ctx, updatePlanCommandStatus,
		arg.Status,
		arg.FailureReason,
		arg.UpdatedAt,
		arg.PlanID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var i PlanCommand
	err := row.Scan(
		&i.CommandID,
		&i.PlanID,
		&i.ActorID,
		&i.Action,
		&i.IdempotencyKey,
		&i.PayloadJson,
		&i.Status,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccountID,
		&i.ProjectID,
	)
	return i, err
}

const upsertPlan = `-- name: UpsertPlan :exec
INSERT INTO plans (
    plan_id,
    thread_id,
    account_id,
    project_id,
    idempotency_key,
    lifecycle_state,
    reason,
    spec_json,
    status_json,
    requested_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::timestamptz)
ON CONFLICT (plan_id) DO UPDATE SET
    thread_id = EXCLUDED.thread_id,
    account_id = EXCLUDED.account_id,
    project_id = EXCLUDED.project_id,
    lifecycle_state = EXCLUDED.lifecycle_state,
    reason = EXCLUDED.reason,
    spec_json = EXCLUDED.spec_json,
    status_json = EXCLUDED.status_json,
    requested_at = EXCLUDED.requested_at,
    updated_at = NOW()
`

type UpsertPlanParams struct {
	PlanID         string
	ThreadID       string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	LifecycleState string
	Reason         string
	SpecJson       []byte
	StatusJson     []byte
	RequestedAt    pgtype.Timestamptz
}

// UpsertPlan writes a full plan state snapshot. A NULL requested_at is the
// zero domain time; identity columns (plan_id, idempotency_key, created_at)
// are never rewritten by the conflict branch.
func (q *Queries) UpsertPlan(ctx context.Context, arg UpsertPlanParams) error {
	_, err := q.db.Exec(ctx, upsertPlan,
		arg.PlanID,
		arg.ThreadID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.LifecycleState,
		arg.Reason,
		arg.SpecJson,
		arg.StatusJson,
		arg.RequestedAt,
	)
	return err
}

const upsertPlanNode = `-- name: UpsertPlanNode :exec
INSERT INTO plan_nodes (
    plan_id,
    node_id,
    run_id,
    backend_kind,
    backend_name,
    capability,
    lifecycle_state,
    attempts,
    reason,
    status_json
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
ON CONFLICT (plan_id, node_id) DO UPDATE SET
    run_id = EXCLUDED.run_id,
    backend_kind = EXCLUDED.backend_kind,
    backend_name = EXCLUDED.backend_name,
    capability = EXCLUDED.capability,
    lifecycle_state = EXCLUDED.lifecycle_state,
    attempts = EXCLUDED.attempts,
    reason = EXCLUDED.reason,
    status_json = EXCLUDED.status_json,
    updated_at = NOW()
`

type UpsertPlanNodeParams struct {
	PlanID         string
	NodeID         string
	RunID          string
	BackendKind    string
	BackendName    string
	Capability     string
	LifecycleState string
	Attempts       int32
	Reason         string
	StatusJson     []byte
}

// UpsertPlanNode writes one node status projection under its plan.
func (q *Queries) UpsertPlanNode(ctx context.Context, arg UpsertPlanNodeParams) error {
	_, err := q.db.Exec(ctx, upsertPlanNode,
		arg.PlanID,
		arg.NodeID,
		arg.RunID,
		arg.BackendKind,
		arg.BackendName,
		arg.Capability,
		arg.LifecycleState,
		arg.Attempts,
		arg.Reason,
		arg.StatusJson,
	)
	return err
}
