// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: process.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceProcessEventSequence = `-- name: AdvanceProcessEventSequence :exec
UPDATE processes
SET event_sequence = $4
WHERE process_id = $1 AND account_id = $2 AND project_id = $3
`

type AdvanceProcessEventSequenceParams struct {
	ProcessID     string
	AccountID     string
	ProjectID     string
	EventSequence int64
}

// AdvanceProcessEventSequence publishes the next sequence number the locked
// scope handed out.
func (q *Queries) AdvanceProcessEventSequence(ctx context.Context, arg AdvanceProcessEventSequenceParams) error {
	_, err := q.db.Exec(ctx, advanceProcessEventSequence,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.EventSequence,
	)
	return err
}

const getProcessByIdempotencyKey = `-- name: GetProcessByIdempotencyKey :one
SELECT spec_json, status_json
FROM processes
WHERE account_id = $1 AND project_id = $2 AND idempotency_key = $3
`

type GetProcessByIdempotencyKeyParams struct {
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetProcessByIdempotencyKeyRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetProcessByIdempotencyKey resolves a process through its tenant-scoped
// idempotency key, so a replayed create finds the original.
func (q *Queries) GetProcessByIdempotencyKey(ctx context.Context, arg GetProcessByIdempotencyKeyParams) (GetProcessByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getProcessByIdempotencyKey, arg.AccountID, arg.ProjectID, arg.IdempotencyKey)
	var i GetProcessByIdempotencyKeyRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getProcessByRef = `-- name: GetProcessByRef :one

SELECT spec_json, status_json
FROM processes
WHERE process_id = $1 AND account_id = $2 AND project_id = $3
`

type GetProcessByRefParams struct {
	ProcessID string
	AccountID string
	ProjectID string
}

type GetProcessByRefRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// Generic AgentOS process projections: one row per process holding its spec
// and status documents, plus the append-only event log and the
// idempotency-keyed status updates.
// GetProcessByRef loads a process by tenant-scoped reference.
func (q *Queries) GetProcessByRef(ctx context.Context, arg GetProcessByRefParams) (GetProcessByRefRow, error) {
	row := q.db.QueryRow(ctx, getProcessByRef, arg.ProcessID, arg.AccountID, arg.ProjectID)
	var i GetProcessByRefRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getProcessEventByIdempotencyKey = `-- name: GetProcessEventByIdempotencyKey :one
SELECT event_json
FROM process_events
WHERE process_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetProcessEventByIdempotencyKeyParams struct {
	ProcessID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

// GetProcessEventByIdempotencyKey resolves an event through its
// tenant-scoped idempotency key.
func (q *Queries) GetProcessEventByIdempotencyKey(ctx context.Context, arg GetProcessEventByIdempotencyKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProcessEventByIdempotencyKey,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var event_json []byte
	err := row.Scan(&event_json)
	return event_json, err
}

const getProcessStatusByIdempotencyKey = `-- name: GetProcessStatusByIdempotencyKey :one
SELECT status_json
FROM process_status_updates
WHERE process_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetProcessStatusByIdempotencyKeyParams struct {
	ProcessID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

// GetProcessStatusByIdempotencyKey resolves a status update through its
// tenant-scoped idempotency key.
func (q *Queries) GetProcessStatusByIdempotencyKey(ctx context.Context, arg GetProcessStatusByIdempotencyKeyParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getProcessStatusByIdempotencyKey,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const insertProcess = `-- name: InsertProcess :exec
INSERT INTO processes (
    process_id,
    kind,
    account_id,
    project_id,
    resource_kind,
    resource_id,
    idempotency_key,
    lifecycle_state,
    reason,
    spec_json,
    status_json,
    requested_at,
    updated_at
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertProcessParams struct {
	ProcessID      string
	Kind           string
	AccountID      string
	ProjectID      string
	ResourceKind   string
	ResourceID     string
	IdempotencyKey string
	LifecycleState string
	Reason         string
	SpecJson       []byte
	StatusJson     []byte
	RequestedAt    pgtype.Timestamptz
	UpdatedAt      time.Time
}

// InsertProcess stores a new process projection.
func (q *Queries) InsertProcess(ctx context.Context, arg InsertProcessParams) error {
	_, err := q.db.Exec(ctx, insertProcess,
		arg.ProcessID,
		arg.Kind,
		arg.AccountID,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.IdempotencyKey,
		arg.LifecycleState,
		arg.Reason,
		arg.SpecJson,
		arg.StatusJson,
		arg.RequestedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertProcessEvent = `-- name: InsertProcessEvent :exec
INSERT INTO process_events (
    event_id,
    process_id,
    account_id,
    project_id,
    resource_kind,
    resource_id,
    event_type,
    sequence,
    idempotency_key,
    payload_json,
    event_json,
    timestamp
) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertProcessEventParams struct {
	EventID        string
	ProcessID      string
	AccountID      string
	ProjectID      string
	ResourceKind   string
	ResourceID     string
	EventType      string
	Sequence       int64
	IdempotencyKey string
	PayloadJson    []byte
	EventJson      []byte
	Timestamp      time.Time
}

// InsertProcessEvent appends one process event.
func (q *Queries) InsertProcessEvent(ctx context.Context, arg InsertProcessEventParams) error {
	_, err := q.db.Exec(ctx, insertProcessEvent,
		arg.EventID,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.EventType,
		arg.Sequence,
		arg.IdempotencyKey,
		arg.PayloadJson,
		arg.EventJson,
		arg.Timestamp,
	)
	return err
}

const insertProcessStatusUpdate = `-- name: InsertProcessStatusUpdate :exec
INSERT INTO process_status_updates (
    process_id,
    account_id,
    project_id,
    idempotency_key,
    status_json
) VALUES ($1,$2,$3,$4,$5)
`

type InsertProcessStatusUpdateParams struct {
	ProcessID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	StatusJson     []byte
}

// InsertProcessStatusUpdate records that a status update was applied.
func (q *Queries) InsertProcessStatusUpdate(ctx context.Context, arg InsertProcessStatusUpdateParams) error {
	_, err := q.db.Exec(ctx, insertProcessStatusUpdate,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.StatusJson,
	)
	return err
}

const listProcessEvents = `-- name: ListProcessEvents :many
SELECT event_json
FROM process_events
WHERE process_id = $1
  AND account_id = $2
  AND project_id = $3
  AND sequence > $4
ORDER BY sequence ASC
LIMIT $5::bigint
`

type ListProcessEventsParams struct {
	ProcessID string
	AccountID string
	ProjectID string
	Sequence  int64
	RowLimit  pgtype.Int8
}

// ListProcessEvents pages a process's events by sequence ascending, starting
// after the given sequence. A NULL row_limit is LIMIT ALL.
func (q *Queries) ListProcessEvents(ctx context.Context, arg ListProcessEventsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listProcessEvents,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.Sequence,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var event_json []byte
		if err := rows.Scan(&event_json); err != nil {
			return nil, err
		}
		items = append(items, event_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcesses = `-- name: ListProcesses :many
SELECT status_json
FROM processes
WHERE account_id = $1
  AND project_id = $2
  AND ($3::text = '' OR (resource_kind = $3::text AND resource_id = $4))
  AND ($5::text = '' OR kind = $5::text)
  AND ($6::text = '' OR lifecycle_state = $6::text)
ORDER BY updated_at DESC, process_id ASC
LIMIT $7::bigint
`

type ListProcessesParams struct {
	AccountID      string
	ProjectID      string
	ResourceKind   string
	ResourceID     string
	KindFilter     string
	LifecycleState string
	RowLimit       pgtype.Int8
}

// ListProcesses pages a tenant's processes newest-updated first. Optional
// filters are empty-string-means-absent; a NULL row_limit is LIMIT ALL.
func (q *Queries) ListProcesses(ctx context.Context, arg ListProcessesParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listProcesses,
		arg.AccountID,
		arg.ProjectID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.KindFilter,
		arg.LifecycleState,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var status_json []byte
		if err := rows.Scan(&status_json); err != nil {
			return nil, err
		}
		items = append(items, status_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProcessEventScope = `-- name: LockProcessEventScope :one
SELECT process_id, account_id, project_id, resource_kind, resource_id, event_sequence
FROM processes
WHERE process_id = $1 AND account_id = $2 AND project_id = $3
FOR UPDATE
`

type LockProcessEventScopeParams struct {
	ProcessID string
	AccountID string
	ProjectID string
}

type LockProcessEventScopeRow struct {
	ProcessID     string
	AccountID     string
	ProjectID     string
	ResourceKind  string
	ResourceID    string
	EventSequence int64
}

// LockProcessEventScope takes the process row lock that serializes event
// appends for one process, returning the scope and current sequence.
func (q *Queries) LockProcessEventScope(ctx context.Context, arg LockProcessEventScopeParams) (LockProcessEventScopeRow, error) {
	row := q.db.QueryRow(ctx, lockProcessEventScope, arg.ProcessID, arg.AccountID, arg.ProjectID)
	var i LockProcessEventScopeRow
	err := row.Scan(
		&i.ProcessID,
		&i.AccountID,
		&i.ProjectID,
		&i.ResourceKind,
		&i.ResourceID,
		&i.EventSequence,
	)
	return i, err
}

const updateProcessProjection = `-- name: UpdateProcessProjection :execrows
UPDATE processes
SET lifecycle_state = $4,
    reason = $5,
    status_json = $6,
    updated_at = $7
WHERE process_id = $1 AND account_id = $2 AND project_id = $3
`

type UpdateProcessProjectionParams struct {
	ProcessID      string
	AccountID      string
	ProjectID      string
	LifecycleState string
	Reason         string
	StatusJson     []byte
	UpdatedAt      time.Time
}

// UpdateProcessProjection writes a status update's projection. The row count
// tells the caller whether the process still exists.
func (q *Queries) UpdateProcessProjection(ctx context.Context, arg UpdateProcessProjectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProcessProjection,
		arg.ProcessID,
		arg.AccountID,
		arg.ProjectID,
		arg.LifecycleState,
		arg.Reason,
		arg.StatusJson,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
