// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_backend_index.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlanNodeOwner = `-- name: GetPlanNodeOwner :one
SELECT p.account_id, p.project_id, n.node_id, n.run_id
FROM plans p
LEFT JOIN plan_nodes n
    ON n.plan_id = p.plan_id
   AND n.node_id = $2
WHERE p.plan_id = $1
`

type GetPlanNodeOwnerParams struct {
	PlanID string
	NodeID string
}

type GetPlanNodeOwnerRow struct {
	AccountID string
	ProjectID string
	NodeID    pgtype.Text
	RunID     pgtype.Text
}

// GetPlanNodeOwner reads the plan's tenant together with the node's durable
// state in one join: a node row absent or carrying a different run id is an
// ownership violation the caller rejects. The LEFT JOIN keeps a plan with no
// such node readable, which is itself the "node not durable" case.
func (q *Queries) GetPlanNodeOwner(ctx context.Context, arg GetPlanNodeOwnerParams) (GetPlanNodeOwnerRow, error) {
	row := q.db.QueryRow(ctx, getPlanNodeOwner, arg.PlanID, arg.NodeID)
	var i GetPlanNodeOwnerRow
	err := row.Scan(
		&i.AccountID,
		&i.ProjectID,
		&i.NodeID,
		&i.RunID,
	)
	return i, err
}

const getRunBackendIndex = `-- name: GetRunBackendIndex :one

SELECT run_id,
       COALESCE(plan_id, '') AS plan_id,
       COALESCE(node_id, '') AS node_id,
       thread_id,
       account_id,
       project_id,
       backend_kind,
       backend_name,
       idempotency_key,
       lifecycle_state,
       created_at,
       updated_at
FROM run_backend_index
WHERE run_id = $1
`

type GetRunBackendIndexRow struct {
	RunID          string
	PlanID         string
	NodeID         string
	ThreadID       string
	AccountID      string
	ProjectID      string
	BackendKind    string
	BackendName    string
	IdempotencyKey string
	LifecycleState string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// Run backend ownership: which backend kind and name owns each run, keyed by
// run id and deduplicated per tenant by idempotency key. The run/event outbox
// claim joins this table for the tenant, so resolution here is on the
// publish path too.
// GetRunBackendIndex loads one ownership row. plan_id and node_id are stored
// nullable for standalone runs but read as empty strings — the record is a
// flat ownership fact, and "no plan" is the same fact as "empty plan".
func (q *Queries) GetRunBackendIndex(ctx context.Context, runID string) (GetRunBackendIndexRow, error) {
	row := q.db.QueryRow(ctx, getRunBackendIndex, runID)
	var i GetRunBackendIndexRow
	err := row.Scan(
		&i.RunID,
		&i.PlanID,
		&i.NodeID,
		&i.ThreadID,
		&i.AccountID,
		&i.ProjectID,
		&i.BackendKind,
		&i.BackendName,
		&i.IdempotencyKey,
		&i.LifecycleState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRunBackendIndexByIdempotencyKey = `-- name: GetRunBackendIndexByIdempotencyKey :one
SELECT run_id,
       COALESCE(plan_id, '') AS plan_id,
       COALESCE(node_id, '') AS node_id,
       thread_id,
       account_id,
       project_id,
       backend_kind,
       backend_name,
       idempotency_key,
       lifecycle_state,
       created_at,
       updated_at
FROM run_backend_index
WHERE account_id = $1 AND project_id = $2 AND idempotency_key = $3
`

type GetRunBackendIndexByIdempotencyKeyParams struct {
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetRunBackendIndexByIdempotencyKeyRow struct {
	RunID          string
	PlanID         string
	NodeID         string
	ThreadID       string
	AccountID      string
	ProjectID      string
	BackendKind    string
	BackendName    string
	IdempotencyKey string
	LifecycleState string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

// GetRunBackendIndexByIdempotencyKey resolves an ownership row through the
// tenant-scoped idempotency key, so a replayed bind finds its original run.
func (q *Queries) GetRunBackendIndexByIdempotencyKey(ctx context.Context, arg GetRunBackendIndexByIdempotencyKeyParams) (GetRunBackendIndexByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getRunBackendIndexByIdempotencyKey, arg.AccountID, arg.ProjectID, arg.IdempotencyKey)
	var i GetRunBackendIndexByIdempotencyKeyRow
	err := row.Scan(
		&i.RunID,
		&i.PlanID,
		&i.NodeID,
		&i.ThreadID,
		&i.AccountID,
		&i.ProjectID,
		&i.BackendKind,
		&i.BackendName,
		&i.IdempotencyKey,
		&i.LifecycleState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRunBackendIndex = `-- name: InsertRunBackendIndex :execrows
INSERT INTO run_backend_index (
    run_id, plan_id, node_id, thread_id, account_id, project_id,
    backend_kind, backend_name, idempotency_key, lifecycle_state
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (run_id) DO NOTHING
`

type InsertRunBackendIndexParams struct {
	RunID          string
	PlanID         pgtype.Text
	NodeID         pgtype.Text
	ThreadID       string
	AccountID      string
	ProjectID      string
	BackendKind    string
	BackendName    string
	IdempotencyKey string
	LifecycleState string
}

// InsertRunBackendIndex records ownership. DO NOTHING keeps the first bind
// for a run id; the caller resolves the collision through the idempotency
// path (zero affected rows means a conflicting bind, not a silent overwrite).
func (q *Queries) InsertRunBackendIndex(ctx context.Context, arg InsertRunBackendIndexParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertRunBackendIndex,
		arg.RunID,
		arg.PlanID,
		arg.NodeID,
		arg.ThreadID,
		arg.AccountID,
		arg.ProjectID,
		arg.BackendKind,
		arg.BackendName,
		arg.IdempotencyKey,
		arg.LifecycleState,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRunBackendLifecycle = `-- name: UpdateRunBackendLifecycle :exec
UPDATE run_backend_index
SET lifecycle_state = $2,
    updated_at = NOW()
WHERE run_id = $1
`

type UpdateRunBackendLifecycleParams struct {
	RunID          string
	LifecycleState string
}

// UpdateRunBackendLifecycle advances a run's lifecycle state on a bind whose
// run already exists with the same declaration.
func (q *Queries) UpdateRunBackendLifecycle(ctx context.Context, arg UpdateRunBackendLifecycleParams) error {
	_, err := q.db.Exec(ctx, updateRunBackendLifecycle, arg.RunID, arg.LifecycleState)
	return err
}
