// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workset.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimWorksetChunkResult = `-- name: ClaimWorksetChunkResult :one
INSERT INTO workset_chunk_results (workset_id, account_id, project_id, chunk_id, idempotency_key, result_json, status_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (account_id, project_id, workset_id, chunk_id, idempotency_key) DO NOTHING
RETURNING status_json
`

type ClaimWorksetChunkResultParams struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	ChunkID        string
	IdempotencyKey string
	ResultJson     []byte
	StatusJson     []byte
}

// ClaimWorksetChunkResult inserts a chunk result's claim, same protocol as
// the status update claim.
func (q *Queries) ClaimWorksetChunkResult(ctx context.Context, arg ClaimWorksetChunkResultParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, claimWorksetChunkResult,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
		arg.ChunkID,
		arg.IdempotencyKey,
		arg.ResultJson,
		arg.StatusJson,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const claimWorksetStatusUpdate = `-- name: ClaimWorksetStatusUpdate :one
INSERT INTO workset_status_updates (workset_id, account_id, project_id, idempotency_key, status_json)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, project_id, workset_id, idempotency_key) DO NOTHING
RETURNING status_json
`

type ClaimWorksetStatusUpdateParams struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
	StatusJson     []byte
}

// ClaimWorksetStatusUpdate inserts an update's claim; ON CONFLICT DO NOTHING
// plus RETURNING means no row comes back when the key already exists, and
// the caller then reads the stored status instead.
func (q *Queries) ClaimWorksetStatusUpdate(ctx context.Context, arg ClaimWorksetStatusUpdateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, claimWorksetStatusUpdate,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
		arg.StatusJson,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const getWorksetByID = `-- name: GetWorksetByID :one
SELECT spec_json, status_json
FROM worksets
WHERE workset_id = $1
`

type GetWorksetByIDRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetWorksetByID loads a workset's spec and status documents by id.
func (q *Queries) GetWorksetByID(ctx context.Context, worksetID string) (GetWorksetByIDRow, error) {
	row := q.db.QueryRow(ctx, getWorksetByID, worksetID)
	var i GetWorksetByIDRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getWorksetByIdempotencyKey = `-- name: GetWorksetByIdempotencyKey :one
SELECT spec_json, status_json
FROM worksets
WHERE account_id = $1 AND project_id = $2 AND idempotency_key = $3
`

type GetWorksetByIdempotencyKeyParams struct {
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

type GetWorksetByIdempotencyKeyRow struct {
	SpecJson   []byte
	StatusJson []byte
}

// GetWorksetByIdempotencyKey resolves a workset through its tenant-scoped
// registration key, so a replayed create finds the original.
func (q *Queries) GetWorksetByIdempotencyKey(ctx context.Context, arg GetWorksetByIdempotencyKeyParams) (GetWorksetByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getWorksetByIdempotencyKey, arg.AccountID, arg.ProjectID, arg.IdempotencyKey)
	var i GetWorksetByIdempotencyKeyRow
	err := row.Scan(&i.SpecJson, &i.StatusJson)
	return i, err
}

const getWorksetChunkStatus = `-- name: GetWorksetChunkStatus :one
SELECT status_json
FROM workset_chunk_results
WHERE workset_id = $1 AND account_id = $2 AND project_id = $3
  AND chunk_id = $4 AND idempotency_key = $5
`

type GetWorksetChunkStatusParams struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	ChunkID        string
	IdempotencyKey string
}

// GetWorksetChunkStatus loads the status a prior chunk result stored.
func (q *Queries) GetWorksetChunkStatus(ctx context.Context, arg GetWorksetChunkStatusParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorksetChunkStatus,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
		arg.ChunkID,
		arg.IdempotencyKey,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const getWorksetStatusUpdate = `-- name: GetWorksetStatusUpdate :one
SELECT status_json
FROM workset_status_updates
WHERE workset_id = $1 AND account_id = $2 AND project_id = $3 AND idempotency_key = $4
`

type GetWorksetStatusUpdateParams struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	IdempotencyKey string
}

// GetWorksetStatusUpdate loads the status a prior idempotent update stored.
func (q *Queries) GetWorksetStatusUpdate(ctx context.Context, arg GetWorksetStatusUpdateParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getWorksetStatusUpdate,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
		arg.IdempotencyKey,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const insertWorkset = `-- name: InsertWorkset :one

INSERT INTO worksets (
    workset_id, account_id, project_id, process_id,
    resource_kind, resource_id, kind, lifecycle_state, idempotency_key,
    spec_json, status_json, requested_at, updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING status_json
`

type InsertWorksetParams struct {
	WorksetID      string
	AccountID      string
	ProjectID      string
	ProcessID      string
	ResourceKind   string
	ResourceID     string
	Kind           string
	LifecycleState string
	IdempotencyKey string
	SpecJson       []byte
	StatusJson     []byte
	RequestedAt    pgtype.Timestamptz
	UpdatedAt      time.Time
}

// Batch worksets: spec and status projections with idempotent status
// updates and chunk results. The spec/status pair is the projection; the
// workset_status_updates and workset_chunk_results tables are the
// claim-before-apply ledgers that make updates replayable.
// InsertWorkset persists a new workset projection and returns the stored
// status document.
func (q *Queries) InsertWorkset(ctx context.Context, arg InsertWorksetParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, insertWorkset,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
		arg.ProcessID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Kind,
		arg.LifecycleState,
		arg.IdempotencyKey,
		arg.SpecJson,
		arg.StatusJson,
		arg.RequestedAt,
		arg.UpdatedAt,
	)
	var status_json []byte
	err := row.Scan(&status_json)
	return status_json, err
}

const listWorksets = `-- name: ListWorksets :many
SELECT status_json
FROM worksets
WHERE account_id = $1
  AND project_id = $2
  AND ($3::text = '' OR process_id = $3::text)
  AND ($4::text = '' OR (resource_kind = $4::text AND resource_id = $5))
  AND ($6::text = '' OR kind = $6::text)
  AND ($7::text = '' OR lifecycle_state = $7::text)
ORDER BY updated_at DESC, workset_id ASC
LIMIT $8::bigint
`

type ListWorksetsParams struct {
	AccountID      string
	ProjectID      string
	ProcessID      string
	ResourceKind   string
	ResourceID     string
	Kind           string
	LifecycleState string
	RowLimit       pgtype.Int8
}

// ListWorksets pages workset statuses newest-first inside a tenant. Optional
// filters are empty-string-means-absent: an empty narg disables the
// predicate, preserving the caller's filter semantics. A NULL row_limit is
// LIMIT ALL.
func (q *Queries) ListWorksets(ctx context.Context, arg ListWorksetsParams) ([][]byte, error) {
	rows, err := q.db.Query(ctx, listWorksets,
		arg.AccountID,
		arg.ProjectID,
		arg.ProcessID,
		arg.ResourceKind,
		arg.ResourceID,
		arg.Kind,
		arg.LifecycleState,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var status_json []byte
		if err := rows.Scan(&status_json); err != nil {
			return nil, err
		}
		items = append(items, status_json)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorksetProjection = `-- name: UpdateWorksetProjection :execrows
UPDATE worksets
SET lifecycle_state = $1, status_json = $2, updated_at = $3
WHERE workset_id = $4 AND account_id = $5 AND project_id = $6
`

type UpdateWorksetProjectionParams struct {
	LifecycleState string
	StatusJson     []byte
	UpdatedAt      time.Time
	WorksetID      string
	AccountID      string
	ProjectID      string
}

// UpdateWorksetProjection writes the claimed status into the projection.
// Zero affected rows means the workset vanished mid-update — a tenant-scope
// error to the caller, never a silent success.
func (q *Queries) UpdateWorksetProjection(ctx context.Context, arg UpdateWorksetProjectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWorksetProjection,
		arg.LifecycleState,
		arg.StatusJson,
		arg.UpdatedAt,
		arg.WorksetID,
		arg.AccountID,
		arg.ProjectID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
